---
title: "Parte ?: "
format: html
---

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(tidyverse)
```

<!--
NOTA: Se importan los conjuntos de datos con la identificación de los taqs y singletones.
-->

```{r}
#| label: Importación de conjuntos de datos

# Se importa los datos con la identificación de los taqs ----

dat_taqs <- read_delim(file = 'single_taqs/Datos/datPuros/SNP_only_tags_ANI.txt', col_names = FALSE, delim = ' ') |>
  rename(
    ID_marc_HD = X1 # Como los tags estan obtenidos de genotipados a alta densidad (HD), se coloca el nombre de estos como ID_marc_HD (de identificación de marcadores genotipados a alta densidad).
    )

# Se importa los datos con la identificación de los singletones ----

dat_sing <- read_delim(file = 'single_taqs/Datos/datPuros/SNP_single_ANI.txt', col_names = FALSE, delim = ' ') |>
  rename(
    ID_marc_HD = X1 # Como los singletones estan obtenidos de genotipados a alta densidad (HD), se coloca el nombre de estos como ID_marc_HD (de identificación de marcadores genotipados a alta densidad).
    )
```

<!--
NOTA: A continuación se identifican los taqs y singletones presentes como marcadores imputados.
-->

```{r}
#| label: taqs y singletones imputados

# Se importa el conjunto de datos que contiene el nombre de los marcadores en común entre genotipado a media densidad (50k) y a alta densidad (HD) ----

marc_50k_HD <- read_delim(file = 'Imputacion/Imp_HD/Datos/datQC_2/nomb_marc_comun.txt', col_names = FALSE, delim = ' ') |>
  rename(
    ID_marc_HD = X1,
    ID_marc_50k = X2
    ) 

# Se identifican los marcadores presentes tanto en el conjunto de datos que se imputo a densidad media (50k) y alta (HD), como en el conjunto de datos con el nombre de los taqs ----

marc_50k_HD |>
  inner_join(dat_taqs, by = 'ID_marc_HD') |>
  write_delim(file = 'single_taqs/Datos/imput_taqs.txt', col_names = FALSE)

# Se identifican los marcadores presentes tanto en el conjunto de datos que se imputo a densidad media (50k) y alta (HD), como en el conjunto de datos con el nombre de los singletones ----

marc_50k_HD |>
  inner_join(dat_sing, by = 'ID_marc_HD') |> # NOTA: REVISAR, PARECE SER QUE NO HAY SINGLETONES QUE HAYAN SIDO IMPUTADOS.
  write_delim(file = 'single_taqs/Datos/imput_sing.txt', col_names = FALSE)
```

<!--
NOTA: .
-->

```{r}
#| label: Hola

# Se importa el conjunto de datos anterior con el nombre de los marcadores imputados y que son taqs ----

imput_taqs <- read_delim(file = 'single_taqs/Datos/imput_taqs.txt', col_names = FALSE, delim = ' ', col_select = c(X2)) |>
  rename('ID genotipos' = X2)

# Se importa el archivo con los genotipos reales y posteriormente imputados con Beagle v. 5.4 ----

datGen <- read_delim(file = 'Imputacion/Beagle/Datos/Precision/datGen.txt', col_names = FALSE, delim = ' ')

# Se extrae el nombre de los marcadores del archivo "Paso_5.bim" y luego se coloca el nombre de los marcadores como corresponde en cada columna ----

nomGen <- read_table(file = 'Imputacion/Beagle/Datos/Precision/Paso_5.bim', col_names = FALSE) |>
  pull(X2)

colnames(datGen) <- c('IID', paste0(nomGen))

# Se pasa a formato largo ----

datGen_2 <- datGen |>
  pivot_longer(
    cols = c(2:585),
    names_to = 'ID genotipos',
    values_to = 'Genotipos reales'
    )

#######################
# Grupo 1 de validación
#######################

# Se importa el nombre de los individuos que hacen parte del primer grupo de validación ----

Grup1 <- read_delim(file = 'Imputacion/Beagle/Datos/Precision/Prec_1/Grup1.txt', delim = ' ', col_names = FALSE)

# Se importa el archivo de genotipos imputados con Beagle v. 5.4 y luego se coloca el nombre de los marcadores como corresponde en cada columna ----

datGen1 <- read_delim(file = 'Imputacion/Beagle/Datos/Precision/Prec_1/datGen1_v5.4.txt', col_names = FALSE, delim = ' ')

colnames(datGen1) <- c('IID', paste0(nomGen))

# Se eligen solo los individuos del primer grupo de validación ----

datGen1_2 <- datGen1 |>
  filter(IID %in% Grup1$X1) # La expresión IID %in% Grup1$X1 filtra las filas en las que el valor de la columna IID está presente en el objeto Grup1$X1.

# Se pasa a formato largo y se une con el objeto que contiene los genotipos reales ----

Prec_imput_1 <- datGen1_2 |>
  pivot_longer(
    cols = c(2:585),
    names_to = 'ID genotipos',
    values_to = 'Genotipos imputados'
    ) |>
  inner_join(datGen_2, by = c('IID', 'ID genotipos')) |>
  mutate(
    Grupo_val = 'Primero' # Se indica el grupo de validación (primer grupo).
  )

# Se une el anterior objeto de genotipos reales e imputados con el objeto que contiene el nombre de los taqs que también fueron imputados ----

imput_taqs_2 <- Prec_imput_1 |>
  inner_join(y = imput_taqs, by = 'ID genotipos')

# ----

imput_taqs |>
  filter(`Genotipos imputados` == `Genotipos reales`)
```
