---
title: "Parte 23: Formación de grupos de validación mediante k-means y, verificación de parentesco basado en segmentos dentro de grupos de validación y entre grupos de validación"
format: html
---

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(tidyverse, tidyclust, tidymodels, ggplot2)
```

<!--
NOTA: Se estima el parentesco a partir de la información del pedigrí (coascendencia geneológica), tanto de individuos genotipados como no genotipados.
-->

```{r}
#| label: Parentesco basado en el pedigrí

# Se importa la ID de los individuos genotipados y se indica que estos estan genotipados con TRUE ----

# Se importa el pedigrí en el que se incluyen individuos genotipados y no genotipados (que se uso al imputar a media densidad) ----

ped_1 <- read_delim(file = 'Paternidad/Datos/datPed.txt', delim = ' ', col_names = FALSE) |> # NOTA: En este pedigrí no estan 76 de los 284 individuos genotipados. Por ejemplo, el individuo "ES000803645478". Los pasos a continuaicón (obejtos "ped_2", "ped_3" y "ped_4") permiten incluir estos 76 individuos. 
  rename(
    ID_id = X1,
    ID_pad = X2,
    ID_mad = X3
    ) |>
  mutate(
    ID_pad = replace(ID_pad, ID_pad == 0, NA),
    ID_mad = replace(ID_mad, ID_mad == 0, NA)
    ) # Los valores en cero en las columnas de padre y madre deben pasarse a NA.

# Se importa el pedigrí en el que se incluyen individuos genotipados (que se uso al imputar a alta densidad) ----

ped_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/datPed.txt', delim = ' ', col_names = FALSE) |>
  rename(
    ID_id = X1,
    ID_pad = X2,
    ID_mad = X3
    ) |>
  mutate(
    ID_pad = replace(ID_pad, ID_pad == 0, NA),
    ID_mad = replace(ID_mad, ID_mad == 0, NA)
    ) # Los valores en cero en las columnas de padre y madre deben pasarse a NA.

# Se observa a continuación los individuos que estan en el pedigrí "ped_2" pero que no estan presentes en el pedigrí del objeto "ped_1" ----

ped_3 <- anti_join(x = ped_2, y = ped_1, by = 'ID_id')

# Se unen los objetos "ped_1" y "ped_3" para obtener un pedigrí completo en el que se incluyan los 284 individuos genotipados ----

ped_4 <- bind_rows(ped_1, ped_3)

# Se prepara el pedigrí para posterior análisis ----

ped <- optiSel::prePed(Pedig = ped_4) # Se prepara el pedigrí con la función prePed(). Esta función ordena el pedigrí, agrega nuevas líneas para los fundadores y corrige algunos errores de pedigrí en caso de que los tuviera.

# Se calcula el parentesco basado en el pedigrí ----

fped <- optiSel::pedIBD(Pedig = ped) # La función pedIBD() permite definir una matriz de relaciones para los fundadores. Por defecto, los fundadores no están relacionados ni son endogámicos.
```

<!--
NOTA: A continuación, de la matriz de parentesco basado en el pedigrí (o matriz A) calculado anteriormente, solo se extrae la parte que corresponde a los 284 individuos genotipados.
-->

```{r}
#| label: Parentesco basado en el pedigrí de individuos genotipados

# Se importa la ID de los individuos genotipados ----

id_geno <- read_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/datPed.txt', delim = ' ', col_names = FALSE) |>
  select(X1) |> # Se extrae la ID de los individuos genotipados.
  rename(ID_id = X1)

# Se crea el objeto "id_fped" en el que se indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco calculado anteriormente ----

id_fped <- tibble(ID_id = colnames(fped)) |>
  mutate(Indice = row_number()) |>
  inner_join(x = id_geno, by = 'ID_id')

# Se extrae la matriz de parentesco (o matriz A) de los 284 indivdiuos genotipados ----

mA_Geno <- fped[id_fped$Indice, id_fped$Indice]
```

<!--
NOTA: Se calcula la matriz de disimilitud (matriz D) entre individuos genotipados a partir de los elementos de la matriz A anterior.
-->

```{r}
#| label: Matriz D de disimilitud 1

# Utilizando el paquete "optiSel", se convierte la matriz A anterior en una matriz de disimilitud ---- 

mD <- optiSel::sim2dis(f = mA_Geno) # En el argumento "f" se indica la matriz de similitud (con valores entre 0 y 1, por ejemplo, la matriz de parentesco basado en el pedigri) que se quiere convertir en una matriz de disimilitud. Los otros argumentos dentro de la función sim2dist() se usaron por defecto, entre ellos, el método (el método 1 tiene la ventaja de que el área refleja de manera más razonable la diversidad de una población).
```

<!--
NOTA: Se observa a continuaicón el número adecuado de clústeres.
-->

```{r}
#| label: Número adecuado de clústeres

# NOTA: Me guie de estos blogs (https://tidyclust.tidymodels.org/articles/k_means.html y https://tidyclust.tidymodels.org/articles/tuning_and_metrics.html) para hacer el análisis a continuación.

set.seed(1234) # Se establece una semilla para garantizar que los resultados sean reproducibles.

# Se genera un subconjunto de validación mediante validación cruzada k-fold ----

mD_VC <- vfold_cv(data = mD, v = 10) # Se genera un subconjunto de validación usando parámetros predeterminados (v = 10).

# Se especifica el modelo de k-means ----

k_med_1 <- k_means(num_clusters = tune()) |> # Como el objetivo aquí será seleccionar la cantidad adecuada de clúteres, se usa tune().
  set_engine('stats', algorithm = 'Hartigan-Wong') # Se indica aquí los detalles algorítmicos: stats::kmeans (este sería el motor del modelo)  y "Hartigan-Wong" como algoritmo dentro de esta implementación.

# Se ajusta el modelo de k-means ----

k_med_2 <- recipe(formula = ~ ., data = mD) # Se proporciona aquí la formula del modelo. A diferencia del modelado supervisado, la fórmula no debe incluir una variable de respuesta.

# Se combinan los dos pasos anteriores mediante un flujo de trabajo ----

k_med_3 <- workflow() |>
  add_model(k_med_1) |>
  add_recipe(k_med_2)

# Se establece un rango de valores posibles de "num_clusters" ----

clust_num_grid <- grid_regular(num_clusters(range = c(1L, 20L)), levels = 20) # Se establece en 20 como el rango de valores posibles de "num_clusters".  La función grid_regular() genera una cuadrícula de valores distribuidos uniformemente dentro de un rango especificado. En este caso, se está especificando que el número de clústeres puede variar entre 1 y 20, con un total de 20 niveles (o valores). Entonces, clust_num_grid contendrá una secuencia de valores del 1 al 20, que serán utilizados para ajustar el modelo de k-means con diferentes números de clústeres y evaluar su desempeño utilizando validación cruzada.

# Se usa la función tune_cluster() para calcular las métricas en cada división de validación cruzada, para cada posible elección del número de clústeres anterior ----

res <- tune_cluster(
  k_med_3,
  resamples = mD_VC,
  grid = clust_num_grid,
  control = control_grid(save_pred = TRUE, extract = identity), # La función control_grid() es del paquete "tune".
  metrics = cluster_metric_set(sse_within_total, sse_total, sse_ratio) # La función cluster_metric_set() es del paquete "tidyclust".
  )

res_metricas <- res |>
  collect_metrics() # La función collect_metrics() se utiliza para recopilar y resumir las métricas.

# Se observa la cantidad adecuada de clústeres ----

res_metricas |>
  filter(.metric == 'sse_ratio') |> # Un enfoque común para elegir una cantidad de clústeres adecuado es buscar un “codo”, o curvatura notable, en el gráfico de la relación WSS/TSS por número de conglomerados.
  ggplot(aes(x = num_clusters, y = mean)) +
  geom_line(colour = 'black', linewidth = 1.2, alpha = 0.2) +
  geom_point(size = 2.4, colour = 'orange') +
  scale_x_continuous(breaks = 1:20) + # Mediante la regla del codo se observa que con cada aumento en el número de clústeres, la relación WSS/TSS disminuye. Se observa también que la disminución del primer al segundo cluśter es muy extrema en relación a las disminución en el resto de clústeres (la cantidad de disminución es menor en estas), por lo que problablemente se deberían elegir dos grupos.
  labs(x = 'Número de clústeres', y = 'Relación media de WSS/TSS') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold'),
    plot.caption = element_text(color = 'black', face = 'italic', hjust = 0)
    ) # Es común observar la forma del gráfico de la "Relación media de WSS/TSS" (Within-Cluster Sum of Squares / Total Sum of Squares) en función del número de clústeres y buscar un punto donde se observe un cambio notable o una "curva de codo". Este cambio puede indicar un punto de disminución significativamente menor en la relación WSS/TSS, lo que sugiere que agregar más clústeres no proporciona una mejora sustancial en la capacidad del modelo para explicar la varianza en los datos.

# NOTA: Una métrica simple es el error de suma de cuadrados (WSS) dentro del grupo , que mide la suma de todas las distancias desde las observaciones hasta el centro del grupo. A veces esto se escala con el error total de suma de cuadrados (TSS) , la distancia desde todas las observaciones hasta el centroide global; en particular, a menudo se calcula la relación WSS/TSS. En principio, valores pequeños de WSS o de la relación WSS/TSS sugieren que las observaciones dentro de los conglomerados son más cercanas (más similares) entre sí que con los otros conglomerados.

ggsave('Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Imagenes/kmeans_ped.pdf', width = 40, height = 20, units = 'cm')
```

<!--
NOTA: Con base en el número adecuado de clústeres anterior, se ajusta el modelo k-means con diez clústeres.
-->

```{r}
#| label: Modelo k-means con diez clústeres

set.seed(1234) # Se establece una semilla para garantizar que los resultados sean reproducibles.

# Se especifica el modelo de k-means ----

k_med_1 <- k_means(num_clusters = 10) |> # Se indica aquí que el número de clústeres adecuados es de 10. NOTA: Si bien aquí se indica como 10, en el gráfico anterior no se pudo observar un punto claro de codo lo que hizo que la elección del número óptimo de clústeres fuera más difícil.
  set_engine('stats', algorithm = 'Hartigan-Wong')

# Se ajusta el modelo de k-means ----

k_med_2 <- recipe(formula = ~ ., data = mD)

# Se combinan los dos pasos anteriores mediante un flujo de trabajo ----

k_med_3 <- workflow() |>
  add_model(k_med_1) |>
  add_recipe(k_med_2)

# Se ajusta el modelo de k-means ----

k_med_4 <- fit(k_med_3, data = mD)

k_med_resumen <- k_med_4 |>
  extract_fit_summary() # Con la función extract_fit_summary() se produce una lista de información resumida del modelo.

asignacion_grupos <- tibble(
  Grupos = k_med_resumen$orig_labels,
  Cluster = k_med_resumen$cluster_assignments
  ) # El objetivo principal de ajustar un modelo de agrupamiento (k-means) suele ser asignar observaciones (en este caso individuos) a los conglomerados. Aquí se puede observar estas asignaciones.

# Se observan algunas de las métricas para cuantificar la calidad de una partición o estructura de clúster particular ----

k_med_4 |> sse_within_total() # Aquí se calcula la suma del error al cuadrado (SSE) dentro del clúster.

k_med_4 |> sse_total() # Aquí se calcula la SSE total.

k_med_4 |> sse_ratio() # Aquí se calcula la relación entre el WSS y el SSE total.

# NOTA: Todas estas métricas dependen de la medición de la distancia entre puntos y/o centroides. Por defecto, se utiliza la distancia euclidiana ordinaria. Sin embargo, es posible seleccionar una función de distancia diferente. Se puede consultar el blog (https://tidyclust.tidymodels.org/articles/k_means.html) en caso de que se quiera profundizar más en esto.
```

<!--
NOTA: A continuación, se obtiene el parentesco de los individuos genotipados a partir de estimaciones basadas en segmentos.
-->

```{r}
#| label: Parentesco basado en segmentos

# NOTA: Las estimaciones anteriores basadas en el pedigrí tienen la desventaja de que el muestreo mendeliano en todos los ancestros se considera aleatorio, por lo que no se puede explicar los alelos que los ancestros realmente heredaron de sus padres. En general, se recomienda el uso de estimaciones basadas en segmentos para tener en cuenta el muestreo mendeliano.

# Usando PLINK se obtiene el archivo *.vcf con el fin de obtener los genotipos en fase ----

plink <- function(PLINKopciones = '') system(paste('/home/leonardo/Escritorio/Doc_p1/Plink/Datos/plink', PLINKopciones)) # Esto permitirá ejecutar PLINK dentro de R.

plink() # Al correr esta línea de código aparecen las opciones de PLINK, la versión, entre otros, lo que indica que si se cargo bien este software dentro del ambiente R.

plink('--cow --allow-extra-chr --bfile Imputacion/Imp_HD/Datos/datQC_2/Paso_14 --recode vcf --alleleACGT --out Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Paso_1 --const-fid')

# Se elimina del encabezado (ID de los individuos) la parte repetida ----

system("sed 's/_ES[0-9]\\{12\\}//g' 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Paso_1.vcf' > 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Paso_2.vcf'") # En los último individuos tuve que eliminar la parte repetida manualmente.

# A continuación, para cada cromosoma, se extraen los genotipos en fase (como 0/1, 0/0, 1/0 y ./., este último en caso de missing). Así lo requiere el paquete optiSel ----

datos_vcf <- data.table::fread('Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Paso_2.vcf', sep = '\t', skip = '#CHROM', header = TRUE) # Con skip = "#CHROM" se indica iniciar en la fila donde estan los nombres de las columnas.

ruta_base <- 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/genotipos.Chr' # Esta es la ruta base para guardar los archivos de genotipos. El nombre de estos archivos debe contener la palabra .Chr*, donde * corresponde al número de cromosoma.

for (cromosoma in 1:29) { # Este bucle itera sobre los cromosomas, filtra los datos del VCF para cada cromosoma y escribe los archivos de genotipos.
  
  # Filtrar los datos del VCF para el cromosoma actual:
  datos_cromosoma <- datos_vcf |>
    filter(`#CHROM` == cromosoma) |>
    select(-c(4:9))
  
  # Escribir los datos del cromosoma en un archivo:
  ruta_archivo <- paste0(ruta_base, cromosoma)
  write_delim(datos_cromosoma, file = ruta_archivo, col_names = TRUE, delim = ' ')
  }

# Se obtiene la información de mapa (map) como lo requiere el paquete optiSel ----

bim <- read_table(file = 'Imputacion/Imp_HD/Datos/datQC_2/Paso_14.bim', col_names = FALSE) |>
  select(X2, X1, X4) |>
  rename(
    Name = X2,
    Chr = X1,
    Mb = X4
    ) |>
  mutate(Mb = Mb / 1000000) # Se pasa a Mb.

# Se leen los archivos (files) con la información de los genotipos en cada uno de los 29 cromosomas del bovino, y se cálcula el parentesco basado en segmentos con el paquete optiSel ----

files <-paste0('Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/genotipos.Chr', 1:29)

fseg <- optiSel::segIBD(files = files, map = bim)

fseg |>
  save(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/fseg.RData')
```

<!--
NOTA: Se calcula la matriz de disimilitud (matriz D) entre individuos genotipados a partir de los elementos de la matriz de parentesco basado en segmentos anterior.
-->

```{r}
#| label: Matriz D de disimilitud 2

# Se carga la anterior matriz de parentesco basado en segmentos  ---

load(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/fseg.RData')

# Utilizando el paquete "optiSel", se convierte la matriz de parentesco basado en segmentos anterior en una matriz de disimilitud ---- 

mD <- optiSel::sim2dis(f = fseg)
```

<!--
NOTA: Se observa a continuaicón el número adecuado de clústeres.
-->

```{r}
#| label: Número adecuado de clústeres

# NOTA: Me guie de estos blogs (https://tidyclust.tidymodels.org/articles/k_means.html y https://tidyclust.tidymodels.org/articles/tuning_and_metrics.html) para hacer el análisis a continuación.

set.seed(1234) # Se establece una semilla para garantizar que los resultados sean reproducibles.

# Se genera un subconjunto de validación mediante validación cruzada k-fold ----

mD_VC <- vfold_cv(data = mD, v = 10) # Se genera un subconjunto de validación usando parámetros predeterminados (v = 10).

# Se especifica el modelo de k-means ----

k_med_1 <- k_means(num_clusters = tune()) |> # Como el objetivo aquí será seleccionar la cantidad adecuada de clúteres, se usa tune().
  set_engine('stats', algorithm = 'Hartigan-Wong') # Se indica aquí los detalles algorítmicos: implementación stats::kmeans (este sería el motor del modelo)  y "Hartigan-Wong" como algoritmo dentro de esta implementación.

# Se ajusta el modelo de k-means ----

k_med_2 <- recipe(formula = ~ ., data = mD) # Se proporciona aquí la formula del modelo. A diferencia del modelado supervisado, la fórmula no debe incluir una variable de respuesta.

# Se combinan los dos pasos anteriores mediante un flujo de trabajo ----

k_med_3 <- workflow() |>
  add_model(k_med_1) |>
  add_recipe(k_med_2)

# Se establece un rango de valores posibles de "num_clusters" ----

clust_num_grid <- grid_regular(num_clusters(range = c(1L, 20L)), levels = 20) # Se establece en 20 como el rango de valores posibles de "num_clusters".  La función grid_regular() genera una cuadrícula de valores distribuidos uniformemente dentro de un rango especificado. En este caso, se está especificando que el número de clústeres puede variar entre 1 y 20, con un total de 20 niveles (o valores). Entonces, clust_num_grid contendrá una secuencia de valores del 1 al 20, que serán utilizados para ajustar el modelo de k-means con diferentes números de clústeres y evaluar su desempeño utilizando validación cruzada.

# Se usa la función tune_cluster() para calcular las métricas en cada división de validación cruzada, para cada posible elección del número de clústeres anterior ----

res <- tune_cluster(
  k_med_3,
  resamples = mD_VC,
  grid = clust_num_grid,
  control = control_grid(save_pred = TRUE, extract = identity), # La función control_grid() es del paquete "tune".
  metrics = cluster_metric_set(sse_within_total, sse_total, sse_ratio) # La función cluster_metric_set() es del paquete "tidyclust".
  )

res_metricas <- res |>
  collect_metrics() # La función collect_metrics() se utiliza para recopilar y resumir las métricas.

# Se observa la cantidad adecuada de clústeres ----

res_metricas |>
  filter(.metric == 'sse_ratio') |> # Un enfoque común para elegir una cantidad de clústeres adecuado es buscar un “codo”, o curvatura notable, en el gráfico de la relación WSS/TSS por número de conglomerados.
  ggplot(aes(x = num_clusters, y = mean)) +
  geom_line(colour = 'black', linewidth = 1.2, alpha = 0.2) +
  geom_point(size = 2.4, colour = 'orange') +
  scale_x_continuous(breaks = 1:20) + # Mediante la regla del codo se observa que con cada aumento en el número de clústeres, la relación WSS/TSS disminuye. Se observa también que la disminución del primer al segundo cluśter es muy extrema en relación a las disminución en el resto de clústeres (la cantidad de disminución es menor en estas), por lo que problablemente se deberían elegir dos grupos.
  labs(x = 'Número de clústeres', y = 'Relación media de WSS/TSS') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold'),
    plot.caption = element_text(color = 'black', face = 'italic', hjust = 0)
    ) # Es común observar la forma del gráfico de la "Relación media de WSS/TSS" (Within-Cluster Sum of Squares / Total Sum of Squares) en función del número de clústeres y buscar un punto donde se observe un cambio notable o una "curva de codo". Este cambio puede indicar un punto de disminución significativamente menor en la relación WSS/TSS, lo que sugiere que agregar más clústeres no proporciona una mejora sustancial en la capacidad del modelo para explicar la varianza en los datos.

# NOTA: Una métrica simple es el error de suma de cuadrados (WSS) dentro del grupo , que mide la suma de todas las distancias desde las observaciones hasta el centro del grupo. A veces esto se escala con el error total de suma de cuadrados (TSS) , la distancia desde todas las observaciones hasta el centroide global; en particular, a menudo se calcula la relación WSS/TSS. En principio, valores pequeños de WSS o de la relación WSS/TSS sugieren que las observaciones dentro de los conglomerados son más cercanas (más similares) entre sí que con los otros conglomerados.

ggsave('Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Imagenes/kmeans_gen.pdf', width = 40, height = 20, units = 'cm')
```

<!--
NOTA: Con base en el número adecuado de clústeres anterior, se ajusta el modelo k-means con siete clústeres.
-->

```{r}
#| label: Modelo k-means con seis clústeres

set.seed(1234) # Se establece una semilla para garantizar que los resultados sean reproducibles.

# Se especifica el modelo de k-means ----

k_med_1 <- k_means(num_clusters = 7) |> # Se indica aquí que el número de clústeres adecuados es de 7.
  set_engine('stats', algorithm = 'Hartigan-Wong')

# Se ajusta el modelo de k-means ----

k_med_2 <- recipe(formula = ~ ., data = mD)

# Se combinan los dos pasos anteriores mediante un flujo de trabajo ----

k_med_3 <- workflow() |>
  add_model(k_med_1) |>
  add_recipe(k_med_2)

# Se ajusta el modelo de k-means ----

k_med_4 <- fit(k_med_3, data = mD)

k_med_resumen <- k_med_4 |>
  extract_fit_summary() # Con la función extract_fit_summary() se produce una lista de información resumida del modelo.

# Se observan algunas de las métricas para cuantificar la calidad de una partición o estructura de clúster particular ----

k_med_4 |> sse_within_total() # Aquí se calcula la suma del error al cuadrado (SSE) dentro del clúster.

k_med_4 |> sse_total() # Aquí se calcula la SSE total.

k_med_4 |> sse_ratio() # Aquí se calcula la relación entre el WSS y el SSE total.

# NOTA: Todas estas métricas dependen de la medición de la distancia entre puntos y/o centroides. Por defecto, se utiliza la distancia euclidiana ordinaria. Sin embargo, es posible seleccionar una función de distancia diferente. Se puede consultar el blog (https://tidyclust.tidymodels.org/articles/k_means.html) en caso de que se quiera profundizar más en esto.
```

<!--
NOTA: A partir del modelo de k-means con siete clúster, se observa y extrae a continuación en que grupo se clasificaron los distintos individuos. 
-->

```{r}
#| label: Grupos a partir del modelo de k-means

# Se crea un "tibble" donde se indique a que grupo (o clúster) pertenece cada uno de los individuos----

Grupos <- tibble(
  ID_id = colnames(mD),
  Grupos = k_med_resumen$cluster_assignments
  ) # El objetivo principal de ajustar un modelo de agrupamiento (k-means) suele ser asignar observaciones (en este caso individuos) a los conglomerados. Aquí se puede observar estas asignaciones cada uno de los 284 individuos.

Grupos |>
  count(Grupos) # Se observa el número de individuos en cada uno de los grupos o clústeres.

#######################
# Grupo de validación 1
#######################

Grupos |>
  filter(Grupos == 'Cluster_1') |>
  select(ID_id) |>
  write_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE)

#######################
# Grupo de validación 2
#######################

Grupos |>
  filter(Grupos == 'Cluster_2') |>
  select(ID_id) |>
  write_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE)

#######################
# Grupo de validación 3
#######################

Grupos |>
  filter(Grupos == 'Cluster_3') |>
  select(ID_id) |>
  write_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE)

#######################
# Grupo de validación 4
#######################

Grupos |>
  filter(Grupos == 'Cluster_4') |>
  select(ID_id) |>
  write_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE)

#######################
# Grupo de validación 5
#######################

Grupos |>
  filter(Grupos == 'Cluster_5') |>
  select(ID_id) |>
  write_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE)

#######################
# Grupo de validación 6
#######################

Grupos |>
  filter(Grupos == 'Cluster_6') |>
  select(ID_id) |>
  write_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE)

#######################
# Grupo de validación 7
#######################

Grupos |>
  filter(Grupos == 'Cluster_7') |>
  select(ID_id) |>
  write_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE)
```

<!--
NOTA: A continuaicón, se obtiene la matriz de parentesco basado en segmentos para cada grupo de validación.
-->

```{r}
#| label: Matriz de parentesco basado en segmentos en cada grupo de validación

# Se carga de nuevo la matriz de parentesco basado en segmentos  ---

load(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/fseg.RData')

# Se crea el objeto "id_fped" en el que se indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

id_fped <- read_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/datPed.txt', delim = ' ', col_names = FALSE) |>
  select(X1) |> # Se extrae la ID de los individuos genotipados.
  rename(ID_id = X1) |>
  mutate(Indice = row_number())

#######################
# Grupo de validación 1
#######################

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del primer grupo de validación ----

fseg_1 <- fseg[Grup_1$Indice, Grup_1$Indice]

# Se calcula el parentesco promedio dentro del grupo de validación 1 ----

t_fseg_1 <- fseg_1 |>
  as_tibble() |>
  mutate('Individuos 2' = colnames(fseg_1)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802524910'
    ) |>
  pivot_longer(
    cols = c(2:37),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    ) |>
  filter(`Individuos 2` != Individuos) # Se quita el auto-parentesco.

t_fseg_1 |> count(Individuos)

t_fseg_1 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

#######################
# Grupo de validación 2
#######################

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del segundo grupo de validación ----

fseg_2 <- fseg[Grup_2$Indice, Grup_2$Indice]

# Se calcula el parentesco promedio dentro del grupo de validación 2 ----

t_fseg_2 <- fseg_2 |>
  as_tibble() |>
  mutate('Individuos 2' = colnames(fseg_2)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802935597'
    ) |>
  pivot_longer(
    cols = c(2:99),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    ) |>
  filter(`Individuos 2` != Individuos) # Se quita el auto-parentesco.

t_fseg_2 |> count(Individuos)

t_fseg_2 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

#######################
# Grupo de validación 3
#######################

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del tercer grupo de validación ----

fseg_3 <- fseg[Grup_3$Indice, Grup_3$Indice]

# Se calcula el parentesco promedio dentro del grupo de validación 3 ----

t_fseg_3 <- fseg_3 |>
  as_tibble() |>
  mutate('Individuos 2' = colnames(fseg_3)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803645478'
    ) |>
  pivot_longer(
    cols = c(2:45),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    ) |>
  filter(`Individuos 2` != Individuos) # Se quita el auto-parentesco.

t_fseg_3 |> count(Individuos)

t_fseg_3 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

#######################
# Grupo de validación 4
#######################

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del cuarto grupo de validación ----

fseg_4 <- fseg[Grup_4$Indice, Grup_4$Indice]

# Se calcula el parentesco promedio dentro del grupo de validación 4 ----

t_fseg_4 <- fseg_4 |>
  as_tibble() |>
  mutate('Individuos 2' = colnames(fseg_4)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803657207'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    ) |>
  filter(`Individuos 2` != Individuos) # Se quita el auto-parentesco.

t_fseg_4 |> count(Individuos)

t_fseg_4 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

#######################
# Grupo de validación 5
#######################

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del quinto grupo de validación ----

fseg_5 <- fseg[Grup_5$Indice, Grup_5$Indice]

# Se calcula el parentesco promedio dentro del grupo de validación 5 ----

t_fseg_5 <- fseg_5 |>
  as_tibble() |>
  mutate('Individuos 2' = colnames(fseg_5)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000805439661'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    ) |>
  filter(`Individuos 2` != Individuos) # Se quita el auto-parentesco.

t_fseg_5 |> count(Individuos)

t_fseg_5 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

#######################
# Grupo de validación 6
#######################

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del sexto grupo de validación ----

fseg_6 <- fseg[Grup_6$Indice, Grup_6$Indice]

# Se calcula el parentesco promedio dentro del grupo de validación 6 ----

t_fseg_6 <- fseg_6 |>
  as_tibble() |>
  mutate('Individuos 2' = colnames(fseg_6)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000806582398'
    ) |>
  pivot_longer(
    cols = c(2:12),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    ) |>
  filter(`Individuos 2` != Individuos) # Se quita el auto-parentesco.

t_fseg_6 |> count(Individuos)

t_fseg_6 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

#######################
# Grupo de validación 7
#######################

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del sexto grupo de validación ----

fseg_7 <- fseg[Grup_7$Indice, Grup_7$Indice]

# Se calcula el parentesco promedio dentro del grupo de validación 7 ----

t_fseg_7 <- fseg_7 |>
  as_tibble() |>
  mutate('Individuos 2' = colnames(fseg_7)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES010805535734'
    ) |>
  pivot_longer(
    cols = c(2:6),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    ) |>
  filter(`Individuos 2` != Individuos) # Se quita el auto-parentesco.

t_fseg_7 |> count(Individuos)

t_fseg_7 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )
```

<!--
NOTA: A continuación, se obtiene el coeficiente de relación máximo (amax) dentro de cada grupo de validación. Esta medida se refiere al valor más alto del coeficiente de relación genético entre un individuo y todos los demás individuos. Este coeficiente se obtiene utilizando la matriz de parentesco basado en segmentos previamente calculada. El amax proporciona una medida de la relación genética máxima entre un individuo y los demás individuos dentro del mismo grupo. Esto es útil para evaluar la similitud genética dentro de cada grupo específico de individuos.
-->

```{r}
#| label: Coeficiente de relación máximo (amax) dentro del grupo

# Mediante una lista se guarda la matriz de parentesco basado en segmentos para cada grupo de validación, para posteriormente calcular en ellas el coeficiente de relación máximo (amax) dentro del grupo ----

fseg_grupos <- list(fseg_1, fseg_2, fseg_3, fseg_4, fseg_5, fseg_6, fseg_7)

# Se define una función para obtener el amax de un individuo en un grupo específico ----

amax <- function(matrices_fseg) { # Esta función itera sobre cada matriz de parentesco en la lista anterior, obtiene elamax para cada individuo en esa matriz y devuelve una lista con los resultados para cada grupo.

  # Se aplica la función map para iterar sobre cada matriz de parentesco en la lista de matrices de parentesco (fseg_grupos).
  lista_amax <- map(matrices_fseg, ~ {
    
    # Dentro de cada iteración, se obtiene el amax para cada individuo en la matriz de parentesco.
    diag(.x) <- 0 # Los valores de la diagonal, que corresponden al auto-parentesco, se colocan en 0. De esta forma, se excluye el auto-parentesco antes de calcular el máximo en cada fila
    amax_grupo <- apply(.x, 1, max) # Se obtiene el máximo valor en cada fila de la matriz.
    
    # Se devuelve el vector de amax para el grupo actual.
    amax_grupo
    })
  
  # Se devuelve una lista que contiene los vectores de amax para cada grupo de validación.
  return(lista_amax)
  }

# Se obtiene el amax para cada individuo en cada grupo de validación ----

amax_grupos <- amax(fseg_grupos)

# Se calcula el valor medio y la desviación estándar del amax para cada grupo ----

res <- map_dfr(amax_grupos, ~ tibble(Valor_Medio = mean(.x), Desviacion_Estandar = sd(.x), min = min(.x), max = max(.x))) |>
  mutate(Grupo = row_number()) # Se agrega una columna que indica el número de grupo de validación.

# Para cada grupo de validación se extrae el amax ----

fseg_g1 <- as_tibble(amax_grupos[[1]]) |>
  mutate(Grup_val = 'Grupo 1') # Primer grupo de validación.

fseg_g2 <- as_tibble(amax_grupos[[2]]) |>
  mutate(Grup_val = 'Grupo 2') # Segundo grupo de validación.

fseg_g3 <- as_tibble(amax_grupos[[3]]) |>
  mutate(Grup_val = 'Grupo 3') # Tercer grupo de validación.

fseg_g4 <- as_tibble(amax_grupos[[4]]) |>
  mutate(Grup_val = 'Grupo 4') # Cuarto grupo de validación.

fseg_g5 <- as_tibble(amax_grupos[[5]]) |>
  mutate(Grup_val = 'Grupo 5') # Quinto grupo de validación.

fseg_g6 <- as_tibble(amax_grupos[[6]]) |>
  mutate(Grup_val = 'Grupo 6') # Sexto grupo de validación.

fseg_g7 <- as_tibble(amax_grupos[[7]]) |>
  mutate(Grup_val = 'Grupo 7') # Séptimo grupo de validación.
```

<!--
NOTA: A continuaicón, se obtiene la matriz de parentesco basado en segmentos entre el primer grupo de validación con el resto de grupos (2, 3, 4, 5, 6 y 7). Luego con estos, se obtiene el coeficiente de relación máximo (amax) entre dichos grupos de validación.
-->

```{r}
#| label: Coeficiente de relación máximo (amax) entre el grupo 1 con el resto de grupos

# Se carga  de nuevo la matriz de parentesco basado en segmentos  ---

load(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/fseg.RData')

# Se crea el objeto "id_fped" en el que se indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

id_fped <- read_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/datPed.txt', delim = ' ', col_names = FALSE) |>
  select(X1) |> # Se extrae la ID de los individuos genotipados.
  rename(ID_id = X1) |>
  mutate(Indice = row_number())

############################
# Grupos de validación 1 y 2
############################

# Se importan los individuos del primer y segundo grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 1') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 2') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del primer y segundo grupo de validación ----

fseg_1_2 <- fseg[Grup_1$Indice, Grup_2$Indice] # Este es una matriz de dimensión 36x98 (36 individuos del primer grupo de validación y 98 idnivdiuos del segundo grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 1 y 2 ----

t_fseg_1_2 <- fseg_1_2 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_1_2)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802935597'
    ) |>
  pivot_longer(
    cols = c(2:99),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_1_2 |> count(Individuos)

t_fseg_1_2 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 1 y 3
############################

# Se importan los individuos del primer y tercer grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 1') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 3') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del primer y tercer grupo de validación ----

fseg_1_3 <- fseg[Grup_1$Indice, Grup_3$Indice] # Este es una matriz de dimensión 36x44 (36 individuos del primer grupo de validación y 44 idnivdiuos del tercer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 1 y 3 ----

t_fseg_1_3 <- fseg_1_3 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_1_3)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803645478'
    ) |>
  pivot_longer(
    cols = c(2:45),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_1_3 |> count(Individuos)

t_fseg_1_3 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 1 y 4
############################

# Se importan los individuos del primer y cuarto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 1') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 4') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del primer y cuarto grupo de validación ----

fseg_1_4 <- fseg[Grup_1$Indice, Grup_4$Indice] # Este es una matriz de dimensión 36x45 (36 individuos del primer grupo de validación y 45 idnivdiuos del cuarto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 1 y 4 ----

t_fseg_1_4 <- fseg_1_4 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_1_4)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803657207'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_1_4 |> count(Individuos)

t_fseg_1_4 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 1 y 5
############################

# Se importan los individuos del primer y quinto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 1') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del primer y quinto grupo de validación ----

fseg_1_5 <- fseg[Grup_1$Indice, Grup_5$Indice] # Este es una matriz de dimensión 36x45 (36 individuos del primer grupo de validación y 45 idnivdiuos del quinto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 1 y 5 ----

t_fseg_1_5 <- fseg_1_5 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_1_5)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000805439661'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_1_5 |> count(Individuos)

t_fseg_1_5 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 1 y 6
############################

# Se importan los individuos del primer y sexto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 1') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 6') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del primer y cuarto grupo de validación ----

fseg_1_6 <- fseg[Grup_1$Indice, Grup_6$Indice] # Este es una matriz de dimensión 36x11 (36 individuos del primer grupo de validación y 11 idnivdiuos del sexto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 1 y 6 ----

t_fseg_1_6 <- fseg_1_6 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_1_6)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000806582398'
    ) |>
  pivot_longer(
    cols = c(2:12),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_1_6 |> count(Individuos)

t_fseg_1_6 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 1 y 7
############################

# Se importan los individuos del primer y séptimo grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 1') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 7') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del primer y cuarto grupo de validación ----

fseg_1_7 <- fseg[Grup_1$Indice, Grup_7$Indice] # Este es una matriz de dimensión 36x11 (36 individuos del primer grupo de validación y 5 idnivdiuos del séptimo grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 1 y 7 ----

t_fseg_1_7 <- fseg_1_7 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_1_7)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES010805535734'
    ) |>
  pivot_longer(
    cols = c(2:6),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_1_7 |> count(Individuos)

t_fseg_1_7 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

# Se crea una lista con la matriz de parentesco basado en segemntos del primer grupo de validación con el resto de grupos de validación ----

fseg_grupos <- list(fseg_1_2, fseg_1_3, fseg_1_4, fseg_1_5, fseg_1_6, fseg_1_7)

# Se define una función para obtener el amax de un individuo en un grupo específico ----

amax <- function(matrices_fseg) { # Esta función itera sobre cada matriz de parentesco genómico en la lista anterior, obtiene elamax para cada individuo en esa matriz y devuelve una lista con los resultados para cada grupo.

  # Se aplica la función map para iterar sobre cada matriz de parentesco en la lista de matrices de parentesco (fseg_grupos).
  lista_amax <- map(matrices_fseg, ~ {
    
    # Dentro de cada iteración, se obtiene el amax para cada individuo en la matriz de parentesco.
    amax_grupo <- apply(.x, 1, max)
    
    # Se devuelve el vector de amax para el grupo actual.
    amax_grupo
    })
  
  # Se devuelve una lista que contiene los vectores de amax para cada grupo de validación.
  return(lista_amax)
  }

# Se obtiene el amax para cada individuo en cada combinación de grupos de validación ----

amax_grupos <- amax(fseg_grupos)

# Se calcula el valor medio y la desviación estándar del amax para cada grupo ----

res_Grup_1 <- map_dfr(amax_grupos, ~ tibble(Valor_Medio = mean(.x), Desviacion_Estandar = sd(.x), min = min(.x), max = max(.x))) |>
  mutate(
    Grupo = c('Grup_1_2', 'Grup_1_3', 'Grup_1_4', 'Grup_1_5', 'Grup_1_6', 'Grup_1_7')
    ) # Se agrega una columna que indica la combinación del primer grupo de validación con el resto.

# Para cada combinación de grupo de validación 1 con el resto de grupos de validación se extrae el amax ----

fseg_g1_g2 <- as_tibble(amax_grupos[[1]]) |>
  mutate(Grup_val = 'Grupo 1_2') # Primer y segundo grupo de validación.

fseg_g1_g3 <- as_tibble(amax_grupos[[2]]) |>
  mutate(Grup_val = 'Grupo 1_3') # Primer y tercer grupo de validación.

fseg_g1_g4 <- as_tibble(amax_grupos[[3]]) |>
  mutate(Grup_val = 'Grupo 1_4') # Primer y cuarto grupo de validación.

fseg_g1_g5 <- as_tibble(amax_grupos[[4]]) |>
  mutate(Grup_val = 'Grupo 1_5') # Primer y quinto grupo de validación.

fseg_g1_g6 <- as_tibble(amax_grupos[[5]]) |>
  mutate(Grup_val = 'Grupo 1_6') # Primer y sexto grupo de validación.

fseg_g1_g7 <- as_tibble(amax_grupos[[6]]) |>
  mutate(Grup_val = 'Grupo 1_7') # Primer y séptimo grupo de validación.

fseg_Grup1 <- bind_rows(fseg_g1, fseg_g1_g2, fseg_g1_g3, fseg_g1_g4, fseg_g1_g5, fseg_g1_g6, fseg_g1_g7)

# Se realiza un gráfico donde se observe la distribución de densidad de las relaciones genéticas basada en segmentos máximas (amax) entre cada individuo en un grupo particular y todos los individuos en el mismo o en diferentes grupos formados por agrupamiento de kmeans ----

fseg_Grup1 |>
  ggplot(aes(x = value, colour = Grup_val, fill = Grup_val)) +
  geom_density(alpha = 0.2) +
  facet_wrap(~ Grup_val, ncol = 3) +
  scale_color_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  scale_fill_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  labs(x = 'Coeficiente de relación máximo', y = 'Densidad') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold'),
    strip.background = element_rect(colour = 'black', fill = 'white'),
    strip.text = element_text(size = 12, colour = 'black', face = 'bold'),
    legend.position = 'none'
    )

ggsave('Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Imagenes/fseg_Grup1.pdf', width = 40, height = 20, units = 'cm')
```

<!--
NOTA: A continuaicón, se obtiene la matriz de parentesco basado en segmentos entre el segundo grupo de validación con el resto de grupos (1, 3, 4, 5, 6 y 7). Luego con estos, se obtiene el coeficiente de relación máximo (amax) entre dichos grupos de validación.
-->

```{r}
#| label: Coeficiente de relación máximo (amax) entre el grupo 2 con el resto de grupos

# Se carga  de nuevo la matriz de parentesco basado en segmentos  ---

load(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/fseg.RData')

# Se crea el objeto "id_fped" en el que se indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

id_fped <- read_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/datPed.txt', delim = ' ', col_names = FALSE) |>
  select(X1) |> # Se extrae la ID de los individuos genotipados.
  rename(ID_id = X1) |>
  mutate(Indice = row_number())

############################
# Grupos de validación 2 y 1
############################

# Se importan los individuos del segundo y primer grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 2') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 1') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del segundo y primer grupo de validación ----

fseg_2_1 <- fseg[Grup_2$Indice, Grup_1$Indice] # Este es una matriz de dimensión 98x36 (98 individuos del segundo grupo de validación y 36 idnivdiuos del primer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 2 y 1 ----

t_fseg_2_1 <- fseg_2_1 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_2_1)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802524910'
    ) |>
  pivot_longer(
    cols = c(2:37),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_2_1 |> count(Individuos)

t_fseg_2_1 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 2 y 3
############################

# Se importan los individuos del segundo y tercer grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 2') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 3') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del segundo y tercer grupo de validación ----

fseg_2_3 <- fseg[Grup_2$Indice, Grup_3$Indice] # Este es una matriz de dimensión 98x44 (98 individuos del segundo grupo de validación y 44 idnivdiuos del tercer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 2 y 3 ----

t_fseg_2_3 <- fseg_2_3 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_2_3)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803645478'
    ) |>
  pivot_longer(
    cols = c(2:45),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_2_3 |> count(Individuos)

t_fseg_2_3 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 2 y 4
############################

# Se importan los individuos del segundo y cuarto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 2') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 4') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del segundo y cuarto grupo de validación ----

fseg_2_4 <- fseg[Grup_2$Indice, Grup_4$Indice] # Este es una matriz de dimensión 98x45 (98 individuos del segundo grupo de validación y 45 idnivdiuos del cuarto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 2 y 4 ----

t_fseg_2_4 <- fseg_2_4 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_2_4)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803657207'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_2_4 |> count(Individuos)

t_fseg_2_4 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 2 y 5
############################

# Se importan los individuos del segundo y quinto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 2') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del segundo y quinto grupo de validación ----

fseg_2_5 <- fseg[Grup_2$Indice, Grup_5$Indice] # Este es una matriz de dimensión 98x45 (98 individuos del segundo grupo de validación y 45 idnivdiuos del quinto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 2 y 5 ----

t_fseg_2_5 <- fseg_2_5 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_2_5)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000805439661'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_2_5 |> count(Individuos)

t_fseg_2_5 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 2 y 6
############################

# Se importan los individuos del segundo y sexto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 2') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 6') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del segundo y sexto grupo de validación ----

fseg_2_6 <- fseg[Grup_2$Indice, Grup_6$Indice] # Este es una matriz de dimensión 98x11 (98 individuos del segundo grupo de validación y 11 idnivdiuos del sexto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 2 y 6 ----

t_fseg_2_6 <- fseg_2_6 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_2_6)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000806582398'
    ) |>
  pivot_longer(
    cols = c(2:12),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_2_6 |> count(Individuos)

t_fseg_2_6 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 2 y 7
############################

# Se importan los individuos del segundo y séptimo grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 2') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 7') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del segundo y séptimo grupo de validación ----

fseg_2_7 <- fseg[Grup_2$Indice, Grup_7$Indice] # Este es una matriz de dimensión 98x5 (98 individuos del segundo grupo de validación y 5 idnivdiuos del séptimo grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 2 y 7 ----

t_fseg_2_7 <- fseg_2_7 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_2_7)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES010805535734'
    ) |>
  pivot_longer(
    cols = c(2:6),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_2_7 |> count(Individuos)

t_fseg_2_7 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

# Se crea una lista con la matriz de parentesco basado en segemntos del segundo grupo de validación con el resto de grupos de validación ----

fseg_grupos <- list(fseg_2_1, fseg_2_3, fseg_2_4, fseg_2_5, fseg_2_6, fseg_2_7)

# Se define una función para obtener el amax de un individuo en un grupo específico ----

amax <- function(matrices_fseg) { # Esta función itera sobre cada matriz de parentesco genómico en la lista anterior, obtiene elamax para cada individuo en esa matriz y devuelve una lista con los resultados para cada grupo.

  # Se aplica la función map para iterar sobre cada matriz de parentesco en la lista de matrices de parentesco (fseg_grupos).
  lista_amax <- map(matrices_fseg, ~ {
    
    # Dentro de cada iteración, se obtiene el amax para cada individuo en la matriz de parentesco.
    amax_grupo <- apply(.x, 1, max)
    
    # Se devuelve el vector de amax para el grupo actual.
    amax_grupo
    })
  
  # Se devuelve una lista que contiene los vectores de amax para cada grupo de validación.
  return(lista_amax)
  }

# Se obtiene el amax para cada individuo en cada combinación de grupos de validación ----

amax_grupos <- amax(fseg_grupos)

# Se calcula el valor medio y la desviación estándar del amax para cada grupo ----

res_Grup_2 <- map_dfr(amax_grupos, ~ tibble(Valor_Medio = mean(.x), Desviacion_Estandar = sd(.x), min = min(.x), max = max(.x))) |>
  mutate(
    Grupo = c('Grup_2_1', 'Grup_2_3', 'Grup_2_4', 'Grup_2_5', 'Grup_2_6', 'Grup_2_7')
    ) # Se agrega una columna que indica la combinación del primer grupo de validación con el resto.

# Para cada combinación de grupo de validación 1 con el resto de grupos de validación se extrae el amax ----

fseg_g2_g1 <- as_tibble(amax_grupos[[1]]) |>
  mutate(Grup_val = 'Grupo 2_1') # Segundo y primer grupo de validación.

fseg_g2_g3 <- as_tibble(amax_grupos[[2]]) |>
  mutate(Grup_val = 'Grupo 2_3') # Segundo y tercer grupo de validación.

fseg_g2_g4 <- as_tibble(amax_grupos[[3]]) |>
  mutate(Grup_val = 'Grupo 2_4') # Segundo y cuarto grupo de validación.

fseg_g2_g5 <- as_tibble(amax_grupos[[4]]) |>
  mutate(Grup_val = 'Grupo 2_5') # Segundo y quinto grupo de validación.

fseg_g2_g6 <- as_tibble(amax_grupos[[5]]) |>
  mutate(Grup_val = 'Grupo 2_6') # Segundo y sexto grupo de validación.

fseg_g2_g7 <- as_tibble(amax_grupos[[6]]) |>
  mutate(Grup_val = 'Grupo 2_7') # Segundo y séptimo grupo de validación.

fseg_Grup2 <- bind_rows(fseg_g2, fseg_g2_g1, fseg_g2_g3, fseg_g2_g4, fseg_g2_g5, fseg_g2_g6, fseg_g2_g7)

# Se realiza un gráfico donde se observe la distribución de densidad de las relaciones genéticas basada en segmentos máximas (amax) entre cada individuo en un grupo particular y todos los individuos en el mismo o en diferentes grupos formados por agrupamiento de kmeans ----

fseg_Grup2 |>
  ggplot(aes(x = value, colour = Grup_val, fill = Grup_val)) +
  geom_density(alpha = 0.2) +
  facet_wrap(~ Grup_val, ncol = 3) +
  scale_color_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  scale_fill_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  labs(x = 'Coeficiente de relación máximo', y = 'Densidad') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold'),
    strip.background = element_rect(colour = 'black', fill = 'white'),
    strip.text = element_text(size = 12, colour = 'black', face = 'bold'),
    legend.position = 'none'
    )

ggsave('Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Imagenes/fseg_Grup2.pdf', width = 40, height = 20, units = 'cm')
```

<!--
NOTA: A continuaicón, se obtiene la matriz de parentesco basado en segmentos entre el tercer grupo de validación con el resto de grupos (1, 2, 4, 5, 6 y 7). Luego con estos, se obtiene el coeficiente de relación máximo (amax) entre dichos grupos de validación.
-->

```{r}
#| label: Coeficiente de relación máximo (amax) entre el grupo 3 con el resto de grupos

# Se carga  de nuevo la matriz de parentesco basado en segmentos  ---

load(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/fseg.RData')

# Se crea el objeto "id_fped" en el que se indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

id_fped <- read_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/datPed.txt', delim = ' ', col_names = FALSE) |>
  select(X1) |> # Se extrae la ID de los individuos genotipados.
  rename(ID_id = X1) |>
  mutate(Indice = row_number())

############################
# Grupos de validación 3 y 1
############################

# Se importan los individuos del tercer y primer grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 3') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 1') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del tercer y primer grupo de validación ----

fseg_3_1 <- fseg[Grup_3$Indice, Grup_1$Indice] # Este es una matriz de dimensión 44x36 (44 individuos del segundo grupo de validación y 36 idnivdiuos del primer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 3 y 1 ----

t_fseg_3_1 <- fseg_3_1 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_3_1)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802524910'
    ) |>
  pivot_longer(
    cols = c(2:37),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_3_1 |> count(Individuos)

t_fseg_3_1 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 3 y 2
############################

# Se importan los individuos del tercer y segundo grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 3') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 2') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del tercer y segundo grupo de validación ----

fseg_3_2 <- fseg[Grup_3$Indice, Grup_2$Indice] # Este es una matriz de dimensión 44x98 (44 individuos del tercer grupo de validación y 98 idnivdiuos del tercer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 3 y 2 ----

t_fseg_3_2 <- fseg_3_2 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_3_2)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802935597'
    ) |>
  pivot_longer(
    cols = c(2:99),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_3_2 |> count(Individuos)

t_fseg_3_2 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 3 y 4
############################

# Se importan los individuos del tercer y cuarto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 3') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 4') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del tercer y cuarto grupo de validación ----

fseg_3_4 <- fseg[Grup_3$Indice, Grup_4$Indice] # Este es una matriz de dimensión 44x45 (44 individuos del tercer grupo de validación y 45 idnivdiuos del cuarto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 3 y 4 ----

t_fseg_3_4 <- fseg_3_4 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_3_4)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803657207'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_3_4 |> count(Individuos)

t_fseg_3_4 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 3 y 5
############################

# Se importan los individuos del segundo y quinto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 3') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del tercer y quinto grupo de validación ----

fseg_3_5 <- fseg[Grup_3$Indice, Grup_5$Indice] # Este es una matriz de dimensión 44x45 (44 individuos del tercer grupo de validación y 45 idnivdiuos del quinto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 3 y 5 ----

t_fseg_3_5 <- fseg_3_5 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_3_5)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000805439661'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_3_5 |> count(Individuos)

t_fseg_3_5 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 3 y 6
############################

# Se importan los individuos del tercer y sexto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 3') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 6') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del tercer y sexto grupo de validación ----

fseg_3_6 <- fseg[Grup_3$Indice, Grup_6$Indice] # Este es una matriz de dimensión 44x11 (44 individuos del tercer grupo de validación y 11 idnivdiuos del sexto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 3 y 6 ----

t_fseg_3_6 <- fseg_3_6 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_3_6)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000806582398'
    ) |>
  pivot_longer(
    cols = c(2:12),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_3_6 |> count(Individuos)

t_fseg_3_6 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 3 y 6
############################

# Se importan los individuos del tercer y sexto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 3') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 7') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del tercer y sexto grupo de validación ----

fseg_3_7 <- fseg[Grup_3$Indice, Grup_7$Indice] # Este es una matriz de dimensión 44x5 (44 individuos del tercer grupo de validación y 5 idnivdiuos del séxtimo grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 3 y 7 ----

t_fseg_3_7 <- fseg_3_7 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_3_7)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES010805535734'
    ) |>
  pivot_longer(
    cols = c(2:6),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_3_7 |> count(Individuos)

t_fseg_3_7 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

# Se crea una lista con la matriz de parentesco basado en segemntos del primer grupo de validación con el resto de grupos de validación ----

fseg_grupos <- list(fseg_3_1, fseg_3_2, fseg_3_4, fseg_3_5, fseg_3_6, fseg_3_7)

# Se define una función para obtener el amax de un individuo en un grupo específico ----

amax <- function(matrices_fseg) { # Esta función itera sobre cada matriz de parentesco genómico en la lista anterior, obtiene elamax para cada individuo en esa matriz y devuelve una lista con los resultados para cada grupo.

  # Se aplica la función map para iterar sobre cada matriz de parentesco en la lista de matrices de parentesco (fseg_grupos).
  lista_amax <- map(matrices_fseg, ~ {
    
    # Dentro de cada iteración, se obtiene el amax para cada individuo en la matriz de parentesco.
    amax_grupo <- apply(.x, 1, max)
    
    # Se devuelve el vector de amax para el grupo actual.
    amax_grupo
    })
  
  # Se devuelve una lista que contiene los vectores de amax para cada grupo de validación.
  return(lista_amax)
  }

# Se obtiene el amax para cada individuo en cada combinación de grupos de validación ----

amax_grupos <- amax(fseg_grupos)

# Se calcula el valor medio y la desviación estándar del amax para cada grupo ----

res_Grup_3 <- map_dfr(amax_grupos, ~ tibble(Valor_Medio = mean(.x), Desviacion_Estandar = sd(.x), min = min(.x), max = max(.x))) |>
  mutate(
    Grupo = c('Grup_3_1', 'Grup_3_2', 'Grup_3_4', 'Grup_3_5', 'Grup_3_6', 'Grup_3_7')
    ) # Se agrega una columna que indica la combinación del tercer grupo de validación con el resto.

# Para cada combinación de grupo de validación 3 con el resto de grupos de validación se extrae el amax ----

fseg_g3_g1 <- as_tibble(amax_grupos[[1]]) |>
  mutate(Grup_val = 'Grupo 3_1') # Tercer y primer grupo de validación.

fseg_g3_g2 <- as_tibble(amax_grupos[[2]]) |>
  mutate(Grup_val = 'Grupo 3_2') # Tercer y segundo grupo de validación.

fseg_g3_g4 <- as_tibble(amax_grupos[[3]]) |>
  mutate(Grup_val = 'Grupo 3_4') # Tercer y cuarto grupo de validación.

fseg_g3_g5 <- as_tibble(amax_grupos[[4]]) |>
  mutate(Grup_val = 'Grupo 3_5') # Tercer y quinto grupo de validación.

fseg_g3_g6 <- as_tibble(amax_grupos[[5]]) |>
  mutate(Grup_val = 'Grupo 3_6') # Tercer y sexto grupo de validación.

fseg_g3_g7 <- as_tibble(amax_grupos[[6]]) |>
  mutate(Grup_val = 'Grupo 3_7') # Tercer y séptimo grupo de validación.

fseg_Grup3 <- bind_rows(fseg_g3, fseg_g3_g1, fseg_g3_g2, fseg_g3_g4, fseg_g3_g5, fseg_g3_g6, fseg_g3_g7)

# Se realiza un gráfico donde se observe la distribución de densidad de las relaciones genéticas basada en segmentos máximas (amax) entre cada individuo en un grupo particular y todos los individuos en el mismo o en diferentes grupos formados por agrupamiento de kmeans ----

fseg_Grup3 |>
  ggplot(aes(x = value, colour = Grup_val, fill = Grup_val)) +
  geom_density(alpha = 0.2) +
  facet_wrap(~ Grup_val, ncol = 3) +
  scale_color_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  scale_fill_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  labs(x = 'Coeficiente de relación máximo', y = 'Densidad') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold'),
    strip.background = element_rect(colour = 'black', fill = 'white'),
    strip.text = element_text(size = 12, colour = 'black', face = 'bold'),
    legend.position = 'none'
    )

ggsave('Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Imagenes/fseg_Grup3.pdf', width = 40, height = 20, units = 'cm')
```

<!--
NOTA: A continuaicón, se obtiene la matriz de parentesco basado en segmentos entre el cuarto grupo de validación con el resto de grupos (1, 2, 3, 5, 6 y 7). Luego con estos, se obtiene el coeficiente de relación máximo (amax) entre dichos grupos de validación.
-->

```{r}
#| label: Coeficiente de relación máximo (amax) entre el grupo 4 con el resto de grupos

# Se carga  de nuevo la matriz de parentesco basado en segmentos  ---

load(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/fseg.RData')

# Se crea el objeto "id_fped" en el que se indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

id_fped <- read_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/datPed.txt', delim = ' ', col_names = FALSE) |>
  select(X1) |> # Se extrae la ID de los individuos genotipados.
  rename(ID_id = X1) |>
  mutate(Indice = row_number())

############################
# Grupos de validación 4 y 1
############################

# Se importan los individuos del cuarto y primer grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 4') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 1') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del cuarto y primer grupo de validación ----

fseg_4_1 <- fseg[Grup_4$Indice, Grup_1$Indice] # Este es una matriz de dimensión 45x36 (45 individuos del cuarto grupo de validación y 36 idnivdiuos del primer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 4 y 1 ----

t_fseg_4_1 <- fseg_4_1 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_4_1)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802524910'
    ) |>
  pivot_longer(
    cols = c(2:37),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_4_1 |> count(Individuos)

t_fseg_4_1 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 4 y 2
############################

# Se importan los individuos del cuarto y segundo grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 4') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 2') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del tercer y segundo grupo de validación ----

fseg_4_2 <- fseg[Grup_4$Indice, Grup_2$Indice] # Este es una matriz de dimensión 45x98 (45 individuos del cuarto grupo de validación y 98 idnivdiuos del segundo grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 4 y 2 ----

t_fseg_4_2 <- fseg_4_2 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_4_2)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802935597'
    ) |>
  pivot_longer(
    cols = c(2:99),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_4_2 |> count(Individuos)

t_fseg_4_2 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 4 y 3
############################

# Se importan los individuos del cuarto y tercer grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 4') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 3') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del tercer y cuarto grupo de validación ----

fseg_4_3 <- fseg[Grup_4$Indice, Grup_3$Indice] # Este es una matriz de dimensión 45x44 (45 individuos del cuarto grupo de validación y 44 idnivdiuos del tercer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 4 y 3 ----

t_fseg_4_3 <- fseg_4_3 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_4_3)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803645478'
    ) |>
  pivot_longer(
    cols = c(2:45),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_4_3 |> count(Individuos)

t_fseg_4_3 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 4 y 5
############################

# Se importan los individuos del cuarto y quinto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 4') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del tercer y quinto grupo de validación ----

fseg_4_5 <- fseg[Grup_4$Indice, Grup_5$Indice] # Este es una matriz de dimensión 45x45 (45 individuos del cuarto grupo de validación y 45 idnivdiuos del quinto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 4 y 5 ----

t_fseg_4_5 <- fseg_4_5 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_4_5)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000805439661'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_4_5 |> count(Individuos)

t_fseg_4_5 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 4 y 6
############################

# Se importan los individuos del cuarto y sexto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 4') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 6') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del cuarto y sexto grupo de validación ----

fseg_4_6 <- fseg[Grup_4$Indice, Grup_6$Indice] # Este es una matriz de dimensión 45x11 (45 individuos del cuarto grupo de validación y 11 idnivdiuos del sexto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 4 y 6 ----

t_fseg_4_6 <- fseg_4_6 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_4_6)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000806582398'
    ) |>
  pivot_longer(
    cols = c(2:12),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_4_6 |> count(Individuos)

t_fseg_4_6 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 4 y 7
############################

# Se importan los individuos del cuarto y séptimo grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 4') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 7') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del cuarto y séptimo grupo de validación ----

fseg_4_7 <- fseg[Grup_4$Indice, Grup_7$Indice] # Este es una matriz de dimensión 45x5 (45 individuos del cuarto grupo de validación y 5 idnivdiuos del sexto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 4 y 7 ----

t_fseg_4_7 <- fseg_4_7 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_4_7)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES010805535734'
    ) |>
  pivot_longer(
    cols = c(2:6),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_4_7 |> count(Individuos)

t_fseg_4_7 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

# Se crea una lista con la matriz de parentesco basado en segemntos del cuarto grupo de validación con el resto de grupos de validación ----

fseg_grupos <- list(fseg_4_1, fseg_4_2, fseg_4_3, fseg_4_5, fseg_4_6, fseg_4_7)

# Se define una función para obtener el amax de un individuo en un grupo específico ----

amax <- function(matrices_fseg) { # Esta función itera sobre cada matriz de parentesco genómico en la lista anterior, obtiene elamax para cada individuo en esa matriz y devuelve una lista con los resultados para cada grupo.

  # Se aplica la función map para iterar sobre cada matriz de parentesco en la lista de matrices de parentesco (fseg_grupos).
  lista_amax <- map(matrices_fseg, ~ {
    
    # Dentro de cada iteración, se obtiene el amax para cada individuo en la matriz de parentesco.
    amax_grupo <- apply(.x, 1, max)
    
    # Se devuelve el vector de amax para el grupo actual.
    amax_grupo
    })
  
  # Se devuelve una lista que contiene los vectores de amax para cada grupo de validación.
  return(lista_amax)
  }

# Se obtiene el amax para cada individuo en cada combinación de grupos de validación ----

amax_grupos <- amax(fseg_grupos)

# Se calcula el valor medio y la desviación estándar del amax para cada grupo ----

res_Grup_4 <- map_dfr(amax_grupos, ~ tibble(Valor_Medio = mean(.x), Desviacion_Estandar = sd(.x), min = min(.x), max = max(.x))) |>
  mutate(
    Grupo = c('Grup_4_1', 'Grup_4_2', 'Grup_4_3', 'Grup_4_5', 'Grup_4_6', 'Grup_4_7')
    ) # Se agrega una columna que indica la combinación del cuarto grupo de validación con el resto.

# Para cada combinación de grupo de validación 4 con el resto de grupos de validación se extrae el amax ----

fseg_g4_g1 <- as_tibble(amax_grupos[[1]]) |>
  mutate(Grup_val = 'Grupo 4_1') # Cuarto y primer grupo de validación.

fseg_g4_g2 <- as_tibble(amax_grupos[[2]]) |>
  mutate(Grup_val = 'Grupo 4_2') # Cuarto y segundo grupo de validación.

fseg_g4_g3 <- as_tibble(amax_grupos[[3]]) |>
  mutate(Grup_val = 'Grupo 4_3') # Cuarto y tercer grupo de validación.

fseg_g4_g5 <- as_tibble(amax_grupos[[4]]) |>
  mutate(Grup_val = 'Grupo 4_5') # Cuarto y quinto grupo de validación.

fseg_g4_g6 <- as_tibble(amax_grupos[[5]]) |>
  mutate(Grup_val = 'Grupo 4_6') # Cuarto y sexto grupo de validación.

fseg_g4_g7 <- as_tibble(amax_grupos[[5]]) |>
  mutate(Grup_val = 'Grupo 4_7') # Cuarto y séptimo grupo de validación.

fseg_Grup4 <- bind_rows(fseg_g4, fseg_g4_g1, fseg_g4_g2, fseg_g4_g3, fseg_g4_g5, fseg_g4_g6, fseg_g4_g7)

# Se realiza un gráfico donde se observe la distribución de densidad de las relaciones genéticas basada en segmentos máximas (amax) entre cada individuo en un grupo particular y todos los individuos en el mismo o en diferentes grupos formados por agrupamiento de kmeans ----

fseg_Grup4 |>
  ggplot(aes(x = value, colour = Grup_val, fill = Grup_val)) +
  geom_density(alpha = 0.2) +
  facet_wrap(~ Grup_val, ncol = 3) +
  scale_color_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  scale_fill_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  labs(x = 'Coeficiente de relación máximo', y = 'Densidad') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold'),
    strip.background = element_rect(colour = 'black', fill = 'white'),
    strip.text = element_text(size = 12, colour = 'black', face = 'bold'),
    legend.position = 'none'
    )

ggsave('Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Imagenes/fseg_Grup4.pdf', width = 40, height = 20, units = 'cm')
```

<!--
NOTA: A continuaicón, se obtiene la matriz de parentesco basado en segmentos entre el quinto grupo de validación con el resto de grupos (1, 2, 3, 4, 6 y 7). Luego con estos, se obtiene el coeficiente de relación máximo (amax) entre dichos grupos de validación.
-->

```{r}
#| label: Coeficiente de relación máximo (amax) entre el grupo 5 con el resto de grupos

# Se carga  de nuevo la matriz de parentesco basado en segmentos  ---

load(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/fseg.RData')

# Se crea el objeto "id_fped" en el que se indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

id_fped <- read_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/datPed.txt', delim = ' ', col_names = FALSE) |>
  select(X1) |> # Se extrae la ID de los individuos genotipados.
  rename(ID_id = X1) |>
  mutate(Indice = row_number())

############################
# Grupos de validación 5 y 1
############################

# Se importan los individuos del quinto y primer grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 1') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del quinto y primer grupo de validación ----

fseg_5_1 <- fseg[Grup_5$Indice, Grup_1$Indice] # Este es una matriz de dimensión 45x36 (45 individuos del quinto grupo de validación y 36 idnivdiuos del primer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 5 y 1 ----

t_fseg_5_1 <- fseg_5_1 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_5_1)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802524910'
    ) |>
  pivot_longer(
    cols = c(2:37),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_5_1 |> count(Individuos)

t_fseg_5_1 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 5 y 2
############################

# Se importan los individuos del quinto y segundo grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 2') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del quinto y segundo grupo de validación ----

fseg_5_2 <- fseg[Grup_5$Indice, Grup_2$Indice] # Este es una matriz de dimensión 45x98 (45 individuos del cuarto grupo de validación y 98 idnivdiuos del segundo grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 5 y 2 ----

t_fseg_5_2 <- fseg_5_2 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_5_2)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802935597'
    ) |>
  pivot_longer(
    cols = c(2:99),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_5_2 |> count(Individuos)

t_fseg_5_2 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 5 y 3
############################

# Se importan los individuos del quinto y tercer grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 3') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del tercer y quinto grupo de validación ----

fseg_5_3 <- fseg[Grup_5$Indice, Grup_3$Indice] # Este es una matriz de dimensión 45x44 (45 individuos del quinto grupo de validación y 44 idnivdiuos del tercer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 5 y 3 ----

t_fseg_5_3 <- fseg_5_3 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_5_3)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803645478'
    ) |>
  pivot_longer(
    cols = c(2:45),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_5_3 |> count(Individuos)

t_fseg_5_3 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 5 y 4
############################

# Se importan los individuos del quinto y cuarto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 4') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del quinto y cuarto grupo de validación ----

fseg_5_4 <- fseg[Grup_5$Indice, Grup_4$Indice] # Este es una matriz de dimensión 45x45 (45 individuos del quinto grupo de validación y 45 idnivdiuos del cuarto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 5 y 4 ----

t_fseg_5_4 <- fseg_5_4 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_5_4)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803657207'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_5_4 |> count(Individuos)

t_fseg_5_4 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 5 y 6
############################

# Se importan los individuos del quinto y sexto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 6') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del quinto y sexto grupo de validación ----

fseg_5_6 <- fseg[Grup_5$Indice, Grup_6$Indice] # Este es una matriz de dimensión 45x11 (45 individuos del quinto grupo de validación y 11 idnivdiuos del sexto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 5 y 6 ----

t_fseg_5_6 <- fseg_5_6 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_5_6)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000806582398'
    ) |>
  pivot_longer(
    cols = c(2:12),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_5_6 |> count(Individuos)

t_fseg_5_6 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 5 y 7
############################

# Se importan los individuos del quinto y séptimo grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 7') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del quinto y séptimo grupo de validación ----

fseg_5_7 <- fseg[Grup_5$Indice, Grup_7$Indice] # Este es una matriz de dimensión 45x5 (45 individuos del quinto grupo de validación y 5 idnivdiuos del séptimo grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 5 y 7 ----

t_fseg_5_7 <- fseg_5_7 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_5_7)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES010805535734'
    ) |>
  pivot_longer(
    cols = c(2:6),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_5_7 |> count(Individuos)

t_fseg_5_7 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

# Se crea una lista con la matriz de parentesco basado en segemntos del quinto grupo de validación con el resto de grupos de validación ----

fseg_grupos <- list(fseg_5_1, fseg_5_2, fseg_5_3, fseg_5_4, fseg_5_6, fseg_5_7)

# Se define una función para obtener el amax de un individuo en un grupo específico ----

amax <- function(matrices_fseg) { # Esta función itera sobre cada matriz de parentesco genómico en la lista anterior, obtiene elamax para cada individuo en esa matriz y devuelve una lista con los resultados para cada grupo.

  # Se aplica la función map para iterar sobre cada matriz de parentesco en la lista de matrices de parentesco (fseg_grupos).
  lista_amax <- map(matrices_fseg, ~ {
    
    # Dentro de cada iteración, se obtiene el amax para cada individuo en la matriz de parentesco.
    amax_grupo <- apply(.x, 1, max)
    
    # Se devuelve el vector de amax para el grupo actual.
    amax_grupo
    })
  
  # Se devuelve una lista que contiene los vectores de amax para cada grupo de validación.
  return(lista_amax)
  }

# Se obtiene el amax para cada individuo en cada combinación de grupos de validación ----

amax_grupos <- amax(fseg_grupos)

# Se calcula el valor medio y la desviación estándar del amax para cada grupo ----

res_Grup_5 <- map_dfr(amax_grupos, ~ tibble(Valor_Medio = mean(.x), Desviacion_Estandar = sd(.x), min = min(.x), max = max(.x))) |>
  mutate(
    Grupo = c('Grup_5_1', 'Grup_5_2', 'Grup_5_3', 'Grup_5_4', 'Grup_5_6', 'Grup_5_7')
    ) # Se agrega una columna que indica la combinación del cuarto grupo de validación con el resto.

# Para cada combinación de grupo de validación 1 con el resto de grupos de validación se extrae el amax ----

fseg_g5_g1 <- as_tibble(amax_grupos[[1]]) |>
  mutate(Grup_val = 'Grupo 5_1') # Quinto y primer grupo de validación.

fseg_g5_g2 <- as_tibble(amax_grupos[[2]]) |>
  mutate(Grup_val = 'Grupo 5_2') # Quinto y segundo grupo de validación.

fseg_g5_g3 <- as_tibble(amax_grupos[[3]]) |>
  mutate(Grup_val = 'Grupo 5_3') # Quinto y tercer grupo de validación.

fseg_g5_g4 <- as_tibble(amax_grupos[[4]]) |>
  mutate(Grup_val = 'Grupo 5_4') # Quinto y quinto grupo de validación.

fseg_g5_g6 <- as_tibble(amax_grupos[[5]]) |>
  mutate(Grup_val = 'Grupo 5_6') # Quinto y sexto grupo de validación.

fseg_g5_g7 <- as_tibble(amax_grupos[[6]]) |>
  mutate(Grup_val = 'Grupo 5_7') # Quinto y séptimo grupo de validación.

fseg_Grup5 <- bind_rows(fseg_g5, fseg_g5_g1, fseg_g5_g2, fseg_g5_g3, fseg_g5_g4, fseg_g5_g6, fseg_g5_g7)

# Se realiza un gráfico donde se observe la distribución de densidad de las relaciones genéticas basada en segmentos máximas (amax) entre cada individuo en un grupo particular y todos los individuos en el mismo o en diferentes grupos formados por agrupamiento de kmeans ----

fseg_Grup5 |>
  ggplot(aes(x = value, colour = Grup_val, fill = Grup_val)) +
  geom_density(alpha = 0.2) +
  facet_wrap(~ Grup_val, ncol = 3) +
  scale_color_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  scale_fill_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  labs(x = 'Coeficiente de relación máximo', y = 'Densidad') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold'),
    strip.background = element_rect(colour = 'black', fill = 'white'),
    strip.text = element_text(size = 12, colour = 'black', face = 'bold'),
    legend.position = 'none'
    )

ggsave('Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Imagenes/fseg_Grup5.pdf', width = 40, height = 20, units = 'cm')
```

<!--
NOTA: A continuaicón, se obtiene la matriz de parentesco basado en segmentos entre el sexto grupo de validación con el resto de grupos (1, 2, 3, 4, 5 y 7). Luego con estos, se obtiene el coeficiente de relación máximo (amax) entre dichos grupos de validación.
-->

```{r}
#| label: Coeficiente de relación máximo (amax) entre el grupo 6 con el resto de grupos

# Se carga  de nuevo la matriz de parentesco basado en segmentos  ---

load(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/fseg.RData')

# Se crea el objeto "id_fped" en el que se indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

id_fped <- read_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/datPed.txt', delim = ' ', col_names = FALSE) |>
  select(X1) |> # Se extrae la ID de los individuos genotipados.
  rename(ID_id = X1) |>
  mutate(Indice = row_number())

############################
# Grupos de validación 6 y 1
############################

# Se importan los individuos del sexto y primer grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 6') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 1') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del sexto y primer grupo de validación ----

fseg_6_1 <- fseg[Grup_6$Indice, Grup_1$Indice] # Este es una matriz de dimensión 11x36 (11 individuos del sexto grupo de validación y 36 idnivdiuos del primer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 6 y 1 ----

t_fseg_6_1 <- fseg_6_1 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_6_1)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802524910'
    ) |>
  pivot_longer(
    cols = c(2:37),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_6_1 |> count(Individuos)

t_fseg_6_1 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 6 y 2
############################

# Se importan los individuos del sexto y segundo grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 2') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del quinto y segundo grupo de validación ----

fseg_6_2 <- fseg[Grup_6$Indice, Grup_2$Indice] # Este es una matriz de dimensión 11x98 (11 individuos del sexto grupo de validación y 98 idnivdiuos del segundo grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 6 y 2 ----

t_fseg_6_2 <- fseg_6_2 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_6_2)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802935597'
    ) |>
  pivot_longer(
    cols = c(2:99),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_6_2 |> count(Individuos)

t_fseg_6_2 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 6 y 3
############################

# Se importan los individuos del sexto y tercer grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 6') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 3') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del sexto y tercer grupo de validación ----

fseg_6_3 <- fseg[Grup_6$Indice, Grup_3$Indice] # Este es una matriz de dimensión 11x44 (11 individuos del sexto grupo de validación y 44 idnivdiuos del tercer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 6 y 3 ----

t_fseg_6_3 <- fseg_6_3 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_6_3)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803645478'
    ) |>
  pivot_longer(
    cols = c(2:45),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_6_3 |> count(Individuos)

t_fseg_6_3 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 6 y 4
############################

# Se importan los individuos del sexto y cuarto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 6') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 4') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del sexto y cuarto grupo de validación ----

fseg_6_4 <- fseg[Grup_6$Indice, Grup_4$Indice] # Este es una matriz de dimensión 11x45 (11 individuos del sexto grupo de validación y 45 idnivdiuos del cuarto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 6 y 4 ----

t_fseg_6_4 <- fseg_6_4 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_6_4)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803657207'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_6_4 |> count(Individuos)

t_fseg_6_4 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 6 y 5
############################

# Se importan los individuos del sexto y quinto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 6') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del sexto y quinto grupo de validación ----

fseg_6_5 <- fseg[Grup_6$Indice, Grup_5$Indice] # Este es una matriz de dimensión 11x45 (11 individuos del sexto grupo de validación y 45 idnivdiuos del quinto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 6 y 5 ----

t_fseg_6_5 <- fseg_6_5 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_6_5)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000805439661'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_6_5 |> count(Individuos)

t_fseg_6_5 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 6 y 7
############################

# Se importan los individuos del sexto y séptimo grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 6') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 7') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del sexto y quinto grupo de validación ----

fseg_6_7 <- fseg[Grup_6$Indice, Grup_7$Indice] # Este es una matriz de dimensión 11x5 (11 individuos del sexto grupo de validación y 5 idnivdiuos del séptimo grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 6 y 7 ----

t_fseg_6_7 <- fseg_6_7 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_6_7)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES010805535734'
    ) |>
  pivot_longer(
    cols = c(2:6),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_6_7 |> count(Individuos)

t_fseg_6_7 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

# Se crea una lista con la matriz de parentesco basado en segemntos del cuarto grupo de validación con el resto de grupos de validación ----

fseg_grupos <- list(fseg_6_1, fseg_6_2, fseg_6_3, fseg_6_4, fseg_6_5, fseg_6_7)

# Se define una función para obtener el amax de un individuo en un grupo específico ----

amax <- function(matrices_fseg) { # Esta función itera sobre cada matriz de parentesco genómico en la lista anterior, obtiene elamax para cada individuo en esa matriz y devuelve una lista con los resultados para cada grupo.

  # Se aplica la función map para iterar sobre cada matriz de parentesco en la lista de matrices de parentesco (fseg_grupos).
  lista_amax <- map(matrices_fseg, ~ {
    
    # Dentro de cada iteración, se obtiene el amax para cada individuo en la matriz de parentesco.
    amax_grupo <- apply(.x, 1, max)
    
    # Se devuelve el vector de amax para el grupo actual.
    amax_grupo
    })
  
  # Se devuelve una lista que contiene los vectores de amax para cada grupo de validación.
  return(lista_amax)
  }

# Se obtiene el amax para cada individuo en cada combinación de grupos de validación ----

amax_grupos <- amax(fseg_grupos)

# Se calcula el valor medio y la desviación estándar del amax para cada grupo ----

res_Grup_6 <- map_dfr(amax_grupos, ~ tibble(Valor_Medio = mean(.x), Desviacion_Estandar = sd(.x), min = min(.x), max = max(.x))) |>
  mutate(
    Grupo = c('Grup_6_1', 'Grup_6_2', 'Grup_6_3', 'Grup_6_4', 'Grup_6_5', 'Grup_6_7')
    ) # Se agrega una columna que indica la combinación del sexto grupo de validación con el resto.

# Para cada combinación de grupo de validación 6 con el resto de grupos de validación se extrae el amax ----

fseg_g6_g1 <- as_tibble(amax_grupos[[1]]) |>
  mutate(Grup_val = 'Grupo 6_1') # Sexto y primer grupo de validación.

fseg_g6_g2 <- as_tibble(amax_grupos[[2]]) |>
  mutate(Grup_val = 'Grupo 6_2') # Sexto y segundo grupo de validación.

fseg_g6_g3 <- as_tibble(amax_grupos[[3]]) |>
  mutate(Grup_val = 'Grupo 6_3') # Sexto y tercer grupo de validación.

fseg_g6_g4 <- as_tibble(amax_grupos[[4]]) |>
  mutate(Grup_val = 'Grupo 6_4') # Sexto y quinto grupo de validación.

fseg_g6_g5 <- as_tibble(amax_grupos[[5]]) |>
  mutate(Grup_val = 'Grupo 6_5') # Sexto y sexto grupo de validación.

fseg_g6_g7 <- as_tibble(amax_grupos[[5]]) |>
  mutate(Grup_val = 'Grupo 6_7') # Sexto y séptimo grupo de validación.

fseg_Grup6 <- bind_rows(fseg_g6, fseg_g6_g1, fseg_g6_g2, fseg_g6_g3, fseg_g6_g4, fseg_g6_g5, fseg_g6_g7)

# Se realiza un gráfico donde se observe la distribución de densidad de las relaciones genéticas basada en segmentos máximas (amax) entre cada individuo en un grupo particular y todos los individuos en el mismo o en diferentes grupos formados por agrupamiento de kmeans ----

fseg_Grup6 |>
  ggplot(aes(x = value, colour = Grup_val, fill = Grup_val)) +
  geom_density(alpha = 0.2) +
  facet_wrap(~ Grup_val, ncol = 3) +
  scale_color_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  scale_fill_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  labs(x = 'Coeficiente de relación máximo', y = 'Densidad') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold'),
    strip.background = element_rect(colour = 'black', fill = 'white'),
    strip.text = element_text(size = 12, colour = 'black', face = 'bold'),
    legend.position = 'none'
    )

ggsave('Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Imagenes/fseg_Grup6.pdf', width = 40, height = 20, units = 'cm')
```

<!--
NOTA: A continuaicón, se obtiene la matriz de parentesco basado en segmentos entre el séptimo grupo de validación con el resto de grupos (1, 2, 3, 4, 5 y 6). Luego con estos, se obtiene el coeficiente de relación máximo (amax) entre dichos grupos de validación.
-->

```{r}
#| label: Coeficiente de relación máximo (amax) entre el grupo 7 con el resto de grupos

# Se carga  de nuevo la matriz de parentesco basado en segmentos  ---

load(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/fseg.RData')

# Se crea el objeto "id_fped" en el que se indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

id_fped <- read_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/datPed.txt', delim = ' ', col_names = FALSE) |>
  select(X1) |> # Se extrae la ID de los individuos genotipados.
  rename(ID_id = X1) |>
  mutate(Indice = row_number())

############################
# Grupos de validación 7 y 1
############################

# Se importan los individuos del sexto y primer grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 7') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 1') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del sexto y primer grupo de validación ----

fseg_7_1 <- fseg[Grup_7$Indice, Grup_1$Indice] # Este es una matriz de dimensión 5x36 (5 individuos del sexto grupo de validación y 36 idnivdiuos del primer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 7 y 1 ----

t_fseg_7_1 <- fseg_7_1 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_7_1)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802524910'
    ) |>
  pivot_longer(
    cols = c(2:37),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_7_1 |> count(Individuos)

t_fseg_7_1 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 7 y 2
############################

# Se importan los individuos del sexto y segundo grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 7') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 2') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del quinto y segundo grupo de validación ----

fseg_7_2 <- fseg[Grup_7$Indice, Grup_2$Indice] # Este es una matriz de dimensión 5x98 (5 individuos del sexto grupo de validación y 98 idnivdiuos del segundo grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 7 y 2 ----

t_fseg_7_2 <- fseg_7_2 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_7_2)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000802935597'
    ) |>
  pivot_longer(
    cols = c(2:99),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_7_2 |> count(Individuos)

t_fseg_7_2 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 7 y 3
############################

# Se importan los individuos del sexto y tercer grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 7') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 3') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del sexto y tercer grupo de validación ----

fseg_7_3 <- fseg[Grup_7$Indice, Grup_3$Indice] # Este es una matriz de dimensión 5x44 (5 individuos del sexto grupo de validación y 44 idnivdiuos del tercer grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 7 y 3 ----

t_fseg_7_3 <- fseg_7_3 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_7_3)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803645478'
    ) |>
  pivot_longer(
    cols = c(2:45),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_7_3 |> count(Individuos)

t_fseg_7_3 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 7 y 4
############################

# Se importan los individuos del sexto y cuarto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 7') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 4') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del sexto y cuarto grupo de validación ----

fseg_7_4 <- fseg[Grup_7$Indice, Grup_4$Indice] # Este es una matriz de dimensión 5x45 (5 individuos del sexto grupo de validación y 45 idnivdiuos del cuarto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 7 y 4 ----

t_fseg_7_4 <- fseg_7_4 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_7_4)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000803657207'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_7_4 |> count(Individuos)

t_fseg_7_4 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 7 y 5
############################

# Se importan los individuos del sexto y quinto grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 7') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 5') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del sexto y quinto grupo de validación ----

fseg_7_5 <- fseg[Grup_7$Indice, Grup_5$Indice] # Este es una matriz de dimensión 5x45 (5 individuos del sexto grupo de validación y 45 idnivdiuos del quinto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 7 y 5 ----

t_fseg_7_5 <- fseg_7_5 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_7_5)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000805439661'
    ) |>
  pivot_longer(
    cols = c(2:46),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_7_5 |> count(Individuos)

t_fseg_7_5 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

############################
# Grupos de validación 7 y 7
############################

# Se importan los individuos del sexto y séptimo grupo de validación y se unen con el objeto "id_fped" que indica la posición (o índice numérico) que cada individuo genotipado ocupa en la matriz de parentesco basado en segmentos ----

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 7') |>
  inner_join(y = id_fped, by = 'ID_id')

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  rename(ID_id = X1) |>
  mutate(Grup_val = 'Grupo 6') |>
  inner_join(y = id_fped, by = 'ID_id')

# Se extrae la matriz de parentesco basado en segmentos de los individuos del sexto y quinto grupo de validación ----

fseg_7_6 <- fseg[Grup_7$Indice, Grup_6$Indice] # Este es una matriz de dimensión 5x11 (5 individuos del séptimo grupo de validación y 1 idnivdiuos del séxto grupo de validación).

# Se calcula el parentesco promedio entre los grupos de validación 7 y 7 ----

t_fseg_7_6 <- fseg_7_6 |>
  as_tibble() |>
  mutate('Individuos 2' = rownames(fseg_7_6)) |>
  relocate(
    `Individuos 2`,
    .before = 'ES000806582398'
    ) |>
  pivot_longer(
    cols = c(2:12),
    names_to = 'Individuos',
    values_to = 'Parentesco'
    )

t_fseg_7_6 |> count(Individuos)

t_fseg_7_6 |>
  summarise(
    prom_par = round(mean(Parentesco), digits = 4),
    desv_par = round(sd(Parentesco), digits = 4),
    min = min(Parentesco),
    max = max(Parentesco)
    )

# Se crea una lista con la matriz de parentesco basado en segemntos del cuarto grupo de validación con el resto de grupos de validación ----

fseg_grupos <- list(fseg_7_1, fseg_7_2, fseg_7_3, fseg_7_4, fseg_7_5, fseg_7_6)

# Se define una función para obtener el amax de un individuo en un grupo específico ----

amax <- function(matrices_fseg) { # Esta función itera sobre cada matriz de parentesco genómico en la lista anterior, obtiene elamax para cada individuo en esa matriz y devuelve una lista con los resultados para cada grupo.

  # Se aplica la función map para iterar sobre cada matriz de parentesco en la lista de matrices de parentesco (fseg_grupos).
  lista_amax <- map(matrices_fseg, ~ {
    
    # Dentro de cada iteración, se obtiene el amax para cada individuo en la matriz de parentesco.
    amax_grupo <- apply(.x, 1, max)
    
    # Se devuelve el vector de amax para el grupo actual.
    amax_grupo
    })
  
  # Se devuelve una lista que contiene los vectores de amax para cada grupo de validación.
  return(lista_amax)
  }

# Se obtiene el amax para cada individuo en cada combinación de grupos de validación ----

amax_grupos <- amax(fseg_grupos)

# Se calcula el valor medio y la desviación estándar del amax para cada grupo ----

res_Grup_7 <- map_dfr(amax_grupos, ~ tibble(Valor_Medio = mean(.x), Desviacion_Estandar = sd(.x), min = min(.x), max = max(.x))) |>
  mutate(
    Grupo = c('Grup_7_1', 'Grup_7_2', 'Grup_7_3', 'Grup_7_4', 'Grup_7_5', 'Grup_7_6')
    ) # Se agrega una columna que indica la combinación del sexto grupo de validación con el resto.

# Para cada combinación de grupo de validación 7 con el resto de grupos de validación se extrae el amax ----

fseg_g7_g1 <- as_tibble(amax_grupos[[1]]) |>
  mutate(Grup_val = 'Grupo 7_1') # Sexto y primer grupo de validación.

fseg_g7_g2 <- as_tibble(amax_grupos[[2]]) |>
  mutate(Grup_val = 'Grupo 7_2') # Sexto y segundo grupo de validación.

fseg_g7_g3 <- as_tibble(amax_grupos[[3]]) |>
  mutate(Grup_val = 'Grupo 7_3') # Sexto y tercer grupo de validación.

fseg_g7_g4 <- as_tibble(amax_grupos[[4]]) |>
  mutate(Grup_val = 'Grupo 7_4') # Sexto y quinto grupo de validación.

fseg_g7_g5 <- as_tibble(amax_grupos[[5]]) |>
  mutate(Grup_val = 'Grupo 7_5') # Sexto y sexto grupo de validación.

fseg_g7_g6 <- as_tibble(amax_grupos[[5]]) |>
  mutate(Grup_val = 'Grupo 7_6') # Séptimo y sexto grupo de validación.

fseg_Grup7 <- bind_rows(fseg_g7, fseg_g7_g1, fseg_g7_g2, fseg_g7_g3, fseg_g7_g4, fseg_g7_g5, fseg_g7_g6)

# Se realiza un gráfico donde se observe la distribución de densidad de las relaciones genéticas basada en segmentos máximas (amax) entre cada individuo en un grupo particular y todos los individuos en el mismo o en diferentes grupos formados por agrupamiento de kmeans ----

fseg_Grup7 |>
  ggplot(aes(x = value, colour = Grup_val, fill = Grup_val)) +
  geom_density(alpha = 0.2) +
  facet_wrap(~ Grup_val, ncol = 3) +
  scale_color_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  scale_fill_manual(values = c('yellow', 'cyan', 'orange', 'green', 'black', 'red', 'brown')) +
  labs(x = 'Coeficiente de relación máximo', y = 'Densidad') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold'),
    strip.background = element_rect(colour = 'black', fill = 'white'),
    strip.text = element_text(size = 12, colour = 'black', face = 'bold'),
    legend.position = 'none'
    )

ggsave('Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM/Imagenes/fseg_Grup7.pdf', width = 40, height = 20, units = 'cm')
```
