---
title: "Parte 6: Generación de archivos necesarios para la imputación a alta densidad mediante Beagle v 5.4, usando información de 50k sin imputar"
format: html
---

```{r}
#| label: Directorio de trabajo

setwd('/home/leonardo/Escritorio/Doc_p1/Plink/Datos/')
```

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(tidyverse)
```

<!--
NOTA: Se carga el software PLINK dentro del ambiente R.
-->

```{r}
#| label: Carga del software PLINK dentro del ambiente R

# Función que permite ejecutar PLINK dentro de R:
plink <- function(PLINKopciones = '') system(paste('./plink', PLINKopciones))

plink() # Al correr esta línea de código aparecen las opciones de PLINK, la versión, entre otros, lo que indica que si se cargo bien este software dentro del ambiente R.
```

<!--
NOTA: Se crea un subconjunto de datos de PLINK donde el genotipado de densidad media (50k) sin imputar contenga los marcadores compartidos con los datos de alta densidad. Para ello, y a diferencia de lo hecho con los datos de 50k imputados, se usan los datos de media densidad anterior a la imputación. Los pasos son iguales a lo hecho anteriormente con los datos de 50k imputados y que puede encontrarse en el archivo Parte-1.qmd.
-->

```{r}
#| label: Subconjunto de datos PLINK con marcadores compartidos en el genotipado de media densidad sin imputar

plink('--cow --allow-extra-chr --vcf ../../Imputacion/Beagle/Datos/Paso_1.vcf --make-bed --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_1') # Usando PLINK, se pasan el archivo VCF a datos PLINK binarios (.bed, .fam y .bim).

system2('plink2', args = paste0('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_1 --alt1-allele force ../../Imputacion/Beagle/Datos/Precision/Prec_1/aleloALT.txt --make-bed --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_2')) # Se convierte los genotipos (0/0, 0/1, 1/1) del Beagle a (0, 1, 2), indicando el aleloB (1/1: 2) como el alelo alternativo. Se utiliza plink2 ya que este tiene la opción --alt1-allele force.

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_2 --extract ../../Imputacion/Imp_HD/Datos/datQC/marc_comun.txt -make-bed --recode --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_3')

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_3 -update-parents ../../Imputacion/Datos/ID_ind.txt --make-bed --recode --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_4') # Se actualiza la información parental.
```

<!--
NOTA: A continuación, se genera un archivo nomb_marc_comun.txt con el nombre de marcadores en común con ID antiguo y ID nuevo (este último corresponde al ID del marcador de los datos de media densidad). Esto para que los nombres de los marcadores en común de los datos de media y alta densidad queden igual.
-->

```{r}

#| label: Nombre de marcadores coincidentes

# Se crea una lista para almacenar los resultados de cada cromosoma:
bim50k_list <- list()

# Se recorre los cromosomas del 1 al 29:
for (cromosoma in 1:29) {

  # Se lee el archivo Paso_5.bim (que contiene el nombre y la posición de los marcadores de HD) y se filtra por cromosoma y marcadores en común
  bimHD <- read_table(file = '../../Imputacion/Imp_HD/Datos/datQC/Paso_5.bim', col_names = FALSE) %>%
    filter(X1 == cromosoma) %>%
    select(X2, X4)

  # Se lee el archivo Paso_8.bim (que contiene el nombre y la posición de los marcadores de 50k) y se filtra por cromosoma
  bim50k <- read_table(file = 'datQC/Paso_8.bim', col_names = FALSE) %>%
    filter(X1 == cromosoma) %>%
    inner_join(y = bimHD, by = 'X4') %>%
    rename(
      nomb_Mar_50k = X2.x,
      nomb_Mar_HD = X2.y
      ) %>%
    select(nomb_Mar_50k, nomb_Mar_HD)

  # Se agrega el resultado a la lista
  bim50k_list[[cromosoma]] <- bim50k
  }

# Se combinan los resultados en un único dataframe:
bim50k <- bind_rows(bim50k_list) %>%
  distinct(nomb_Mar_50k, .keep_all = TRUE) %>%
  relocate(
    nomb_Mar_50k,
    .after = nomb_Mar_HD
    ) # El archivo de texto que contiene las actualizaciones que desea realizar, debe tener el siguiente formato: nombre_antiguo | nombre_nuevo. 

bim50k %>%
  write_delim(file = '../../Imputacion/Imp_HD/Datos/datQC_2/nomb_marc_comun.txt', col_names = FALSE)
```

<!--
NOTA: Se actualiza a continuación el nombre de los marcadores en los datos PLINK datQC/Paso_2, de tal forma que se genere unos datos de genotipos con el nombre de los marcadores donde se combine la ID de estos según el tipo de genotipado (media densidad y alta densidad), pero con la posición (en pares de bases) y su ubicación (cromosoma) según el mapa del genotipado de alta densidad (UMD 3.1).
-->

```{r}
#| label: Actualización de nombres de marcadores en común

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC/Paso_2 --update-name ../../Imputacion/Imp_HD/Datos/datQC_2/nomb_marc_comun.txt -make-bed --recode --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_5')
```

<!--
NOTA: Se vuelve a actualizar la información de posición de los marcadores, esto para que, una vez se haya actualizado los nombres de los marcadores en común de acuerdo a su posición, los marcadores genotipados a HD queden con una posición de acuerdo al mapa ensamblado en ARS-UCD1.2.
-->

```{r}
#| label: Actualización de posición de los marcadores

# Se importa el conjunto de datos donde se encuentra la ID del maracdor y su posición de acuerdo al ensamblado ARS-UCD1.2 ---

pos_Mar_UMD <- read_delim(file = '../../Imputacion/Imp_HD/Datos/datQC/pos_Mar_ARS.txt', col_names = FALSE) %>%
  rename(
    ID_mar = X1, # Este corresponde a la ID del marcador.
    pos_ARS = X2 # Este corresponde a la posición de ese marcador.
    )

# Se importa el conjunto de datos con ID del maracdor y ID del marcador según el genotipado de densidad media (ensamblado en ARS) ---

mar_comun <- read_delim(file = '../../Imputacion/Imp_HD/Datos/datQC_2/nomb_marc_comun.txt', col_names = FALSE) %>%
  rename(
    ID_mar = X1, # Este corresponde a la ID del marcador.
    ID_ARS = X2 # Este corresponde a la ID del marcador según el ensamblado en ARS-UCD1.2.
    ) %>%
  full_join(x = pos_Mar_UMD, by = 'ID_mar')

mar_comun |> slice(33374:33384) # Se observa que en la columna 3, que corresponde al ID del marcador según el ensamblado en ARS-UCD1.2, hay valores en NA.

mar_comun_2 <- mar_comun %>%
  mutate(ID_ARS = coalesce(ID_ARS, ID_mar)) # Usando la función coalesce(), se reemplaza los valores en NA. Esta función reemplaza los valores NA con el primer valor no NA que encuentra en un conjunto de columnas

mar_comun_2 |> slice(33374:33384) # Se observa que en la columna 3 ya no hay valores en NA, sino que se asigno como ID la ID del marcador según el ensamblado en UMD 3.1.

# Se importa el conjunto de datos rersultante de los pasos anteriores ---

mar_comun_2 %>%
  select(ID_ARS, pos_ARS) %>%
  write_delim('../../Imputacion/Imp_HD/Datos/datQC_2/pos_Mar_ARS_2.txt', col_names = FALSE)

# Se actualiza la posición de los marcadores usando PLINK ---

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_5 --update-map ../../Imputacion/Imp_HD/Datos/datQC_2/pos_Mar_ARS_2.txt --make-bed --recode --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_6')
```

<!--
NOTA: Por último en todo el proceso de actualización del mapa, se actualizan los cromosomas de los datos genómicos. Para ello, se genera inicialmente el archivo *.txt con la ID del marcador y los cromosomas actualizados. Esto usando la opción --update-chr de PLINK.
-->

```{r}
#| label: Actualización de cromosomas

# Se actualizan los cromosomas usando PLINK usando el archivo generado en Parte-1.qmd y que contiene la actualización de cromosomas para los marcadores ---

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_6 --update-chr ../../Imputacion/Imp_HD/Datos/datQC/Chr_Mar_ARS.txt --make-bed --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_7') # Al usar --update-chr, se esta realizando una operación específica de actualización de cromosomas sin generar un nuevo conjunto completo de archivos .bed, .bim, .fam. Por lo tanto, el archivo .map no se generará automáticamente.
```

<!--
NOTA: A continuación, se verifica si hay marcadores duplicados por posición, y si es así, se elimina uno de ellos.
-->

```{r}
#| label: Marcadores duplicados por posición

snpDupPos <- read_table(file = '../../Imputacion/Imp_HD/Datos/datQC_2/Paso_7.bim', col_names = FALSE)

snpDupPos_2 <- snpDupPos %>%
  unite(
    col = 'Posicion',
    c(X1, X4) # Aquí se unen estas dos columnas para observar los marcadores duplicados por posición (siendo la columna "X1" el cromosoma y la columna "X4" la posición en pares de bases).
        ) %>%
  group_by(Posicion) %>%
  filter(n() > 1) %>%
  ungroup() # Estos son una lista de marcadores duplicados por posición.

snpDupPos_2 %>%
  group_by(Posicion) %>%
  slice(2) %>% # Se quita uno de los dos marcadores duplicados por posición, preferiblemente los de la segunda posición, ya que en la primera esta los marcadores nombrados como "Affy-...".
  ungroup() %>%
  select(X2) %>%
  write_delim(file = '../../Imputacion/Imp_HD/Datos/datQC_2/snpDup.txt', col_names = FALSE)

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_7 --list-duplicate-vars --out ../../Imputacion/Imp_HD/Datos/datQC_2/dup_HD') # Con PLINK también se pueden identificar los marcadores duplicados.

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_7 --exclude ../../Imputacion/Imp_HD/Datos/datQC_2/snpDup.txt -make-bed --recode --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_8') # Se quitan los marcadores duplicados por posición.
```

<!--
NOTA: Se actualiza a continuación la ID de la familia, obteniendose con esto los datos de alta densidad deseados para la unión con los datos de densidad media.
-->

```{r}
#| label: ID de la familia actualizado y generación de datos de alta densidad deseados

datFam <- read_table(file = '../../Imputacion/Imp_HD/Datos/datQC_2/Paso_8.fam', col_names = FALSE)

datFam %>%
  select(X2) %>%
  mutate(
    X1 = 0,
    X3 = X2,
    X4 = X2
    ) %>% # El archivo para actualizar la ID de la familia de tener las columnas de ID familiar antiguo, ID del individuo antiguo, nueva identificación familiar y nueva identificación del individuo.
  relocate(
    X1,
    .before = X2
    ) %>%
  write_delim(file = '../../Imputacion/Imp_HD/Datos/datQC_2/ID_fam.txt', col_names = FALSE)

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_8 --update-ids ../../Imputacion/Imp_HD/Datos/datQC_2/ID_fam.txt -make-bed --recode --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_9') # Se actualiza la ID de la familia.
```

<!--
NOTA: Más adelante se unirán los datos de genotipado de media y alta densidad, y con el conjunto de datos resultante de dicha unón se realizará la imputación a alta densidad. Al comparar los archivo *.bim (Paso_4.bim y Paso_9.bim, para el genotipado de media y alta densidad, respectivamente) se observa en las columnas 5 y 6 un cambio de orientación de alelos (por ejemplo, el marcador Affx-106521083 presenta en Paso_4.bim los alelos C-T, mientras que en Paso_7.bim los alelos G-A). Esto significa que los mismos alelos están siendo representados de manera diferente en los dos conjuntos de datos, lo que puede llevar a errores durante el proceso de unión. Por ello, a continuación se identifica que marcadores presentan este problema, y luego mediante el uso de la opción --flip de PLINK se corrige la orientación de los alelos en los datos de alta densidad antes de fusionarlos con el de media densidad. Esto asegurará que los alelos sean representados de la misma manera en ambos conjuntos de datos y evitará problemas de unión debido a diferencias en la orientación de los alelos.
-->

```{r}
#| label: Identificación de marcadores con orientación de alelos diferentes y flipeado

datbim_50k <- read_table(file = '../../Imputacion/Imp_HD/Datos/datQC_2/Paso_4.bim', col_names = FALSE) %>%
  select(2, 4:6) %>%
  unite(
    col = 'Orientacion_50k',
    X5:X6,
    sep = '_'
    )

datbim_HD <- read_table(file = '../../Imputacion/Imp_HD/Datos/datQC_2/Paso_9.bim', col_names = FALSE) %>%
  select(2, 4:6) %>%
  unite(
    col = 'Orientacion_HD',
    X5:X6,
    sep = '_'
    )

datbim <- inner_join(
  x = datbim_HD,
  y = datbim_50k,
  by = c('X2', 'X4')
    ) %>%
  mutate(
  Orientacion = case_when(
    (Orientacion_HD == 'G_A' & Orientacion_50k == 'C_T') |
    (Orientacion_HD == 'A_G' & Orientacion_50k == 'C_T') |
    (Orientacion_HD == 'C_T' & Orientacion_50k == 'G_A') |
    (Orientacion_HD == 'T_C' & Orientacion_50k == 'G_A') |
    (Orientacion_HD == 'C_T' & Orientacion_50k == 'A_G') |
    (Orientacion_HD == 'T_C' & Orientacion_50k == 'A_G') |
    (Orientacion_HD == 'A_G' & Orientacion_50k == 'T_C') |
    (Orientacion_HD == 'G_A' & Orientacion_50k == 'T_C') |
    (Orientacion_HD == 'A_C' & Orientacion_50k == 'T_G') |
    (Orientacion_HD == 'A_C' & Orientacion_50k == 'G_T') |
    (Orientacion_HD == 'A_C' & Orientacion_50k == 'T_C') |
    (Orientacion_HD == 'A_C' & Orientacion_50k == 'C_T') |
    (Orientacion_HD == 'C_A' & Orientacion_50k == 'T_G') |
    (Orientacion_HD == 'C_A' & Orientacion_50k == 'G_T') |
    (Orientacion_HD == 'C_A' & Orientacion_50k == 'T_C') |
    (Orientacion_HD == 'C_A' & Orientacion_50k == 'C_T') |
    (Orientacion_HD == 'T_G' & Orientacion_50k == 'T_C') |
    (Orientacion_HD == 'G_A' & Orientacion_50k == 'C_A') ~ 'Diferente',
    TRUE ~ 'Igual'
    )
  ) %>%
  filter(Orientacion != 'Igual') # Se dejan solo los marcadores cuya orientación sea diferente.
  
datbim %>%
  select(X2) %>%
  write_delim(file = '../../Imputacion/Imp_HD/Datos/datQC_2/flip_HD.txt', col_names = FALSE)

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_9 --flip ../../Imputacion/Imp_HD/Datos/datQC_2/flip_HD.txt -make-bed --recode --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_10')
```

<!--
NOTA: A continuación, se unen los datos de media y alta densidad, siendo este último el flipeado.
-->

```{r}
#| label: Unión de datos de media y alta densidad 1

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_4 --bmerge ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_10.bed ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_10.bim ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_10.fam --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_11 --list-duplicate-vars') # En caso de que se genere un problema debido a marcadores multialelicos, en el archivo *.missnp (en este caso, Paso_11.missnp) se genera una lista de esos marcadores. La opción --list-duplicate-vars permite identificar variantes que tienen una orientación diferente en los dos conjuntos de datos que se estan intentando unir. Esta opción generará un archivo de salida que mostrará las variantes que tienen alelos diferentes entre los dos conjuntos de datos.
```

<!--
NOTA: A continuación se eliminan los dos marcadores restantes luego de la identificación de alelos con orientación diferente y flipeado. Esto dos marcadores, a diferencia del resto, no tienen problemas de orientación de alelos, sino que se tratan de dos marcadores trialélicos (repesentados en el archivo Paso_11.missnp). Luego, se intenta unir nuevamente ambos conjuntos de datos de media y alta densidad.
-->

```{r}
#| label: Unión de datos de media y alta densidad 2

tibble(
  x = c(
    'Affx-106543991', 'Affx-478777195'
    ) # Se crea una lista con el nombre de los dos marcadores trialélicos.
  ) %>%
  write_delim(file = '../../Imputacion/Imp_HD/Datos/datQC_2/snpMult.txt', col_names = FALSE)

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_10 --exclude ../../Imputacion/Imp_HD/Datos/datQC_2/snpMult.txt -make-bed --recode --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_12') # Se quitan los marcadores trialélicos.

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_4 --bmerge ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_12.bed ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_12.bim ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_12.fam --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_13 --list-duplicate-vars')
```

<!--
NOTA: Se dejan solo los 284 individuos de los datos de alta densidad a continuación. Esto para evaluar la precisión de la imputación en estos individuos.
-->

```{r}
#| label: Datos de densidades combinadas

ID_HD <- read_table(file = '../../Imputacion/Imp_HD/Datos/datQC/Paso_12.fam', col_names = FALSE) %>%
  select(X2) %>%
  mutate(ID_fam = X2) %>% # Este corresponderia al ID familiar, que en el caso de los datos de alta densidad es igual a 0 para todos los individuos.
  relocate(
    ID_fam,
    .before = X2
    ) %>%
  write_delim(file = '../../Imputacion/Imp_HD/Datos/datQC_2/ID_HD.txt', col_names = FALSE, delim = '\t')

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_13 --keep ../../Imputacion/Imp_HD/Datos/datQC_2/ID_HD.txt -make-bed --recode --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_14')
```

<!--
NOTA: Una vez se unen los datos de media y alta densidad se convierte los datos en formato PLINK a formato VCF, y se guarda en la carpeta Imp_HD/Datos/Beagle con el nombre de "imp_HD_50k".
-->

```{r}
#| label: Paso a formato VCF

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_14 --recode vcf --alleleACGT --out ../../Imputacion/Imp_HD/Datos/Beagle/Precision_origen/imp_HD_50k --const-fid')
```

<!--
NOTA: Para realizar la imputación a alta densidad con Beagle v. 5.4, los 2970 individuos presentes tanto en densidad media (50k) como en alta densidad (HD) con 719592 marcadores, luego de su unión (datos de densidades combinadas), se pasan a formato VCF. Esto para que al comparar la precisión de la predicción genómica con los datos de 50k, se compare distintas densidades en los mismos individuos.
-->

```{r}
#| label: Paso a formato VCF 2

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_13 --recode vcf --alleleACGT --out ../../Imputacion/Imp_HD/Datos/Beagle/Precision_origen/imp_HD_50k_2 --const-fid')
```

<!--
NOTA: Se genera a continuación los datos de 50K para imputar.
-->

```{r}
#| label: Datos en 50K para imputar

read_table(file = '../../Imputacion/Imp_HD/Datos/datQC_2/nomb_marc_comun.txt', col_names = FALSE) %>%
  select(X2) %>%
  write_delim(file = '../../Imputacion/Imp_HD/Datos/datQC_2/marc_comun_50K.txt', col_names = FALSE) # Se extrae la columna con el nombre de los 33378 marcadores en común según el genotipado en 50K.

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_13 --extract ../../Imputacion/Imp_HD/Datos/datQC_2/marc_comun_50K.txt  -make-bed --recode --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_15') # Del conjunto de datos de PLINK con 2970 indviduos y 719592 marcadores (en HD), me quedo solo con los 33378 maracdores en común con el genotipado a 50K.

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_2 --bmerge ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_15.bed ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_15.bim ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_15.fam --out ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_16 --list-duplicate-vars') # Uno los datos de PLINK generados en el paso anterior con el conjunto de datos de 50K, generando así un conjunto de datos con 3970 individuos y 43421 marcadores (los de 50K). Por lo tanto, 43421 - 33378 = 10043 marcadores se trarán como missing o valores faltantes en 2970 - 2894 = 76 individuos.
```

<!--
NOTA: Para realizar la imputación a media densidad con Beagle v. 5.4, los 2970 individuos presentes tanto en densidad media (50k) como en alta densidad (HD) con 43421 marcadores (la cantidad de marcadores en 50K luego del control de calidad), se pasan a formato VCF. Esto para que al comparar la precisión de la predicción genómica entre densidades variadas (HD y 50K), se compare distintas densidades en los mismos individuos.
-->

```{r}
#| label: Paso a formato VCF 3

plink('--cow --allow-extra-chr --bfile ../../Imputacion/Imp_HD/Datos/datQC_2/Paso_16 --recode vcf --alleleACGT --out ../../Imputacion/Imp_HD/Datos/Beagle/Precision_origen/imp_HD_50k_3 --const-fid')
```

<!--
NOTA: Se comprueba a continuación que los individuos genotipados en densidad media (50k) y que serán imputados a alta densidad (HD) y no aparezcan en este último antes de la unión de ambos genotipados (mediante la opción plink "bmerge"), tengan marcadores en missing. Lo mismo para los individuos genotipados en HD y que serán imputados a 50k.
-->

```{r}
#| label: Verificación de imputación

# Se importa a continuación los marcadores en común entre el genotipado en densidad media (50k) y alta (HD) ----

nomb_marc_comun <- read_delim(file = '../../Imputacion/Imp_HD/Datos/datQC_2/nomb_marc_comun.txt', col_names = FALSE)

# Se importa el archivo en formato VCF que se uso para imputar a 50k ----

imp_50k <- data.table::fread(file = '../../Imputacion/Imp_HD/Datos/Beagle/Precision_origen/imp_HD_50k_3.vcf', sep = '\t', skip = '#CHROM', header = TRUE) |>
  select(-c(1:2, 4:9))

imp_50k |> select(1:4) |> slice_head(n = 12)

imp_50k |> select('ID', 'ES000803657207_ES000803657207', 'ES000807204804_ES000807204804', 'ES021202235562_ES021202235562', 'ESCC0299AG_ESCC0299AG') |> filter(!ID %in% nomb_marc_comun$X2) # Se observan estos cuatro individuos. Los primeros dos individuos no tienen genotipos en 50k, por lo cual al filtrar los marcadores en común entre 50k y HD, dichos marcadores aparecen como missing. Contrario a los últimos dos individuos.

# Se importa el archivo en formato VCF que se uso para imputar a HD ----

imp_HD <- data.table::fread(file = '../../Imputacion/Imp_HD/Datos/Beagle/Precision_origen/imp_HD_50k_2.vcf', sep = '\t', skip = '#CHROM', header = TRUE) |>
  select(-c(1:2, 4:9))

imp_HD |> select(1:4) |> slice_head(n = 12)

imp_HD |> select('ID', 'ES000803657207_ES000803657207', 'ES000807204804_ES000807204804', 'ES000702712752_ES000702712752', 'ES000801569724_ES000801569724') |> filter(!ID %in% nomb_marc_comun$X2) # Se observan estos cuatro individuos. Los primeros dos individuos, contrario a lo visto en 50k, si tienen genotipos en HD, por lo cual al filtrar los marcadores en común entre 50k y HD, esta vez dichos marcadores no aparecen como missing. Contrario a los últimos dos individuos que si estan genotipados a 50k pero no en HD, por lo que dichos marcadores aparecen como missing.
```
