---
title: "Parte 18: Agrupación jerárquica basado en una matriz de disimilitud o de distancia de identidad por estado (IBS) y generación de grupos de validación"
format: html
---

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(here, tidyverse, snpStats, ggplot2)
```

<!--
NOTA: Se genera la matriz de disimilitud o de distancia en base a identidad por estado (IBS). Esto para posteriormente realizar con ella la agrupación jerárquica.
-->

```{r}
#| label: Matriz de disimilitud o de distancia genética en base a identidad por estado (IBS)

# Se importa los archivos *.bed, *.bim y *.fam de PLINK ---

dat_Geno <- read.plink(
  bed = here('Imputacion', 'Imp_HD', 'Datos', 'datQC_2', 'Paso_14.bed'),
  bim = here('Imputacion', 'Imp_HD', 'Datos', 'datQC_2', 'Paso_14.bim'),
  fam = here('Imputacion', 'Imp_HD', 'Datos', 'datQC_2', 'Paso_14.fam')
  ) # Al importar los archivos de PLINK con la función anterior read.plink(), se crea un objeto (lista) con tres elementos.

mGeno <- dat_Geno$genotypes # Aquí se extrae la matriz de genotipos (con marcadores en columnas e individuos en filas).

head(dat_Geno$fam) # Se observa aquí el archivo de texto *.fam que contiene información sobre los individuos.

head(dat_Geno$map) # Se observa aquí el archivo de texto *.map que contiene información sobre los marcadores genéticos. 

# A continuación se cuenta, para todos los pares de individuos y en todos los SNP, el número total de alelos que son identicos por estado (IBS) ---

al_ibs <- ibsCount(snps = mGeno) # Esta función, ibsCount(), cuenta para cada par de individuos el número total de alelos que son IBS.

# Se obtiene a continuación la matriz de distancia ---

al_dist <- ibsDist(counts = al_ibs) # La función ibsDist() genera una matriz de distancia genética entre individuos basada en la información de IBS. Valores más bajos indican mayor similitud genética, mientras que valores más altos indican mayor diferencia genética.

m_distancia <- as.matrix(al_dist) # En lugar de mostrar una matriz completa, la función anterior, ibsDist(), devuelve un vector que contiene las distancias entre pares únicos de individuos. De esta forma se obtiene la matriz completa que se observa a continuación que es simetrica.

m_distancia[281:284, 281:284]

# Se exporta la anterior matriz de distancia genética basada en IBS ---

m_distancia |>
  save(file = here('Imputacion', 'Imp_HD', 'Datos', 'Beagle', 'Precision_origen', 'Precision_IBS', 'mDG.RData')) # Se importa la matriz de distancia genética.
```

<!--
NOTA: Se realiza una agrupación jerárquica usando la matriz de disimilitud o de distancia en base a identidad por estado (IBS) anterior.
-->

```{r}
#| label: Agrupación jerárquica (dendograma) basado en la matriz de distancia genética de identidad por estado (IBS)

# Se carga la anterior matriz de distancia genética  ---

load(file = here('Imputacion', 'Imp_HD', 'Datos', 'Beagle', 'Precision_origen', 'Precision_IBS', 'mDG.RData'))

# Se realizá el gráfico de agrupación jerárquica---

m_distancia <- as.dist(m_distancia) # Se convierte la matriz de distancia a tipo "dist", para que sea compatible con la función a continuación hclust().

res.hc <- hclust(m_distancia, method = 'ward.D2') # Se realiza el custering jerárquico. Para ello, se usa el método "ward.D2", que es un método comúnmente utilizado para minimizar la varianza dentro de los clusters. De esta forma, se cree que sería posible aumentar las relaciones dentro del grupo y disminuir las relaciones entre grupos en base a sus relaciones genéticas.

texto <- tibble(
  x = as.Date(c(25, 75, 104, 225)),
  y = c(0.54, 0.54, 0.54, 0.54),
  text = c(
    '**Grupo 1**',
    '**Grupo 2**',
    '**Grupo 3**',
    '**Grupo 4**'
    )
  )

factoextra::fviz_dend( # Se visualiza el dendrograma usando el paquete "factoextra".
  x = res.hc,
  k = 4, # Se indica aquí formar 4 clusters.
  cex = 0.3, lwd = 0.4,
  #rect = TRUE,
  k_colors = c('green', 'cyan', 'orange', 'red'),
  #rect_border = 'gray',
  rect_fill = FALSE
  ) +
  ggtext::geom_textbox(data = texto, aes(x = x, y = y, label = text), box.r = unit(10.5, 'pt'), box.padding = unit(c(4.5, 4.5, 4.5, 4.5), 'pt'), width = unit(0.8, "inch")) +
  coord_cartesian(ylim = c(-0.05, 0.8)) +
  labs(title = ' ', x = ' ', x = ' ', y = ' ') +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank()
    )

ggsave(here('Imputacion', 'Imp_HD', 'Datos', 'Beagle', 'Precision_origen', 'Precision_IBS', 'Imagenes', 'dendograma.pdf'), width = 40, height = 20, units = 'cm')
```

<!--
NOTA: Se crean las distintas carpetas donde se guardaran los resultados de la imputación para los 4 grupos de validación.
-->

```{r}
#| label: Subcarpetas de validación

# 1. Se indica la ruta base de la carpeta donde deseas crear las subcarpetas:
ruta_base <- '../../Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_IBS/'

# 2. Se utiliza un bucle for para crear las 4 carpetas:
for (i in 1:4) {
  # Se genera el nombre de la carpeta
  nombre_carpeta <- paste0('Prec_', i)
  
  # Se crean la carpetas
  dir.create(paste0(ruta_base, nombre_carpeta))
  } # La función paste0() se utiliza para concatenar el nombre de la carpeta con la ruta base. El bucle for recorre los valores de 1 a 4 y en cada iteración crea una nueva carpeta utilizando la función dir.create().
```

<!--
NOTA: A continuaicón, se generan cuatro grupos de validación en base a los cuatro grupos generados anteriormente mediante agrupación jerárquica.
-->

```{r}
#| label: Generación de grupos de validación.

grup <- cutree(tree = res.hc, k = 4) # Del cluster jerárquico anterior, se extrae la ID de los individuos y el grupo al cual fue clasificado en base la matriz de distancia genética de identidad por estado (IBS).

grup_2 <- tibble(
  ID = as.character(res.hc$labels),
  Grupo = as.factor(grup)
  ) # Se convierte a "tibble" para observar la ID de los individuos y el grupo de clasificación en columnas.

#########
# Grupo 1
#########

grup_2 |>
  mutate(ID_2 = ID) |>
  unite(
    col = ID,
    c(ID,ID_2)
    ) |>
  filter(Grupo == 1) |>
  select(ID) |>
  write_delim(here(file = 'Imputacion', 'Imp_HD', 'Datos', 'Beagle', 'Precision_origen', 'Precision_IBS', 'Prec_1', 'Grup1.txt'), col_names = FALSE)

#########
# Grupo 2
#########

grup_2 |>
  mutate(ID_2 = ID) |>
  unite(
    col = ID,
    c(ID,ID_2)
    ) |>
  filter(Grupo == 2) |>
  select(ID) |>
  write_delim(here(file = 'Imputacion', 'Imp_HD', 'Datos', 'Beagle', 'Precision_origen', 'Precision_IBS', 'Prec_2', 'Grup2.txt'), col_names = FALSE)

#########
# Grupo 3
#########

grup_2 |>
  mutate(ID_2 = ID) |>
  unite(
    col = ID,
    c(ID,ID_2)
    ) |>
  filter(Grupo == 3) |>
  select(ID) |>
  write_delim(here(file = 'Imputacion', 'Imp_HD', 'Datos', 'Beagle', 'Precision_origen', 'Precision_IBS', 'Prec_3', 'Grup3.txt'), col_names = FALSE)

#########
# Grupo 4
#########

grup_2 |>
  mutate(ID_2 = ID) |>
  unite(
    col = ID,
    c(ID,ID_2)
    ) |>
  filter(Grupo == 4) |>
  select(ID) |>
  write_delim(here(file = 'Imputacion', 'Imp_HD', 'Datos', 'Beagle', 'Precision_origen', 'Precision_IBS', 'Prec_4', 'Grup4.txt'), col_names = FALSE)
```
