---
title: "Parte 28: Evaluación de la precisión de la imputación usando grupos de validación formado mediante k-means a partir del parentesco genómico con IBS, imputación que se realizará utilizando el programa Beagle v5.4 - Parte 1"
format: html
---

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(tidyverse)
```

<!--
NOTA: Se carga el software PLINK dentro del ambiente R.
-->

```{r}
#| label: Carga del software PLINK dentro del ambiente R

# Función que permite ejecutar PLINK dentro de R:
plink <- function(PLINKopciones = '') system(paste('/home/leonardo/Escritorio/Doc_p1/Plink/Datos/plink', PLINKopciones))

plink() # Al correr esta línea de código aparecen las opciones de PLINK, la versión, entre otros, lo que indica que si se cargo bien este software dentro del ambiente R.
```

<!--
NOTA: Se identifica a continuación los marcadores con genotipo completo en todos los 284 individuos. Para ello, se utiliza la opción --geno para filtrar los marcadores que tienen tasas de valores faltantes igual a cero.
-->

```{r}
#| label: Identificación de marcadores completamente genotipados

# Se usa PLINk para identificar los marcadores con genotipo completos en todos los individuos ----

plink('--cow --allow-extra-chr --bfile Imputacion/Imp_HD/Datos/datQC_2/Paso_14 --geno 0  --make-bed --recode --out Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Paso_1') # Luego se obtiene como resultado (que se indica en Paso_3.log) un archivo con 598677 marcadores en 284 individuos.

# Se exporta el nombre de los marcadores con genotipo completos ----

nomGen <- read_table(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Paso_1.bim', col_names = FALSE) # Se importa el archivo *.bim anteriormente generado con PLINK con el nombre de los marcadores con genotipo completos.

nomGen %>%
  select(X2) %>%
  write_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/nomGen.txt', col_names = FALSE, delim = ' ')
```

<!--
NOTA: Se modifica el archivo VCF que se uso inicialmente en la imputación (imp_HD_50k.vcf), para enmascarar los genotipos de los marcadores para cada uno de los grupos de validación, y luego se exportan en cada una de las subcarpetas.
-->

```{r}
#| label: Genotipos enmascarados

# Se indica la ruta del archivo vcf y del archivo donde estan los nombres de los marcadores ----

vcf_file <- "Imputacion/Imp_HD/Datos/Beagle/Precision_origen/imp_HD_50k.vcf"
marcadores_file <- "Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_IBS/nomGen.txt"

# Se lee el archivo VCF ----

vcf_data <- data.table::fread(vcf_file, sep = "\t", skip = "#CHROM", header = TRUE) # Con skip = "#CHROM" se indica iniciar en la fila donde estan los nombres de las columnas.

#######################################
# Precisión en el grupo de validación 1
#######################################

# Se importan los individuos ----

Grup_1 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_1/Grup1.txt', col_names = FALSE, delim = ' ') |>
  mutate(ID_2 = X1) |>
  unite(
    col = ID,
    1:2,
    sep = '_'
    ) |>
  pull()

# Se indica la ruta de los archivos donde se guardará el archivo vcf generado con el marcador enmascarado ----

output_file <- "Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_1/Grup1.vcf"

# Se leen los nombres de los marcadores ----

marcadores <- readLines(marcadores_file)

# Se realiza el cambio en los genotipos de los individuos ----

vcf_data_1 <- vcf_data %>%
  mutate_at(vars(one_of(Grup_1)),
            ~ case_when(ID %in% marcadores ~ "./.",
                        TRUE ~ .))

vcf_data_1 %>% 
  filter(ID %in% c('Affx-113744580', 'Affx-113731463', 'BovineHD2700009653', 'Affx-106536391')) %>% 
  select(ES040807701508_ES040807701508, ES060807045343_ES060807045343, ES080810565274_ES080810565274, ES080807347040_ES080807347040) # Se realiza la prueba para ver por ejemplo si los marcadores se enmascaran. Los genotipos de estos individuos aparece como "./.", y antes en el objeto "vcf_data" si tenian genotipos.

# Se guarda el archivo VCF modificado ----

data.table::fwrite(vcf_data_1, output_file, sep = "\t", quote = FALSE) # Se mira el numero de filas y de columnas mediante la terminal de linux: awk '{print NR}' Grup1.vcf | tail -n 1 && awk '{print NF; exit}' Grup1.vcf.

#######################################
# Precisión en el grupo de validación 2
#######################################

# Se importan los individuos ----

Grup_2 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_2/Grup2.txt', col_names = FALSE, delim = ' ') |>
  mutate(ID_2 = X1) |>
  unite(
    col = ID,
    1:2,
    sep = '_'
    ) |>
  pull()

# Se indica la ruta de los archivos donde se guardará el archivo vcf generado con el marcador enmascarado ----

output_file <- "Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_2/Grup2.vcf"

# Se leen los nombres de los marcadores ----

marcadores <- readLines(marcadores_file)

# Se realiza el cambio en los genotipos de los individuos ----

vcf_data_2 <- vcf_data %>%
  mutate_at(vars(one_of(Grup_2)),
            ~ case_when(ID %in% marcadores ~ "./.",
                        TRUE ~ .))

vcf_data_2 %>% 
  filter(ID %in% c('Affx-113744580', 'Affx-113731463', 'BovineHD2700009653', 'Affx-106536391')) %>% 
  select(ES070809139112_ES070809139112, ES090806115252_ES090806115252, ESCC0299AG_ESCC0299AG, ES041004446874_ES041004446874) # Se realiza la prueba para ver por ejemplo si los marcadores se enmascaran. Los genotipos de estos individuos aparece como "./.", y antes en el objeto "vcf_data" si tenian genotipos.

# Se guarda el archivo VCF modificado ----

data.table::fwrite(vcf_data_2, output_file, sep = "\t", quote = FALSE)

#######################################
# Precisión en el grupo de validación 3
#######################################

# Se importan los individuos ----

Grup_3 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_3/Grup3.txt', col_names = FALSE, delim = ' ') |>
  mutate(ID_2 = X1) |>
  unite(
    col = ID,
    1:2,
    sep = '_'
    ) |>
  pull()

# Se indica la ruta de los archivos donde se guardará el archivo vcf generado con el marcador enmascarado ----

output_file <- "Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_3/Grup3.vcf"

# Se leen los nombres de los marcadores ----

marcadores <- readLines(marcadores_file)

# Se realiza el cambio en los genotipos de los individuos ----

vcf_data_3 <- vcf_data %>%
  mutate_at(vars(one_of(Grup_3)),
            ~ case_when(ID %in% marcadores ~ "./.",
                        TRUE ~ .))

vcf_data_3 %>% 
  filter(ID %in% c('Affx-113744580', 'Affx-113731463', 'BovineHD2700009653', 'Affx-106536391')) %>% 
  select(ES091202624142_ES091202624142, ES030808937934_ES030808937934, ES000805439661_ES000805439661, ES021202123705_ES021202123705) # Se realiza la prueba para ver por ejemplo si los marcadores se enmascaran. Los genotipos de estos individuos aparece como "./.", y antes en el objeto "vcf_data" si tenian genotipos.

# Se guarda el archivo VCF modificado ----

data.table::fwrite(vcf_data_3, output_file, sep = "\t", quote = FALSE)

#######################################
# Precisión en el grupo de validación 4
#######################################

# Se importan los individuos ----

Grup_4 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_4/Grup4.txt', col_names = FALSE, delim = ' ') |>
  mutate(ID_2 = X1) |>
  unite(
    col = ID,
    1:2,
    sep = '_'
    ) |>
  pull()

# Se indica la ruta de los archivos donde se guardará el archivo vcf generado con el marcador enmascarado ----

output_file <- "Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_4/Grup4.vcf"

# Se leen los nombres de los marcadores ----

marcadores <- readLines(marcadores_file)

# Se realiza el cambio en los genotipos de los individuos ----

vcf_data_4 <- vcf_data %>%
  mutate_at(vars(one_of(Grup_4)),
            ~ case_when(ID %in% marcadores ~ "./.",
                        TRUE ~ .))

vcf_data_4 %>% 
  filter(ID %in% c('Affx-113744580', 'Affx-113731463', 'BovineHD2700009653', 'Affx-106536391')) %>% 
  select(ES020810557565_ES020810557565, ES020807662326_ES020807662326, ES000806582398_ES000806582398, ESLE2012GB_ESLE2012GB) # Se realiza la prueba para ver por ejemplo si los marcadores se enmascaran. Los genotipos de estos individuos aparece como "./.", y antes en el objeto "vcf_data" si tenian genotipos.

# Se guarda el archivo VCF modificado ----

data.table::fwrite(vcf_data_4, output_file, sep = "\t", quote = FALSE)

#######################################
# Precisión en el grupo de validación 5
#######################################

# Se importan los individuos ----

Grup_5 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_5/Grup5.txt', col_names = FALSE, delim = ' ') |>
  mutate(ID_2 = X1) |>
  unite(
    col = ID,
    1:2,
    sep = '_'
    ) |>
  pull()

# Se indica la ruta de los archivos donde se guardará el archivo vcf generado con el marcador enmascarado ----

output_file <- "Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_5/Grup5.vcf"

# Se leen los nombres de los marcadores ----

marcadores <- readLines(marcadores_file)

# Se realiza el cambio en los genotipos de los individuos ----

vcf_data_5 <- vcf_data %>%
  mutate_at(vars(one_of(Grup_5)),
            ~ case_when(ID %in% marcadores ~ "./.",
                        TRUE ~ .))

vcf_data_5 %>% 
  filter(ID %in% c('Affx-113744580', 'Affx-113731463', 'BovineHD2700009653', 'Affx-106536391')) %>% 
  select(ES000806949713_ES000806949713, ES020807313517_ES020807313517, ES071007304834_ES071007304834, ES081003945863_ES081003945863) # Se realiza la prueba para ver por ejemplo si los marcadores se enmascaran. Los genotipos de estos individuos aparece como "./.", y antes en el objeto "vcf_data" si tenian genotipos.

# Se guarda el archivo VCF modificado ----

data.table::fwrite(vcf_data_4, output_file, sep = "\t", quote = FALSE)

#######################################
# Precisión en el grupo de validación 6
#######################################

# Se importan los individuos ----

Grup_6 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_6/Grup6.txt', col_names = FALSE, delim = ' ') |>
  mutate(ID_2 = X1) |>
  unite(
    col = ID,
    1:2,
    sep = '_'
    ) |>
  pull()

# Se indica la ruta de los archivos donde se guardará el archivo vcf generado con el marcador enmascarado ----

output_file <- "Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_6/Grup6.vcf"

# Se leen los nombres de los marcadores ----

marcadores <- readLines(marcadores_file)

# Se realiza el cambio en los genotipos de los individuos ----

vcf_data_6 <- vcf_data %>%
  mutate_at(vars(one_of(Grup_6)),
            ~ case_when(ID %in% marcadores ~ "./.",
                        TRUE ~ .))

vcf_data_6 %>% 
  filter(ID %in% c('Affx-113744580', 'Affx-113731463', 'BovineHD2700009653', 'Affx-106536391')) %>% 
  select(ES000807681669_ES000807681669, ES030806433297_ES030806433297, ES080805664791_ES080805664791, ES081004654536_ES081004654536) # Se realiza la prueba para ver por ejemplo si los marcadores se enmascaran. Los genotipos de estos individuos aparece como "./.", y antes en el objeto "vcf_data" si tenian genotipos.

# Se guarda el archivo VCF modificado ----

data.table::fwrite(vcf_data_6, output_file, sep = "\t", quote = FALSE)

#######################################
# Precisión en el grupo de validación 7
#######################################

# Se importan los individuos ----

Grup_7 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_7/Grup7.txt', col_names = FALSE, delim = ' ') |>
  mutate(ID_2 = X1) |>
  unite(
    col = ID,
    1:2,
    sep = '_'
    ) |>
  pull()

# Se indica la ruta de los archivos donde se guardará el archivo vcf generado con el marcador enmascarado ----

output_file <- "Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_7/Grup7.vcf"

# Se leen los nombres de los marcadores ----

marcadores <- readLines(marcadores_file)

# Se realiza el cambio en los genotipos de los individuos ----

vcf_data_7 <- vcf_data %>%
  mutate_at(vars(one_of(Grup_7)),
            ~ case_when(ID %in% marcadores ~ "./.",
                        TRUE ~ .))

vcf_data_7 %>% 
  filter(ID %in% c('Affx-113744580', 'Affx-113731463', 'BovineHD2700009653', 'Affx-106536391')) %>% 
  select(ES000809138043_ES000809138043, ES060804840737_ES060804840737, ES060812155123_ES060812155123, ES0MV791160000_ES0MV791160000) # Se realiza la prueba para ver por ejemplo si los marcadores se enmascaran. Los genotipos de estos individuos aparece como "./.", y antes en el objeto "vcf_data" si tenian genotipos.

# Se guarda el archivo VCF modificado ----

data.table::fwrite(vcf_data_7, output_file, sep = "\t", quote = FALSE)

#######################################
# Precisión en el grupo de validación 8
#######################################

# Se importan los individuos ----

Grup_8 <- read_delim(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_8/Grup8.txt', col_names = FALSE, delim = ' ') |>
  mutate(ID_2 = X1) |>
  unite(
    col = ID,
    1:2,
    sep = '_'
    ) |>
  pull()

# Se indica la ruta de los archivos donde se guardará el archivo vcf generado con el marcador enmascarado ----

output_file <- "Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Precision_KM_2/Prec_8/Grup8.vcf"

# Se leen los nombres de los marcadores ----

marcadores <- readLines(marcadores_file)

# Se realiza el cambio en los genotipos de los individuos ----

vcf_data_8 <- vcf_data %>%
  mutate_at(vars(one_of(Grup_8)),
            ~ case_when(ID %in% marcadores ~ "./.",
                        TRUE ~ .))

vcf_data_8 %>% 
  filter(ID %in% c('Affx-113744580', 'Affx-113731463', 'BovineHD2700009653', 'Affx-106536391')) %>% 
  select(ES000810941801_ES000810941801, ES010809139116_ES010809139116, ES030805511383_ES030805511383, ES090805511389_ES090805511389) # Se realiza la prueba para ver por ejemplo si los marcadores se enmascaran. Los genotipos de estos individuos aparece como "./.", y antes en el objeto "vcf_data" si tenian genotipos.

# Se guarda el archivo VCF modificado ----

data.table::fwrite(vcf_data_8, output_file, sep = "\t", quote = FALSE)
```
