---
title: "Parte 15: evaluación de la precisión de la imputación con AlphaImpute2 - Parte 1"
format: html
---

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(Siccuracy, tidyverse)
```

<!--
NOTA: Usando el archivo de genotipos generado en Parte-1.qmd, a continuación, se identifican los marcadores (en columnas) completamente genotipados (es decir, con genotipo en todos los individuos). Esto para asegurar que al momento de elegir al azar determinado número de individuos como muestra de validación, los marcadores que se van a enmascarar si hayan sido genotipados.
-->

```{r}
#| label: Identificación de marcadores completamente genotipados

# Se importa el archivo de genotipos y se asigna un nombre a las columnas ----

datGen <- read_delim(file = 'Imp_HD/Datos/AlphaImpute2/datGen.txt', col_names = FALSE, delim = ' ')

# Se extrae el nombre de los marcadores del archivo "Paso_14.bim" y luego se coloca el nombre de los marcadores como corresponde en cada columna ----

nomGen <- read_table(file = 'Imp_HD/Datos/datQC_2/Paso_14.bim', col_names = FALSE) |>
  pull(X2)

colnames(datGen) <- c('IID', paste0(nomGen))

# Se identifica a continuación que marcadores (en columnas) fueron completamente genotipados (sin valor faltante en la columna) ----

columnas_sin_9 <- datGen %>%
  select(-IID) %>%
  keep(~ all(.x != 9)) %>% # Se utiliza la función keep() del paquete purrr junto con el operador ~ para mantener solo las columnas en las que todos los valores sean diferentes de 9. El resultado se almacena en el objeto columnas_sin_9.
  names() # Luego se obtienen los nombres de las columnas utilizando la función names(). Son en total 472405 marcadores con genotipo en todos los individuos.
```

<!--
NOTA: A continuación, se genera una columna denominada "Grupos" que indicará los 4 grupos en los que los 284 individuos se dividiran de forma aleatoria y sin repetición, por lo que cada grupo estará formado por 71 individuos. Luego, los marcadores con genotipo anteriormente identificados se "enmascaran" en los individuos de cada grupo. Esto es, se hacen pasar como marcadores no genotipados o ausentes con valor de 9.
-->

```{r}
#| label: Creación de grupos de validación

# Se determina el número de individuos y grupos ----

num_individuos <- nrow(datGen)
num_grupos <- 4

# Se calcula el número de individuos en cada grupo ----

tamano <- ceiling(num_individuos / num_grupos) # Se indica aquí que el número de individuos en cada grupo es de 362.

# Se generan el vector de grupos ----

set.seed(123)  # Para garantizar la reproducibilidad de los resultados.

Grupos <- rep(x = 1:num_grupos, each = tamano)  # Se crea un vector con los valores de 1 a 8 repetidos 362 veces.

# Se asigna de forma aleatoria los grupos a la columna Grupos ----

datGen_2 <- datGen %>%
  mutate(Grupos = sample(Grupos))  # Se asigna de forma aleatoria los grupos a la columna Grupos.

table(datGen_2$Grupos) # Se verifica la repetición de los identificadores de grupo. Aquí, el grupo de validación 1 tendra 360 individuos, y el resto 362 individuos.

#################
# Base de datos 1
#################

# Se "enmascaran" los marcadores con genotipo en los individuos que hacen parte del grupo 1 ----

datGen_2 %>%
  relocate(Grupos, .after = IID) %>%
  mutate_at(
    .vars = columnas_sin_9,
    .funs = ~ case_when(
      Grupos == 1 ~ 9,
      TRUE ~ .x
      )
    ) %>% # Se utiliza la función mutate_at() para aplicar una transformación a las columnas especificadas en el objeto columnas_sin_9. La función .vars se utiliza para especificar las columnas a las que se desea aplicar la transformación. Luego, se utiliza .funs para especificar la operación que se realizará en las columnas seleccionadas. Dentro de mutate_at(), se utiliza case_when() para especificar la lógica de la transformación. La expresión Grupos == 1 ~ 9 indica que para los individuos cuyo grupo es igual a 1, se asignará el valor 9. En caso contrario, se mantendrá el valor original de la columna (.x).
  select(-Grupos) %>%
  write_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/Precision/Prec_1/datGen1.txt', col_names = FALSE, delim = ' ')

#################
# Base de datos 2
#################

# Se "enmascaran" los marcadores con genotipo en los individuos que hacen parte del grupo 2 ----

datGen_2 %>%
  relocate(Grupos, .after = IID) %>%
  mutate_at(
    .vars = columnas_sin_9,
    .funs = ~ case_when(
      Grupos == 2 ~ 9,
      TRUE ~ .x
      )
    ) %>% # Se utiliza la función mutate_at() para aplicar una transformación a las columnas especificadas en el objeto columnas_sin_9. La función .vars se utiliza para especificar las columnas a las que se desea aplicar la transformación. Luego, se utiliza .funs para especificar la operación que se realizará en las columnas seleccionadas. Dentro de mutate_at(), se utiliza case_when() para especificar la lógica de la transformación. La expresión Grupos == 1 ~ 9 indica que para los individuos cuyo grupo es igual a 1, se asignará el valor 9. En caso contrario, se mantendrá el valor original de la columna (.x).
  select(-Grupos) %>%
  write_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/Precision/Prec_2/datGen2.txt', col_names = FALSE, delim = ' ')

#################
# Base de datos 3
#################

# Se "enmascaran" los marcadores con genotipo en los individuos que hacen parte del grupo 3 ----

datGen_2 %>%
  relocate(Grupos, .after = IID) %>%
  mutate_at(
    .vars = columnas_sin_9,
    .funs = ~ case_when(
      Grupos == 3 ~ 9,
      TRUE ~ .x
      )
    ) %>% # Se utiliza la función mutate_at() para aplicar una transformación a las columnas especificadas en el objeto columnas_sin_9. La función .vars se utiliza para especificar las columnas a las que se desea aplicar la transformación. Luego, se utiliza .funs para especificar la operación que se realizará en las columnas seleccionadas. Dentro de mutate_at(), se utiliza case_when() para especificar la lógica de la transformación. La expresión Grupos == 1 ~ 9 indica que para los individuos cuyo grupo es igual a 1, se asignará el valor 9. En caso contrario, se mantendrá el valor original de la columna (.x).
  select(-Grupos) %>%
  write_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/Precision/Prec_3/datGen3.txt', col_names = FALSE, delim = ' ')

#################
# Base de datos 4
#################

# Se "enmascaran" los marcadores con genotipo en los individuos que hacen parte del grupo 4 ----

datGen_2 %>%
  relocate(Grupos, .after = IID) %>%
  mutate_at(
    .vars = columnas_sin_9,
    .funs = ~ case_when(
      Grupos == 4 ~ 9,
      TRUE ~ .x
      )
    ) %>% # Se utiliza la función mutate_at() para aplicar una transformación a las columnas especificadas en el objeto columnas_sin_9. La función .vars se utiliza para especificar las columnas a las que se desea aplicar la transformación. Luego, se utiliza .funs para especificar la operación que se realizará en las columnas seleccionadas. Dentro de mutate_at(), se utiliza case_when() para especificar la lógica de la transformación. La expresión Grupos == 1 ~ 9 indica que para los individuos cuyo grupo es igual a 1, se asignará el valor 9. En caso contrario, se mantendrá el valor original de la columna (.x).
  select(-Grupos) %>%
  write_delim(file = 'Imputacion/Imp_HD/Datos/AlphaImpute2/Precision/Prec_4/datGen4.txt', col_names = FALSE, delim = ' ')
```

<!--
NOTA: Se exporta el archivo de pedigrí para usar en la imputación.
-->

```{r}
#| label: Generación y exportación del archivo de pedigrí

datPed <- read_delim(file = 'Imputacion/Imp_HD/Datos/datQC_2/Paso_14.fam', delim = ' ', col_select = c(2:4), col_names = FALSE)

# A continuación, se exporta el archivo de pedirgí (datPed) a las distintas carpetas (Prec_1, Prec_2, ..., Prec_8) ----

directorio_base <- 'Imputacion/Imp_HD/Datos/AlphaImpute2/Precision/'

num_carpetas <- 4 # Se indica aqí el número de carpetas (8 en este caso).

# Se itera sobre las carpetas y se exportan los datos
for (i in 1:num_carpetas) {
  # Se construye la ruta de la carpeta actual
  carpeta_actual <- paste0(directorio_base, 'Prec_', i, '/')
  
  # Se exportan los datos a la carpeta actual
  ruta_archivo <- file.path(carpeta_actual, 'datPed.txt')
  write_delim(x = datPed, file = ruta_archivo, col_names = FALSE, delim = ' ')
  }
```

<!--
NOTA: Se realiza a continuación la imputación con AlphaImpute2, basado en el pedigrí.
-->

```{r}
#| label: Imputación basado en el pedigrí

# Definir la ruta de la carpeta principal
carpeta_principal <- "Imp_HD/Datos/AlphaImpute2/Precision"

# Definir los nombres de las subcarpetas y los archivos
subcarpetas <- c("Prec_1", "Prec_2", "Prec_3", "Prec_4")
archivos_genotipos <- paste0("datGen", 1:4)
archivo_pedigri <- "datPed.txt"

# Iterar sobre las subcarpetas y ejecutar AlphaImpute en cada una
for (i in seq_along(subcarpetas)) {
  # Construir las rutas completas de los archivos
  ruta_genotipos <- file.path(carpeta_principal, subcarpetas[i], paste0(archivos_genotipos[i], ".txt"))
  ruta_pedigri <- file.path(carpeta_principal, subcarpetas[i], archivo_pedigri)
  ruta_salida <- file.path(carpeta_principal, subcarpetas[i], "Resultado1")

  # Ejecutar AlphaImpute para la subcarpeta actual
  comando <- paste("AlphaImpute2 -genotypes", ruta_genotipos,
                   "-pedigree", ruta_pedigri,
                   "-ped_only -phase_output -cycles 5 -out", ruta_salida)

  system(comando)
  }
```

<!--
NOTA: Se realiza a continuación la imputación con AlphaImpute 2, basado en la población.
-->

```{r}
#| label: Imputación basado en la población

# Definir la ruta de la carpeta principal
carpeta_principal <- "../Datos/AlphaImpute2/Precision"

# Definir los nombres de las subcarpetas y los archivos
subcarpetas <- c("Prec_1", "Prec_2", "Prec_3", "Prec_4")
archivos_genotipos <- paste0("datGen", 1:4)
archivo_pedigri <- "datPed.txt"

# Iterar sobre las subcarpetas y ejecutar AlphaImpute en cada una
for (i in seq_along(subcarpetas)) {
  # Construir las rutas completas de los archivos
  ruta_genotipos <- file.path(carpeta_principal, subcarpetas[i], paste0(archivos_genotipos[i], ".txt"))
  ruta_pedigri <- file.path(carpeta_principal, subcarpetas[i], archivo_pedigri)
  ruta_salida <- file.path(carpeta_principal, subcarpetas[i], "Resultado2")

  # Ejecutar AlphaImpute para la subcarpeta actual
  comando <- paste("AlphaImpute2 -genotypes", ruta_genotipos,
                   "-pedigree", ruta_pedigri,
                   "-pop_only -phase_output -n_phasing_cycles 5 -out", ruta_salida)

  system(comando)
  }
```

<!--
NOTA: Se realiza a continuación la imputación con AlphaImpute 2, basado en el pedigrí y en la población (imputación conjunta).
-->

```{r}
#| label: Imputación conjunta

# Definir la ruta de la carpeta principal
carpeta_principal <- "../Datos/AlphaImpute2/Precision"

# Definir los nombres de las subcarpetas y los archivos
subcarpetas <- c("Prec_1", "Prec_2", "Prec_3", "Prec_4")
archivos_genotipos <- paste0("datGen", 1:4)
archivo_pedigri <- "datPed.txt"

# Iterar sobre las subcarpetas y ejecutar AlphaImpute en cada una
for (i in seq_along(subcarpetas)) {
  # Construir las rutas completas de los archivos
  ruta_genotipos <- file.path(carpeta_principal, subcarpetas[i], paste0(archivos_genotipos[i], ".txt"))
  ruta_pedigri <- file.path(carpeta_principal, subcarpetas[i], archivo_pedigri)
  ruta_salida <- file.path(carpeta_principal, subcarpetas[i], "Resultado3")

  # Ejecutar AlphaImpute para la subcarpeta actual
  comando <- paste("AlphaImpute2 -genotypes", ruta_genotipos,
                   "-pedigree", ruta_pedigri,
                   "-phase_output -out", ruta_salida)

  system(comando)
  }
```
