---
title: "Parte 10: Hola"
format: html
---

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(tidyverse, patchwork)
```

<!--
NOTA: Hola
-->

```{r}
#| label: Hola

# Con la siguiente función se creara la visualización de las trazas para mirar la convergencia según el burn-in indicado al hacer el postgibbs ----

create_plot <- function(data, componente, color) {
  data |>
    select(-c(1, 3)) |>
    rename(
      'Muestra' = X2,
      'Varianza para el efecto del grupo de comparación' = X4,
      'Varianza para el efecto del toro' = X5,
      'Varianza para el efecto del individuo' = X6,
      'Residuo' = X7
      ) |>
    pivot_longer(
      cols = c(2:5),
      names_to = 'Componentes de varianza',
      values_to = 'Estima'
      ) |>
    filter(`Componentes de varianza` == componente) |>
    ggplot(aes(x = Muestra, y = Estima)) +
    geom_line(alpha = 0.4, linewidth = 0.4, colour = color) +
    labs(x = 'Número de iteraciones', y = '', title = componente) +
    theme_bw() +
    theme(
      axis.text = element_text(size = 10, face = 'bold'),
      axis.title = element_text(size = 10, face = 'bold'),
      legend.position = 'none'
    )
  }

##########################
# Con burn-in igual a cero
##########################

burnin_1 <- read_table(file = 'eva_genetica/Datos/eva_genomica/Beagle_50K/Edad_Primer_Parto/Completo/postgibbs_1/postgibbs_samples', col_names = FALSE) # Se importa el archivo "postgibbs_samples", el cual es un archivo de texto que contiene las muestras del muesreo de Gibbs hecho con gibbsf90+. Cada columna representa lo siguiente:
#
# Columna 1: Indica el orden secuencial en el que la muestra se guardo luego del proceso de quema (burn-in) y adelgazamiento (thinning).
#
# Columna 2: Indica el número de la muestra en la cadena (en este caso, de 10 mil en adelante, después del burn-in, guarda una de cada 50 veces).
#
# Columna 3: Especifica la cantidad de parámetros para los cuales se guardó la muestra. En este caso 4, lo que sugiere que se estan estimando cuatro parámetros en el modelo (varianzas para los efectos del grupo de comparación, del toro, del individuo y el residuo, respectivamente).
#
# Columnas 4, 5, 6 y 7: Indican los componentes de varianza para los efectos del grupo de comparación, del toro, del individuo y el residuo, respectivamente. Esto se puede observar también en el archivo "postind".

# Se aplica la función al inicio de este fragmento para crear cada visualización de acuerdo al efecto considerado ----

efecto_1 <- create_plot(burnin_1, 'Varianza para el efecto del grupo de comparación', 'cyan')
efecto_2 <- create_plot(burnin_1, 'Varianza para el efecto del toro', 'orange')
efecto_3 <- create_plot(burnin_1, 'Varianza para el efecto del individuo', 'black')
efecto_4 <- create_plot(burnin_1, 'Residuo', 'green')

# Se unen las visualizaciones anteriores usando el paquete "patchwork" ----

(guide_area()/((efecto_1 / efecto_2) | (efecto_3 / efecto_4))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 0') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/Edad_Primer_Parto/Completo/Imagenes/burnin_cero.pdf', width = 40, height = 20, units = 'cm')

###########################
# Con burn-in igual a 5 mil
###########################

burnin_2 <- read_table(file = 'eva_genetica/Datos/eva_genomica/Beagle_50K/Edad_Primer_Parto/Completo/postgibbs_2/postgibbs_samples', col_names = FALSE)

# Se aplica la función al inicio de este fragmento para crear cada visualización de acuerdo al efecto considerado ----

efecto_1 <- create_plot(burnin_2, 'Varianza para el efecto del grupo de comparación', 'cyan')
efecto_2 <- create_plot(burnin_2, 'Varianza para el efecto del toro', 'orange')
efecto_3 <- create_plot(burnin_2, 'Varianza para el efecto del individuo', 'black')
efecto_4 <- create_plot(burnin_2, 'Residuo', 'green')

# Se unen las visualizaciones anteriores usando el paquete "patchwork" ----

(guide_area()/((efecto_1 / efecto_2) | (efecto_3 / efecto_4))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 5 mil') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/Edad_Primer_Parto/Completo/Imagenes/burnin_cincomil.pdf', width = 40, height = 20, units = 'cm')

############################
# Con burn-in igual a 10 mil
############################

burnin_3 <- read_table(file = 'eva_genetica/Datos/eva_genomica/Beagle_50K/Edad_Primer_Parto/Completo/postgibbs_3/postgibbs_samples', col_names = FALSE)

# Se aplica la función al inicio de este fragmento para crear cada visualización de acuerdo al efecto considerado ----

efecto_1 <- create_plot(burnin_3, 'Varianza para el efecto del grupo de comparación', 'cyan')
efecto_2 <- create_plot(burnin_3, 'Varianza para el efecto del toro', 'orange')
efecto_3 <- create_plot(burnin_3, 'Varianza para el efecto del individuo', 'black')
efecto_4 <- create_plot(burnin_3, 'Residuo', 'green')

# Se unen las visualizaciones anteriores usando el paquete "patchwork" ----

(guide_area()/((efecto_1 / efecto_2) | (efecto_3 / efecto_4))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 10 mil') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/Edad_Primer_Parto/Completo/Imagenes/burnin_diezmil.pdf', width = 40, height = 20, units = 'cm')

# Se realiza un gráfica para visualizar las varianzas y la heredabilidad ----

heredabilidad <- burnin_3 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del grupo de comparación' = X4,
    'Varianza para el efecto del toro' = X5,
    'Varianza para el efecto del individuo' = X6,
    'Residuo' = X7
    ) |>
  mutate(heredabilidad = `Varianza para el efecto del individuo` / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo))

graf_varGC <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del grupo de comparación`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'cyan', fill = 'cyan', alpha = 0.2) +
  annotate(
    'text', x = 5800, y = 0.0020,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del grupo de comparación`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del grupo de comparación') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varT <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del toro`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2) +
  annotate(
    'text', x = 4500, y = 0.0015,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del toro`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del toro') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varG <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del individuo`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2) +
  annotate(
    'text', x = 2400, y = 0.0020,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del individuo`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza genética aditiva') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varE <- heredabilidad |>
  ggplot(aes(x = Residuo)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2) +
  annotate(
    'text', x = 11225, y = 0.002,
    label = paste('Valor medio = ', round(mean(heredabilidad$Residuo), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza residual') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_heredabilidad <- heredabilidad |>
  ggplot(aes(x = heredabilidad)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2)  +
  annotate(
    'text', x = 0.078, y = 50,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad), digits = 2)), size = 3.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

(guide_area()/(((graf_varGC | graf_varG) / (graf_varT | graf_varE)) | (graf_heredabilidad))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Parámetros para la edad al primer parto') & 
  theme(plot.title = element_text(size = 9.4, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/Edad_Primer_Parto/Completo/Imagenes/Heredabilidad.pdf', width = 40, height = 20, units = 'cm')
```

<!--
NOTA: Hola
-->

```{r}
#| label: Hola

# Con la siguiente función se creara la visualización de las trazas para mirar la convergencia según el burn-in indicado al hacer el postgibbs ----

create_plot <- function(data, componente, color) {
  data |>
    select(-c(1, 3)) |>
    rename(
      'Muestra' = X2,
      'Varianza para el efecto del grupo de comparación' = X4,
      'Varianza para el efecto del toro' = X5,
      'Varianza para el efecto del individuo' = X6,
      'Residuo' = X7
      ) |>
    pivot_longer(
      cols = c(2:5),
      names_to = 'Componentes de varianza',
      values_to = 'Estima'
      ) |>
    filter(`Componentes de varianza` == componente) |>
    ggplot(aes(x = Muestra, y = Estima)) +
    geom_line(alpha = 0.4, linewidth = 0.4, colour = color) +
    labs(x = 'Número de iteraciones', y = '', title = componente) +
    theme_bw() +
    theme(
      axis.text = element_text(size = 10, face = 'bold'),
      axis.title = element_text(size = 10, face = 'bold'),
      legend.position = 'none'
    )
  }

##########################
# Con burn-in igual a cero
##########################

burnin_1 <- read_table(file = 'eva_genetica/Datos/eva_genomica/Beagle_50K/intervalo_P1_P2/Completo/postgibbs_1/postgibbs_samples', col_names = FALSE)

# Se aplica la función al inicio de este fragmento para crear cada visualización de acuerdo al efecto considerado ----

efecto_1 <- create_plot(burnin_1, 'Varianza para el efecto del grupo de comparación', 'cyan')
efecto_2 <- create_plot(burnin_1, 'Varianza para el efecto del toro', 'orange')
efecto_3 <- create_plot(burnin_1, 'Varianza para el efecto del individuo', 'black')
efecto_4 <- create_plot(burnin_1, 'Residuo', 'green')

# Se unen las visualizaciones anteriores usando el paquete "patchwork" ----

(guide_area()/((efecto_1 / efecto_2) | (efecto_3 / efecto_4))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 0') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/intervalo_P1_P2/Completo/Imagenes/burnin_cero.pdf', width = 40, height = 20, units = 'cm')

###########################
# Con burn-in igual a 5 mil
###########################

burnin_2 <- read_table(file = 'eva_genetica/Datos/eva_genomica/Beagle_50K/intervalo_P1_P2/Completo/postgibbs_2/postgibbs_samples', col_names = FALSE)

# Se aplica la función al inicio de este fragmento para crear cada visualización de acuerdo al efecto considerado ----

efecto_1 <- create_plot(burnin_2, 'Varianza para el efecto del grupo de comparación', 'cyan')
efecto_2 <- create_plot(burnin_2, 'Varianza para el efecto del toro', 'orange')
efecto_3 <- create_plot(burnin_2, 'Varianza para el efecto del individuo', 'black')
efecto_4 <- create_plot(burnin_2, 'Residuo', 'green')

# Se unen las visualizaciones anteriores usando el paquete "patchwork" ----

(guide_area()/((efecto_1 / efecto_2) | (efecto_3 / efecto_4))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 5 mil') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/intervalo_P1_P2/Completo/Imagenes/burnin_cincomil.pdf', width = 40, height = 20, units = 'cm')

############################
# Con burn-in igual a 10 mil
############################

burnin_3 <- read_table(file = 'eva_genetica/Datos/eva_genomica/Beagle_50K/intervalo_P1_P2/Completo/postgibbs_3/postgibbs_samples', col_names = FALSE)

# Se aplica la función al inicio de este fragmento para crear cada visualización de acuerdo al efecto considerado ----

efecto_1 <- create_plot(burnin_3, 'Varianza para el efecto del grupo de comparación', 'cyan')
efecto_2 <- create_plot(burnin_3, 'Varianza para el efecto del toro', 'orange')
efecto_3 <- create_plot(burnin_3, 'Varianza para el efecto del individuo', 'black')
efecto_4 <- create_plot(burnin_3, 'Residuo', 'green')

# Se unen las visualizaciones anteriores usando el paquete "patchwork" ----

(guide_area()/((efecto_1 / efecto_2) | (efecto_3 / efecto_4))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 10 mil') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/intervalo_P1_P2/Completo/Imagenes/burnin_diezmil.pdf', width = 40, height = 20, units = 'cm')
```

<!--
NOTA: Hola
-->

```{r}
#| label: Hola

# Con la siguiente función se creara la visualización de las trazas para mirar la convergencia según el burn-in indicado al hacer el postgibbs ----

create_plot <- function(data, componente, color) {
  data |>
    select(-c(1, 3)) |>
    rename(
      'Muestra' = X2,
      'Varianza para el efecto directo (o del individuo)' = X4,
      'Covarianza entre efecto directo y materno' = X5,
      'Varianza para el efecto materno' = X6,
      'Varianza para el efecto permanente materno' = X7,
      'Residuo' = X8
      ) |>
    pivot_longer(
      cols = c(2:6),
      names_to = 'Componentes de varianza',
      values_to = 'Estima'
      ) |>
    filter(`Componentes de varianza` == componente) |>
    ggplot(aes(x = Muestra, y = Estima)) +
    geom_line(alpha = 0.4, linewidth = 0.4, colour = color) +
    labs(x = 'Número de iteraciones', y = '', title = componente) +
    theme_bw() +
    theme(
      axis.text = element_text(size = 10, face = 'bold'),
      axis.title = element_text(size = 10, face = 'bold'),
      legend.position = 'none'
    )
  }

##########################
# Con burn-in igual a cero
##########################

burnin_1 <- read_table(file = 'eva_genetica/Datos/eva_genomica/Beagle_50K/peso_Dtte/Completo/postgibbs_1/postgibbs_samples', col_names = FALSE)

# Se aplica la función al inicio de este fragmento para crear cada visualización de acuerdo al efecto considerado ----

efecto_1 <- create_plot(burnin_1, 'Varianza para el efecto directo (o del individuo)', 'cyan')
efecto_2 <- create_plot(burnin_1, 'Covarianza entre efecto directo y materno', 'orange')
efecto_3 <- create_plot(burnin_1, 'Varianza para el efecto materno', 'black')
efecto_4 <- create_plot(burnin_1, 'Varianza para el efecto permanente materno', 'green')
efecto_5 <- create_plot(burnin_1, 'Residuo', 'brown')

# Se unen las visualizaciones anteriores usando el paquete "patchwork" ----

(guide_area()/(((efecto_1 / efecto_3) | (efecto_2)) / (efecto_4 | efecto_5))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 0') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/peso_Dtte/Completo/Imagenes/burnin_cero.pdf', width = 40, height = 20, units = 'cm')

###########################
# Con burn-in igual a 5 mil
###########################

burnin_2 <- read_table(file = 'eva_genetica/Datos/eva_genomica/Beagle_50K/peso_Dtte/Completo/postgibbs_2/postgibbs_samples', col_names = FALSE)

# Se aplica la función al inicio de este fragmento para crear cada visualización de acuerdo al efecto considerado ----

efecto_1 <- create_plot(burnin_1, 'Varianza para el efecto directo (o del individuo)', 'cyan')
efecto_2 <- create_plot(burnin_1, 'Covarianza entre efecto directo y materno', 'orange')
efecto_3 <- create_plot(burnin_1, 'Varianza para el efecto materno', 'black')
efecto_4 <- create_plot(burnin_1, 'Varianza para el efecto permanente materno', 'green')
efecto_5 <- create_plot(burnin_1, 'Residuo', 'brown')

# Se unen las visualizaciones anteriores usando el paquete "patchwork" ----

(guide_area()/(((efecto_1 / efecto_3) | (efecto_2)) / (efecto_4 | efecto_5))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 5 mil') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/peso_Dtte/Completo/Imagenes/burnin_cincomil.pdf', width = 40, height = 20, units = 'cm')

############################
# Con burn-in igual a 10 mil
############################

burnin_3 <- read_table(file = 'eva_genetica/Datos/eva_genomica/Beagle_50K/peso_Dtte/Completo/postgibbs_3/postgibbs_samples', col_names = FALSE)

# Se aplica la función al inicio de este fragmento para crear cada visualización de acuerdo al efecto considerado ----

efecto_1 <- create_plot(burnin_1, 'Varianza para el efecto directo (o del individuo)', 'cyan')
efecto_2 <- create_plot(burnin_1, 'Covarianza entre efecto directo y materno', 'orange')
efecto_3 <- create_plot(burnin_1, 'Varianza para el efecto materno', 'black')
efecto_4 <- create_plot(burnin_1, 'Varianza para el efecto permanente materno', 'green')
efecto_5 <- create_plot(burnin_1, 'Residuo', 'brown')

# Se unen las visualizaciones anteriores usando el paquete "patchwork" ----

(guide_area()/(((efecto_1 / efecto_3) | (efecto_2)) / (efecto_4 | efecto_5))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 10 mil') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/peso_Dtte/Completo/Imagenes/burnin_diezmil.pdf', width = 40, height = 20, units = 'cm')
```

<!--
NOTA: Hola
-->

```{r}
#| label: Hola

# Con la siguiente función se creara la visualización de las trazas para mirar la convergencia según el burn-in indicado al hacer el postgibbs ----

create_plot <- function(data, componente, color) {
  data |>
    select(-c(1, 3)) |>
    rename(
      'Muestra' = X2,
      'Varianza para el efecto del grupo de comparación - EPP' = X4,
      'Varianza para el efecto del toro - EPP' = X5,
      'Varianza para el efecto del grupo de comparación - I_P1-P2' = X6,
      'Varianza para el efecto del toro - I_P1-P2' = X7,
      'Varianza para el efecto del individuo - EPP' = X8,
      'Covarianza entre efectos geneticos - EPP e I_P1-P2' = X9,
      'Varianza para el efecto del individuo - I_P1-P2' = X10,
      'Residuo - EPP' = X11,
      'Covarianza residual - EPP e I_P1-P2' = X12,
      'Residuo - I_P1-P2' = X13
      ) |>
    pivot_longer(
      cols = c(2:11),
      names_to = 'Componentes de varianza',
      values_to = 'Estima'
      ) |>
    filter(`Componentes de varianza` == componente) |>
    ggplot(aes(x = Muestra, y = Estima)) +
    geom_line(alpha = 0.4, linewidth = 0.4, colour = color) +
    labs(x = 'Número de iteraciones', y = '', title = componente) +
    theme_bw() +
    theme(
      axis.text = element_text(size = 10, face = 'bold'),
      axis.title = element_text(size = 10, face = 'bold'),
      legend.position = 'none'
    )
  }

##########################
# Con burn-in igual a cero
##########################

burnin_1 <- read_table(file = 'eva_genetica/Datos/eva_genomica/Beagle_50K/EPP_IEP/Completo/postgibbs_1/postgibbs_samples', col_names = FALSE)

efecto_1 <- create_plot(burnin_1, 'Varianza para el efecto del grupo de comparación - EPP', 'cyan')
efecto_2 <- create_plot(burnin_1, 'Varianza para el efecto del toro - EPP', 'orange')
efecto_3 <- create_plot(burnin_1, 'Varianza para el efecto del grupo de comparación - I_P1-P2', 'cyan')
efecto_4 <- create_plot(burnin_1, 'Varianza para el efecto del toro - I_P1-P2', 'orange')
efecto_5 <- create_plot(burnin_1, 'Varianza para el efecto del individuo - EPP', 'green')
efecto_6 <- create_plot(burnin_1, 'Covarianza entre efectos geneticos - EPP e I_P1-P2', 'black')
efecto_7 <- create_plot(burnin_1, 'Varianza para el efecto del individuo - I_P1-P2', 'green')
efecto_8 <- create_plot(burnin_1, 'Residuo - EPP', 'green')
efecto_9 <- create_plot(burnin_1, 'Covarianza residual - EPP e I_P1-P2', 'black')
efecto_10 <- create_plot(burnin_1, 'Residuo - I_P1-P2', 'green')

# Se unen las visualizaciones anteriores usando el paquete "patchwork" ----

(guide_area()/((efecto_1 | efecto_2) / (efecto_3 | efecto_4) / ((efecto_5 / efecto_7) | efecto_6) / ((efecto_8 / efecto_10) | efecto_9))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 0') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/EPP_IEP/Completo/Imagenes/burnin_cero.pdf', width = 40, height = 20, units = 'cm')

(guide_area()/((efecto_1 | efecto_2) / (efecto_3 | efecto_4))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 0') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/EPP_IEP/Completo/Imagenes/burnin_cero_toro_GC.pdf', width = 40, height = 20, units = 'cm')

(guide_area()/((efecto_5 / efecto_7) | (efecto_6)) / ((efecto_8 / efecto_10) | (efecto_9))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1, 0.1), c('cm', 'null', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 0') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/EPP_IEP/Completo/Imagenes/burnin_cero_indivdiuo_residuo.pdf', width = 40, height = 20, units = 'cm')

###########################
# Con burn-in igual a 5 mil
###########################

burnin_2 <- read_table(file = 'eva_genetica/Datos/eva_genomica/Beagle_50K/EPP_IEP/Completo/postgibbs_2/postgibbs_samples', col_names = FALSE)

efecto_1 <- create_plot(burnin_2, 'Varianza para el efecto del grupo de comparación - EPP', 'cyan')
efecto_2 <- create_plot(burnin_2, 'Varianza para el efecto del toro - EPP', 'orange')
efecto_3 <- create_plot(burnin_2, 'Varianza para el efecto del grupo de comparación - I_P1-P2', 'cyan')
efecto_4 <- create_plot(burnin_2, 'Varianza para el efecto del toro - I_P1-P2', 'orange')
efecto_5 <- create_plot(burnin_2, 'Varianza para el efecto del individuo - EPP', 'green')
efecto_6 <- create_plot(burnin_2, 'Covarianza entre efectos geneticos - EPP e I_P1-P2', 'black')
efecto_7 <- create_plot(burnin_2, 'Varianza para el efecto del individuo - I_P1-P2', 'green')
efecto_8 <- create_plot(burnin_2, 'Residuo - EPP', 'green')
efecto_9 <- create_plot(burnin_2, 'Covarianza residual - EPP e I_P1-P2', 'black')
efecto_10 <- create_plot(burnin_2, 'Residuo - I_P1-P2', 'green')

# Se unen las visualizaciones anteriores usando el paquete "patchwork" ----

(guide_area()/((efecto_1 | efecto_2) / (efecto_3 | efecto_4))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 5 mil') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/EPP_IEP/Completo/Imagenes/burnin_cincomil_toro_GC.pdf', width = 40, height = 20, units = 'cm')

(guide_area()/((efecto_5 / efecto_7) | (efecto_6)) / ((efecto_8 / efecto_10) | (efecto_9))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1, 0.1), c('cm', 'null', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 5 mil') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/EPP_IEP/Completo/Imagenes/burnin_cincomil_indivdiuo_residuo.pdf', width = 40, height = 20, units = 'cm')

############################
# Con burn-in igual a 10 mil
############################

burnin_3 <- read_table(file = 'eva_genetica/Datos/eva_genomica/Beagle_50K/EPP_IEP/Completo/postgibbs_3/postgibbs_samples', col_names = FALSE)

efecto_1 <- create_plot(burnin_3, 'Varianza para el efecto del grupo de comparación - EPP', 'cyan')
efecto_2 <- create_plot(burnin_3, 'Varianza para el efecto del toro - EPP', 'orange')
efecto_3 <- create_plot(burnin_3, 'Varianza para el efecto del grupo de comparación - I_P1-P2', 'cyan')
efecto_4 <- create_plot(burnin_3, 'Varianza para el efecto del toro - I_P1-P2', 'orange')
efecto_5 <- create_plot(burnin_3, 'Varianza para el efecto del individuo - EPP', 'green')
efecto_6 <- create_plot(burnin_3, 'Covarianza entre efectos geneticos - EPP e I_P1-P2', 'black')
efecto_7 <- create_plot(burnin_3, 'Varianza para el efecto del individuo - I_P1-P2', 'green')
efecto_8 <- create_plot(burnin_3, 'Residuo - EPP', 'green')
efecto_9 <- create_plot(burnin_3, 'Covarianza residual - EPP e I_P1-P2', 'black')
efecto_10 <- create_plot(burnin_3, 'Residuo - I_P1-P2', 'green')

# Se unen las visualizaciones anteriores usando el paquete "patchwork" ----

(guide_area()/((efecto_1 | efecto_2) / (efecto_3 | efecto_4))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 10 mil') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/EPP_IEP/Completo/Imagenes/burnin_diezmil_toro_GC.pdf', width = 40, height = 20, units = 'cm')

(guide_area()/((efecto_5 / efecto_7) | (efecto_6)) / ((efecto_8 / efecto_10) | (efecto_9))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1, 0.1), c('cm', 'null', 'null'))) + 
  plot_annotation(title = 'Traza - burn-in de 10 mil') & 
  theme(plot.title = element_text(size = 10, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/Beagle_50K/EPP_IEP/Completo/Imagenes/burnin_diezmil_indivdiuo_residuo.pdf', width = 40, height = 20, units = 'cm')
```
