---
title: "Parte 13: Visualización de resultados del gibbs en datos completos y parciales en el genotipado proporcionado por SNP-tags y singletones"
format: html
---

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(tidyverse, patchwork)
```

<!--
NOTA: Para el caracter "edad al primer parto" se realiza la visualización de las trazas de convergencia, los parámetros genéticos (varianzas y heredabilidad) y .
-->

```{r}
#| label: Resultados del postgibbs para la edad al primer parto

# Con la siguiente función se creara la visualización de las trazas para mirar la convergencia según el burn-in indicado al hacer el postgibbs ----

create_plot <- function(data, componente, color) {
  data |>
    select(-c(1, 3)) |>
    rename(
      'Muestra' = X2,
      'Varianza para el efecto del grupo de comparación' = X4,
      'Varianza para el efecto del toro' = X5,
      'Varianza para el efecto del individuo' = X6,
      'Residuo' = X7
      ) |>
    pivot_longer(
      cols = c(2:5),
      names_to = 'Componentes de varianza',
      values_to = 'Estima'
      ) |>
    filter(`Componentes de varianza` == componente) |>
    ggplot(aes(x = Muestra, y = Estima)) +
    geom_line(alpha = 0.4, linewidth = 0.4, colour = color) +
    labs(x = 'Número de iteraciones', y = '', title = componente) +
    theme_bw() +
    theme(
      plot.title = element_text(size = 10, face = 'bold'),
      axis.text = element_text(size = 10, face = 'bold'),
      axis.title = element_text(size = 10, face = 'bold'),
      legend.position = 'none'
    )
  }

###############################
# 1. Conjunto de datos completo
###############################

##########################
# Con burn-in igual a cero
##########################

burnin_1 <- read_table(file = 'Datos/eva_genomica/SNP_tags_sing/Edad_Primer_Parto/Completo/postgibbs_1/postgibbs_samples', col_names = FALSE) # Se importa el archivo "postgibbs_samples", el cual es un archivo de texto que contiene las muestras del muesreo de Gibbs hecho con gibbsf90+. Cada columna representa lo siguiente:
#
# Columna 1: Indica el orden secuencial en el que la muestra se guardo luego del proceso de quema (burn-in) y adelgazamiento (thinning).
#
# Columna 2: Indica el número de la muestra en la cadena (en este caso, de 10 mil en adelante, después del burn-in, guarda una de cada 50 veces).
#
# Columna 3: Especifica la cantidad de parámetros para los cuales se guardó la muestra. En este caso 4, lo que sugiere que se estan estimando cuatro parámetros en el modelo (varianzas para los efectos del grupo de comparación, del toro, del individuo y el residuo, respectivamente).
#
# Columnas 4, 5, 6 y 7: Indican los componentes de varianza para los efectos del grupo de comparación, del toro, del individuo y el residuo, respectivamente. Esto se puede observar también en el archivo "postind".

# Se aplica la función al inicio de este fragmento para crear cada visualización de acuerdo al efecto considerado ----

create_plot(burnin_1, 'Varianza para el efecto del grupo de comparación', 'cyan')

ggsave('Datos/eva_genomica/SNP_tags_sing/Edad_Primer_Parto/Completo/Imagenes/burnin_cero/varGC.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Varianza para el efecto del toro', 'orange')

ggsave('Datos/eva_genomica/SNP_tags_sing/Edad_Primer_Parto/Completo/Imagenes/burnin_cero/varT.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Varianza para el efecto del individuo', 'black')

ggsave('Datos/eva_genomica/SNP_tags_sing/Edad_Primer_Parto/Completo/Imagenes/burnin_cero/varG.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Residuo', 'green')

ggsave('Datos/eva_genomica/SNP_tags_sing/Edad_Primer_Parto/Completo/Imagenes/burnin_cero/varR.pdf', width = 40, height = 20, units = 'cm')

# Se realiza una gráfica para visualizar las varianzas y la heredabilidad, a partir del postgibbs con burn-in de 0 (burnin_1) ----

heredabilidad <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del grupo de comparación' = X4,
    'Varianza para el efecto del toro' = X5,
    'Varianza para el efecto del individuo' = X6,
    'Residuo' = X7
    ) |>
  mutate(
    heredabilidad = `Varianza para el efecto del individuo` / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_grup_comp = (`Varianza para el efecto del grupo de comparación`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_toro = (`Varianza para el efecto del toro`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo)
    )

graf_varGC <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del grupo de comparación`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'cyan', fill = 'cyan', alpha = 0.2) +
  annotate(
    'text', x = 5800, y = 0.0020,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del grupo de comparación`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del grupo de comparación') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varT <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del toro`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2) +
  annotate(
    'text', x = 4500, y = 0.0015,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del toro`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del toro') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varG <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del individuo`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2) +
  annotate(
    'text', x = 2400, y = 0.0020,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del individuo`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza genética aditiva') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varE <- heredabilidad |>
  ggplot(aes(x = Residuo)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2) +
  annotate(
    'text', x = 11225, y = 0.002,
    label = paste('Valor medio = ', round(mean(heredabilidad$Residuo), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza residual') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_grup_comp <- heredabilidad |>
  ggplot(aes(x = proporcion_var_grup_comp)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(
    'text', x = 0.26, y = 40,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_grup_comp), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del grupo de comparación') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_toro <- heredabilidad |>
  ggplot(aes(x = proporcion_var_toro)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'gray', fill = 'gray', alpha = 0.2) +
  annotate(
    'text', x = 0.19, y = 40,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_toro), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del toro') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_heredabilidad <- heredabilidad |>
  ggplot(aes(x = heredabilidad)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2)  +
  annotate(
    'text', x = 0.078, y = 50,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad), digits = 2)), size = 3.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

(guide_area()/(((graf_varGC | graf_varG) / (graf_varT | graf_varE) / (graf_prop_grup_comp | graf_prop_toro)) | (graf_heredabilidad))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Parámetros para la edad al primer parto') & 
  theme(plot.title = element_text(size = 9.4, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/SNP_tags_sing/Edad_Primer_Parto/Completo/Imagenes/burnin_diezmil/Heredabilidad.pdf', width = 40, height = 20, units = 'cm')

# Se calcula el intervalo de densidad posterior más alto al 95% (HPD95%) ----

HPD_result <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del grupo de comparación' = X4,
    'Varianza para el efecto del toro' = X5,
    'Varianza para el efecto del individuo' = X6,
    'Residuo' = X7
    ) |>
  mutate(
    heredabilidad = `Varianza para el efecto del individuo` / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_grup_comp = (`Varianza para el efecto del grupo de comparación`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_toro = (`Varianza para el efecto del toro`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo)
    )

HDInterval::hdi(object = HPD_result$heredabilidad, credMass = 0.95) # El intervalo es de [0.076, 0.106]

##############################
# 2. Conjunto de datos parcial
##############################

##########################
# Con burn-in igual a cero
##########################

burnin_1 <- read_table(file = 'Datos/eva_genomica/SNP_tags_sing/Edad_Primer_Parto/Parcial/postgibbs_1/postgibbs_samples', col_names = FALSE)

# Se realiza una gráfica para visualizar las varianzas y la heredabilidad, a partir del postgibbs con burn-in de 0 (burnin_1) ----

heredabilidad <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del grupo de comparación' = X4,
    'Varianza para el efecto del toro' = X5,
    'Varianza para el efecto del individuo' = X6,
    'Residuo' = X7
    ) |>
  mutate(
    heredabilidad = `Varianza para el efecto del individuo` / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_grup_comp = (`Varianza para el efecto del grupo de comparación`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_toro = (`Varianza para el efecto del toro`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo)
    )

graf_varGC <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del grupo de comparación`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'cyan', fill = 'cyan', alpha = 0.2) +
  annotate(
    'text', x = 5800, y = 0.0020,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del grupo de comparación`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del grupo de comparación') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varT <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del toro`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2) +
  annotate(
    'text', x = 4500, y = 0.0015,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del toro`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del toro') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varG <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del individuo`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2) +
  annotate(
    'text', x = 2400, y = 0.0020,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del individuo`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza genética aditiva') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varE <- heredabilidad |>
  ggplot(aes(x = Residuo)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2) +
  annotate(
    'text', x = 11225, y = 0.002,
    label = paste('Valor medio = ', round(mean(heredabilidad$Residuo), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza residual') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_grup_comp <- heredabilidad |>
  ggplot(aes(x = proporcion_var_grup_comp)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(
    'text', x = 0.26, y = 40,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_grup_comp), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del grupo de comparación') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_toro <- heredabilidad |>
  ggplot(aes(x = proporcion_var_toro)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'gray', fill = 'gray', alpha = 0.2) +
  annotate(
    'text', x = 0.19, y = 40,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_toro), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del toro') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_heredabilidad <- heredabilidad |>
  ggplot(aes(x = heredabilidad)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2)  +
  annotate(
    'text', x = 0.078, y = 50,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad), digits = 2)), size = 3.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

(guide_area()/(((graf_varGC | graf_varG) / (graf_varT | graf_varE) / (graf_prop_grup_comp | graf_prop_toro)) | (graf_heredabilidad))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Parámetros para la edad al primer parto') & 
  theme(plot.title = element_text(size = 9.4, face = 'bold'))

# Se calcula el intervalo de densidad posterior más alto al 95% (HPD95%) ----

HPD_result <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del grupo de comparación' = X4,
    'Varianza para el efecto del toro' = X5,
    'Varianza para el efecto del individuo' = X6,
    'Residuo' = X7
    ) |>
  mutate(
    heredabilidad = `Varianza para el efecto del individuo` / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_grup_comp = (`Varianza para el efecto del grupo de comparación`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_toro = (`Varianza para el efecto del toro`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo)
    )

HDInterval::hdi(object = HPD_result$heredabilidad, credMass = 0.95) # El intervalo es de [0.071, 0.104]
```

<!--
NOTA: Para el caracter "intervalo entre el primer y segundo parto" se realiza la visualización de las trazas de convergencia, los parámetros genéticos (varianzas y heredabilidad) y 
-->

```{r}
#| label: Resultados del postgibbs para el intervalo entre el primer y segundo parto

# Con la siguiente función se creara la visualización de las trazas para mirar la convergencia según el burn-in indicado al hacer el postgibbs ----

create_plot <- function(data, componente, color) {
  data |>
    select(-c(1, 3)) |>
    rename(
      'Muestra' = X2,
      'Varianza para el efecto del grupo de comparación' = X4,
      'Varianza para el efecto del toro' = X5,
      'Varianza para el efecto del individuo' = X6,
      'Residuo' = X7
      ) |>
    pivot_longer(
      cols = c(2:5),
      names_to = 'Componentes de varianza',
      values_to = 'Estima'
      ) |>
    filter(`Componentes de varianza` == componente) |>
    ggplot(aes(x = Muestra, y = Estima)) +
    geom_line(alpha = 0.4, linewidth = 0.4, colour = color) +
    labs(x = 'Número de iteraciones', y = '', title = componente) +
    theme_bw() +
    theme(
      plot.title = element_text(size = 10, face = 'bold'),
      axis.text = element_text(size = 10, face = 'bold'),
      axis.title = element_text(size = 10, face = 'bold'),
      legend.position = 'none'
    )
  }

###############################
# 1. Conjunto de datos completo
###############################

##########################
# Con burn-in igual a cero
##########################

burnin_1 <- read_table(file = 'Datos/eva_genomica/SNP_tags_sing/intervalo_P1_P2/Completo/postgibbs_1/postgibbs_samples', col_names = FALSE)

# Se aplica la función al inicio de este fragmento para crear cada visualización de acuerdo al efecto considerado ----

create_plot(burnin_1, 'Varianza para el efecto del grupo de comparación', 'cyan')

ggsave('Datos/eva_genomica/SNP_tags_sing/intervalo_P1_P2/Completo/Imagenes/burnin_cero/varGC.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Varianza para el efecto del toro', 'orange')

ggsave('Datos/eva_genomica/SNP_tags_sing/intervalo_P1_P2/Completo/Imagenes/burnin_cero/varT.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Varianza para el efecto del individuo', 'black')

ggsave('Datos/eva_genomica/SNP_tags_sing/intervalo_P1_P2/Completo/Imagenes/burnin_cero/varG.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Residuo', 'green')

ggsave('Datos/eva_genomica/SNP_tags_sing/intervalo_P1_P2/Completo/Imagenes/burnin_cero/varR.pdf', width = 40, height = 20, units = 'cm')

# Se realiza una gráfica para visualizar las varianzas y la heredabilidad, a partir del postgibbs con burn-in de cero (burnin_1) ----

heredabilidad <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del grupo de comparación' = X4,
    'Varianza para el efecto del toro' = X5,
    'Varianza para el efecto del individuo' = X6,
    'Residuo' = X7
    ) |>
  mutate(
    heredabilidad = `Varianza para el efecto del individuo` / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_grup_comp = (`Varianza para el efecto del grupo de comparación`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_toro = (`Varianza para el efecto del toro`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo)
    )

graf_varGC <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del grupo de comparación`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'cyan', fill = 'cyan', alpha = 0.2) +
  annotate(
    'text', x = 1280, y = 0.006,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del grupo de comparación`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del grupo de comparación') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varT <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del toro`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2) +
  annotate(
    'text', x = 1280, y = 0.004,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del toro`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del toro') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varG <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del individuo`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2) +
  annotate(
    'text', x = 440, y = 0.006,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del individuo`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza genética aditiva') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_grup_comp <- heredabilidad |>
  ggplot(aes(x = proporcion_var_grup_comp)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(
    'text', x = 0.225, y = 25,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_grup_comp), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del grupo de comparación') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_toro <- heredabilidad |>
  ggplot(aes(x = proporcion_var_toro)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'gray', fill = 'gray', alpha = 0.2) +
  annotate(
    'text', x = 0.225, y = 25,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_toro), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del toro') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varE <- heredabilidad |>
  ggplot(aes(x = Residuo)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2) +
  annotate(
    'text', x = 3040, y = 0.006,
    label = paste('Valor medio = ', round(mean(heredabilidad$Residuo), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza residual') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_heredabilidad <- heredabilidad |>
  ggplot(aes(x = heredabilidad)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2)  +
  annotate(
    'text', x = 0.078, y = 30,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad), digits = 2)), size = 3.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

(guide_area()/(((graf_varGC | graf_varG) / (graf_varT | graf_varE) / (graf_prop_grup_comp | graf_prop_toro)) | (graf_heredabilidad))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Parámetros para el intervalo entre el primer parto y segundo parto') & 
  theme(plot.title = element_text(size = 9.4, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/SNP_tags_sing/intervalo_P1_P2/Completo/Imagenes/burnin_diezmil/Heredabilidad.pdf', width = 40, height = 20, units = 'cm')

# Se calcula el intervalo de densidad posterior más alto al 95% (HPD95%) ----

HPD_result <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del grupo de comparación' = X4,
    'Varianza para el efecto del toro' = X5,
    'Varianza para el efecto del individuo' = X6,
    'Residuo' = X7
    ) |>
  mutate(
    heredabilidad = `Varianza para el efecto del individuo` / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_grup_comp = (`Varianza para el efecto del grupo de comparación`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_toro = (`Varianza para el efecto del toro`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo)
    )

HDInterval::hdi(object = HPD_result$heredabilidad, credMass = 0.95) # El intervalo es de [0.027, 0.087]

##############################
# 2. Conjunto de datos parcial
##############################

##########################
# Con burn-in igual a cero
##########################

burnin_1 <- read_table(file = 'Datos/eva_genomica/SNP_tags_sing/intervalo_P1_P2/Parcial/postgibbs_1/postgibbs_samples', col_names = FALSE)

# Se realiza una gráfica para visualizar las varianzas y la heredabilidad, a partir del postgibbs con burn-in de cero (burnin_1) ----

heredabilidad <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del grupo de comparación' = X4,
    'Varianza para el efecto del toro' = X5,
    'Varianza para el efecto del individuo' = X6,
    'Residuo' = X7
    ) |>
  mutate(
    heredabilidad = `Varianza para el efecto del individuo` / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_grup_comp = (`Varianza para el efecto del grupo de comparación`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_toro = (`Varianza para el efecto del toro`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo)
    )

graf_varGC <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del grupo de comparación`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'cyan', fill = 'cyan', alpha = 0.2) +
  annotate(
    'text', x = 1280, y = 0.006,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del grupo de comparación`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del grupo de comparación') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varT <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del toro`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2) +
  annotate(
    'text', x = 1280, y = 0.004,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del toro`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del toro') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varG <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del individuo`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2) +
  annotate(
    'text', x = 440, y = 0.006,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del individuo`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza genética aditiva') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_grup_comp <- heredabilidad |>
  ggplot(aes(x = proporcion_var_grup_comp)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(
    'text', x = 0.225, y = 25,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_grup_comp), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del grupo de comparación') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_toro <- heredabilidad |>
  ggplot(aes(x = proporcion_var_toro)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'gray', fill = 'gray', alpha = 0.2) +
  annotate(
    'text', x = 0.225, y = 25,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_toro), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del toro') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varE <- heredabilidad |>
  ggplot(aes(x = Residuo)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2) +
  annotate(
    'text', x = 3040, y = 0.006,
    label = paste('Valor medio = ', round(mean(heredabilidad$Residuo), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza residual') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_heredabilidad <- heredabilidad |>
  ggplot(aes(x = heredabilidad)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2)  +
  annotate(
    'text', x = 0.078, y = 30,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad), digits = 2)), size = 3.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

(guide_area()/(((graf_varGC | graf_varG) / (graf_varT | graf_varE) / (graf_prop_grup_comp | graf_prop_toro)) | (graf_heredabilidad))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Parámetros para el intervalo entre el primer parto y segundo parto') & 
  theme(plot.title = element_text(size = 9.4, face = 'bold'))

HPD_result <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del grupo de comparación' = X4,
    'Varianza para el efecto del toro' = X5,
    'Varianza para el efecto del individuo' = X6,
    'Residuo' = X7
    ) |>
  mutate(
    heredabilidad = `Varianza para el efecto del individuo` / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_grup_comp = (`Varianza para el efecto del grupo de comparación`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo),
    proporcion_var_toro = (`Varianza para el efecto del toro`) / (`Varianza para el efecto del grupo de comparación` + `Varianza para el efecto del toro` + `Varianza para el efecto del individuo` + Residuo)
    )

# Se calcula el intervalo de densidad posterior más alto al 95% (HPD95%) ----

HDInterval::hdi(object = HPD_result$heredabilidad, credMass = 0.95) # El intervalo es de [0.026, 0.077]
```

<!--
NOTA: Para el caracter "peso al destete" se realiza la visualización de las trazas de convergencia, los parámetros genéticos (varianzas y heredabilidad) y 
-->

```{r}
#| label: Resultados del postgibbs para el peso al destete

# Con la siguiente función se creara la visualización de las trazas para mirar la convergencia según el burn-in indicado al hacer el postgibbs ----

create_plot <- function(data, componente, color) {
  data |>
    select(-c(1, 3)) |>
    rename(
      'Muestra' = X2,
      'Varianza para el efecto del individuo' = X4,
      'Covarianza entre efecto directo y materno' = X5,
      'Varianza para el efecto materno' = X6,
      'Varianza para el efecto permanente materno' = X7,
      'Residuo' = X8
      ) |>
    pivot_longer(
      cols = c(2:6),
      names_to = 'Componentes de varianza',
      values_to = 'Estima'
      ) |>
    filter(`Componentes de varianza` == componente) |>
    ggplot(aes(x = Muestra, y = Estima)) +
    geom_line(alpha = 0.4, linewidth = 0.4, colour = color) +
    labs(x = 'Número de iteraciones', y = '', title = componente) +
    theme_bw() +
    theme(
      plot.title = element_text(size = 10, face = 'bold'),
      axis.text = element_text(size = 10, face = 'bold'),
      axis.title = element_text(size = 10, face = 'bold'),
      legend.position = 'none'
    )
  }

###############################
# 1. Conjunto de datos completo
###############################

##########################
# Con burn-in igual a cero
##########################

burnin_1 <- read_table(file = 'Datos/eva_genomica/SNP_tags_sing/peso_Dtte/Completo/postgibbs_1/postgibbs_samples', col_names = FALSE)

# Se aplica la función al inicio de este fragmento para crear cada visualización de acuerdo al efecto considerado ----

create_plot(burnin_1, 'Varianza para el efecto del individuo', 'cyan')

ggsave('Datos/eva_genomica/SNP_tags_sing/peso_Dtte/Completo/Imagenes/burnin_cero/varG.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Covarianza entre efecto directo y materno', 'orange')

ggsave('Datos/eva_genomica/SNP_tags_sing/peso_Dtte/Completo/Imagenes/burnin_cero/covarDM.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Varianza para el efecto materno', 'black')

ggsave('Datos/eva_genomica/SNP_tags_sing/peso_Dtte/Completo/Imagenes/burnin_cero/varM.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Varianza para el efecto permanente materno', 'green')

ggsave('Datos/eva_genomica/SNP_tags_sing/peso_Dtte/Completo/Imagenes/burnin_cero/varPM.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Residuo', 'red')

ggsave('Datos/eva_genomica/SNP_tags_sing/peso_Dtte/Completo/Imagenes/burnin_cero/varR.pdf', width = 40, height = 20, units = 'cm')

# Se realiza una gráfica para visualizar las varianzas y la heredabilidad, a partir del postgibbs con burn-in de cero (burnin_1) ---- ----

heredabilidad <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del individuo' = X4,
    'Covarianza entre efecto directo y materno' = X5,
    'Varianza para el efecto materno' = X6,
    'Varianza para el efecto permanente materno' = X7,
    'Residuo' = X8
    ) |>
  mutate(
    heredabilidad_total = (`Varianza para el efecto del individuo` + ((0.5) * (`Varianza para el efecto materno`)) + ((1.5) * (`Covarianza entre efecto directo y materno`))) / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo),
    heredabilidad_directa = `Varianza para el efecto del individuo` / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo),
    heredabilidad_materna = `Varianza para el efecto materno` / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo),
    corr_directo_materno = `Covarianza entre efecto directo y materno` / (sqrt(`Varianza para el efecto del individuo`) * sqrt(`Varianza para el efecto materno`)),
    proporcion_var_ambiental_materna = (`Varianza para el efecto permanente materno`) / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo)
    )

graf_varG <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del individuo`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2) +
  annotate(
    'text', x = 270, y = 0.015,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del individuo`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza genética aditiva') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varE <- heredabilidad |>
  ggplot(aes(x = Residuo)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2) +
  annotate(
    'text', x = 500, y = 0.03,
    label = paste('Valor medio = ', round(mean(heredabilidad$Residuo), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza residual') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varM <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto materno`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(
    'text', x = 140, y = 0.03,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto materno`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto materno') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varPM <- heredabilidad |>
  ggplot(aes(x = Residuo)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2) +
  annotate(
    'text', x = 500, y = 0.03,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto permanente materno`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto permanente materno') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_covarDM <- heredabilidad |>
  ggplot(aes(x = `Covarianza entre efecto directo y materno`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2) +
  annotate(
    'text', x = -80, y = 0.025,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Covarianza entre efecto directo y materno`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Covarianza entre los efectos directos y maternos') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_her_directa <- heredabilidad |>
  ggplot(aes(x = heredabilidad_directa)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2)  +
  annotate(
    'text', x = 0.34, y = 13,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad_directa), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad directa') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_her_materna <- heredabilidad |>
  ggplot(aes(x = heredabilidad_materna)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2)  +
  annotate(
    'text', x = 0.19, y = 20,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad_materna), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad materna') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_her_total <- heredabilidad |>
  ggplot(aes(x = heredabilidad_total)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2)  +
  annotate(
    'text', x = 0.165, y = 20,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad_total), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad total') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_corr_directo_materno <- heredabilidad |>
  ggplot(aes(x = corr_directo_materno)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2)  +
  annotate(
    'text', x = -0.65, y = 9,
    label = paste('Valor medio = ', round(mean(heredabilidad$corr_directo_materno), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Correlación entre los efectos directos y maternos') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_ambiente_materno <- heredabilidad |>
  ggplot(aes(x = proporcion_var_ambiental_materna)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2) +
  annotate(
    'text', x = 0.10, y = 40,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_ambiental_materna), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza ambiental materno') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_vacio <- ggplot(NULL)+
  geom_blank() +
  theme_minimal()

(guide_area()/(((graf_varG | graf_varM) / (graf_varPM | graf_varE) / (graf_covarDM | graf_vacio)) | ((graf_her_directa | graf_her_materna) / (graf_her_total | graf_corr_directo_materno) / (graf_prop_ambiente_materno | graf_vacio)))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Parámetros para el peso al destete') & 
  theme(plot.title = element_text(size = 9.4, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/SNP_tags_sing/peso_Dtte/Completo/Imagenes/burnin_diezmil/Heredabilidad.pdf', width = 40, height = 20, units = 'cm')

HPD_result <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del individuo' = X4,
    'Covarianza entre efecto directo y materno' = X5,
    'Varianza para el efecto materno' = X6,
    'Varianza para el efecto permanente materno' = X7,
    'Residuo' = X8
    ) |>
  mutate(
    heredabilidad_total = (`Varianza para el efecto del individuo` + ((0.5) * (`Varianza para el efecto materno`)) + ((1.5) * (`Covarianza entre efecto directo y materno`))) / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo),
    heredabilidad_directa = `Varianza para el efecto del individuo` / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo),
    heredabilidad_materna = `Varianza para el efecto materno` / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo),
    corr_directo_materno = `Covarianza entre efecto directo y materno` / (sqrt(`Varianza para el efecto del individuo`) * sqrt(`Varianza para el efecto materno`)),
    proporcion_var_ambiental_materna = (`Varianza para el efecto permanente materno`) / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo)
    )

# Se calcula el intervalo de densidad posterior más alto al 95% (HPD95%) ----

HDInterval::hdi(object = HPD_result$heredabilidad_directa, credMass = 0.95) # El intervalo es de [0.238, 0.328]
HDInterval::hdi(object = HPD_result$heredabilidad_materna, credMass = 0.95) # El intervalo es de [0.120, 0.176]
HDInterval::hdi(object = HPD_result$corr_directo_materno, credMass = 0.95) # El intervalo es de [-0.774, -0.648]

##############################
# 2. Conjunto de datos parcial
##############################

##########################
# Con burn-in igual a cero
##########################

burnin_1 <- read_table(file = 'Datos/eva_genomica/SNP_tags_sing/peso_Dtte/Parcial/postgibbs_1/postgibbs_samples', col_names = FALSE)

# Se realiza una gráfica para visualizar las varianzas y la heredabilidad, a partir del postgibbs con burn-in de cero (burnin_1) ---- ----

heredabilidad <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del individuo' = X4,
    'Covarianza entre efecto directo y materno' = X5,
    'Varianza para el efecto materno' = X6,
    'Varianza para el efecto permanente materno' = X7,
    'Residuo' = X8
    ) |>
  mutate(
    heredabilidad_total = (`Varianza para el efecto del individuo` + ((0.5) * (`Varianza para el efecto materno`)) + ((1.5) * (`Covarianza entre efecto directo y materno`))) / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo),
    heredabilidad_directa = `Varianza para el efecto del individuo` / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo),
    heredabilidad_materna = `Varianza para el efecto materno` / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo),
    corr_directo_materno = `Covarianza entre efecto directo y materno` / (sqrt(`Varianza para el efecto del individuo`) * sqrt(`Varianza para el efecto materno`)),
    proporcion_var_ambiental_materna = (`Varianza para el efecto permanente materno`) / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo)
    )

graf_varG <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del individuo`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2) +
  annotate(
    'text', x = 270, y = 0.015,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del individuo`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza genética aditiva') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varE <- heredabilidad |>
  ggplot(aes(x = Residuo)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2) +
  annotate(
    'text', x = 500, y = 0.03,
    label = paste('Valor medio = ', round(mean(heredabilidad$Residuo), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza residual') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varM <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto materno`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(
    'text', x = 140, y = 0.03,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto materno`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto materno') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varPM <- heredabilidad |>
  ggplot(aes(x = Residuo)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2) +
  annotate(
    'text', x = 500, y = 0.03,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto permanente materno`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto permanente materno') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_covarDM <- heredabilidad |>
  ggplot(aes(x = `Covarianza entre efecto directo y materno`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2) +
  annotate(
    'text', x = -80, y = 0.025,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Covarianza entre efecto directo y materno`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Covarianza entre los efectos directos y maternos') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_her_directa <- heredabilidad |>
  ggplot(aes(x = heredabilidad_directa)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2)  +
  annotate(
    'text', x = 0.34, y = 13,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad_directa), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad directa') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_her_materna <- heredabilidad |>
  ggplot(aes(x = heredabilidad_materna)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2)  +
  annotate(
    'text', x = 0.19, y = 20,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad_materna), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad materna') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_her_total <- heredabilidad |>
  ggplot(aes(x = heredabilidad_total)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2)  +
  annotate(
    'text', x = 0.165, y = 20,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad_total), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad total') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_corr_directo_materno <- heredabilidad |>
  ggplot(aes(x = corr_directo_materno)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2)  +
  annotate(
    'text', x = -0.65, y = 9,
    label = paste('Valor medio = ', round(mean(heredabilidad$corr_directo_materno), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Correlación entre los efectos directos y maternos') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_ambiente_materno <- heredabilidad |>
  ggplot(aes(x = proporcion_var_ambiental_materna)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2) +
  annotate(
    'text', x = 0.10, y = 40,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_ambiental_materna), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza ambiental materno') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_vacio <- ggplot(NULL)+
  geom_blank() +
  theme_minimal()

(guide_area()/(((graf_varG | graf_varM) / (graf_varPM | graf_varE) / (graf_covarDM | graf_vacio)) | ((graf_her_directa | graf_her_materna) / (graf_her_total | graf_corr_directo_materno) / (graf_prop_ambiente_materno | graf_vacio)))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Parámetros para el peso al destete') & 
  theme(plot.title = element_text(size = 9.4, face = 'bold'))

HPD_result <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
    'Varianza para el efecto del individuo' = X4,
    'Covarianza entre efecto directo y materno' = X5,
    'Varianza para el efecto materno' = X6,
    'Varianza para el efecto permanente materno' = X7,
    'Residuo' = X8
    ) |>
  mutate(
    heredabilidad_total = (`Varianza para el efecto del individuo` + ((0.5) * (`Varianza para el efecto materno`)) + ((1.5) * (`Covarianza entre efecto directo y materno`))) / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo),
    heredabilidad_directa = `Varianza para el efecto del individuo` / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo),
    heredabilidad_materna = `Varianza para el efecto materno` / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo),
    corr_directo_materno = `Covarianza entre efecto directo y materno` / (sqrt(`Varianza para el efecto del individuo`) * sqrt(`Varianza para el efecto materno`)),
    proporcion_var_ambiental_materna = (`Varianza para el efecto permanente materno`) / (`Varianza para el efecto del individuo` + `Varianza para el efecto materno` + `Varianza para el efecto permanente materno` + `Covarianza entre efecto directo y materno` + Residuo)
    )

# Se calcula el intervalo de densidad posterior más alto al 95% (HPD95%) ----

HDInterval::hdi(object = HPD_result$heredabilidad_directa, credMass = 0.95) # El intervalo es de [0.219, 0.315]
HDInterval::hdi(object = HPD_result$heredabilidad_materna, credMass = 0.95) # El intervalo es de [0.109, 0.168]
HDInterval::hdi(object = HPD_result$corr_directo_materno, credMass = 0.95) # El intervalo es de [-0.750, -0.593]
```

<!--
NOTA: Para el bi-caracter "edad al primer parto" e "intervalo entre el primer y segundo parto" se realiza la visualización de las trazas de convergencia, los parámetros genéticos (varianzas y heredabilidad) y 
-->

```{r}
#| label: Resultados del postgibbs para el bi-carácter edad al primer parto e intervalo entre el primer y segundo parto

# Con la siguiente función se creara la visualización de las trazas para mirar la convergencia según el burn-in indicado al hacer el postgibbs ----

create_plot <- function(data, componente, color) {
  data |>
    select(-c(1, 3)) |>
    rename(
      'Muestra' = X2,
      'Varianza para el efecto del grupo de comparación - EPP' = X4,
      'Varianza para el efecto del toro - EPP' = X5,
      'Varianza para el efecto del grupo de comparación - I_P1-P2' = X6,
      'Varianza para el efecto del toro - I_P1-P2' = X7,
      'Varianza para el efecto del individuo - EPP' = X8,
      'Covarianza entre efectos geneticos - EPP e I_P1-P2' = X9,
      'Varianza para el efecto del individuo - I_P1-P2' = X10,
      'Residuo - EPP' = X11,
      'Covarianza residual - EPP e I_P1-P2' = X12,
      'Residuo - I_P1-P2' = X13
      ) |>
    pivot_longer(
      cols = c(2:11),
      names_to = 'Componentes de varianza',
      values_to = 'Estima'
      ) |>
    filter(`Componentes de varianza` == componente) |>
    ggplot(aes(x = Muestra, y = Estima)) +
    geom_line(alpha = 0.4, linewidth = 0.4, colour = color) +
    labs(x = 'Número de iteraciones', y = '', title = componente) +
    theme_bw() +
    theme(
      plot.title = element_text(size = 10, face = 'bold'),
      axis.text = element_text(size = 10, face = 'bold'),
      axis.title = element_text(size = 10, face = 'bold'),
      legend.position = 'none'
    )
  }

###############################
# 1. Conjunto de datos completo
###############################

##########################
# Con burn-in igual a cero
##########################

burnin_1 <- read_table(file = 'Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Completo/postgibbs_1/postgibbs_samples', col_names = FALSE)

create_plot(burnin_1, 'Varianza para el efecto del grupo de comparación - EPP', 'cyan')

ggsave('Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Completo/Imagenes/burnin_cero/varGC_EPP.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Varianza para el efecto del toro - EPP', 'orange')

ggsave('Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Completo/Imagenes/burnin_cero/varT_EPP.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Varianza para el efecto del grupo de comparación - I_P1-P2', 'cyan')

ggsave('Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Completo/Imagenes/burnin_cero/varGC_IEP.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Varianza para el efecto del toro - I_P1-P2', 'orange')

ggsave('Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Completo/Imagenes/burnin_cero/varT_IEP.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Varianza para el efecto del individuo - EPP', 'green')

ggsave('Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Completo/Imagenes/burnin_cero/varG_EPP.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Covarianza entre efectos geneticos - EPP e I_P1-P2', 'black')

ggsave('Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Completo/Imagenes/burnin_cero/covG__EPP_IEP.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Varianza para el efecto del individuo - I_P1-P2', 'green')

ggsave('Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Completo/Imagenes/burnin_cero/varG_IEP.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Residuo - EPP', 'green')

ggsave('Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Completo/Imagenes/burnin_cero/varR_EPP.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Covarianza residual - EPP e I_P1-P2', 'black')

ggsave('Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Completo/Imagenes/burnin_cero/covR__EPP_IEP.pdf', width = 40, height = 20, units = 'cm')

create_plot(burnin_1, 'Residuo - I_P1-P2', 'green')

ggsave('Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Completo/Imagenes/burnin_cero/varR_IEP.pdf', width = 40, height = 20, units = 'cm')

# Se realiza una gráfica para visualizar las varianzas y la heredabilidad, a partir del postgibbs con burn-in de cero (burnin_1) ---- ----

heredabilidad <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
      'Varianza para el efecto del grupo de comparación - EPP' = X4,
      'Varianza para el efecto del toro - EPP' = X5,
      'Varianza para el efecto del grupo de comparación - I_P1-P2' = X6,
      'Varianza para el efecto del toro - I_P1-P2' = X7,
      'Varianza para el efecto del individuo - EPP' = X8,
      'Covarianza entre efectos geneticos - EPP e I_P1-P2' = X9,
      'Varianza para el efecto del individuo - I_P1-P2' = X10,
      'Residuo - EPP' = X11,
      'Covarianza residual - EPP e I_P1-P2' = X12,
      'Residuo - I_P1-P2' = X13
    ) |>
  mutate(
    heredabilidad_EPP = `Varianza para el efecto del individuo - EPP` / (`Varianza para el efecto del grupo de comparación - EPP` + `Varianza para el efecto del toro - EPP` + `Varianza para el efecto del individuo - EPP` + `Residuo - EPP`),
    heredabilidad_IEP = `Varianza para el efecto del individuo - I_P1-P2` / (`Varianza para el efecto del grupo de comparación - I_P1-P2` + `Varianza para el efecto del toro - I_P1-P2` + `Varianza para el efecto del individuo - I_P1-P2` + `Residuo - I_P1-P2`),
    corr_gen_EPP_IEP = `Covarianza entre efectos geneticos - EPP e I_P1-P2` / (sqrt(`Varianza para el efecto del individuo - EPP`) * sqrt(`Varianza para el efecto del individuo - I_P1-P2`)),
    proporcion_var_grup_comp_EPP = (`Varianza para el efecto del grupo de comparación - EPP`) / (`Varianza para el efecto del grupo de comparación - EPP` + `Varianza para el efecto del toro - EPP` + `Varianza para el efecto del individuo - EPP` + `Residuo - EPP`),
    proporcion_var_toro_EPP = (`Varianza para el efecto del toro - EPP`) / (`Varianza para el efecto del grupo de comparación - EPP` + `Varianza para el efecto del toro - EPP` + `Varianza para el efecto del individuo - EPP` + `Residuo - EPP`),
    proporcion_var_grup_comp_IEP = (`Varianza para el efecto del grupo de comparación - I_P1-P2`) / (`Varianza para el efecto del grupo de comparación - I_P1-P2` + `Varianza para el efecto del toro - I_P1-P2` + `Varianza para el efecto del individuo - I_P1-P2` + `Residuo - I_P1-P2`),
    proporcion_var_toro_IEP = (`Varianza para el efecto del toro - I_P1-P2`) / (`Varianza para el efecto del grupo de comparación - I_P1-P2` + `Varianza para el efecto del toro - I_P1-P2` + `Varianza para el efecto del individuo - I_P1-P2` + `Residuo - I_P1-P2`)
    )

HDInterval::hdi(object = heredabilidad$heredabilidad_EPP, credMass = 0.95) # El intervalo es de [0.074, 0.105]
HDInterval::hdi(object = heredabilidad$heredabilidad_IEP, credMass = 0.95) # El intervalo es de [0.035, 0.078]
HDInterval::hdi(object = heredabilidad$corr_gen_EPP_IEP, credMass = 0.95) # El intervalo es de [0.033, 0.039]

graf_varG_EPP <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del individuo - EPP`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2) +
  annotate(
    'text', x = 2400, y = 0.0015,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del individuo - EPP`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza genética aditiva EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varG_IEP <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del individuo - I_P1-P2`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2) +
  annotate(
    'text', x = 400, y = 0.005,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del individuo - I_P1-P2`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza genética aditiva IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varE_EPP <- heredabilidad |>
  ggplot(aes(x = `Residuo - EPP`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2) +
  annotate(
    'text', x = 11250, y = 0.0020,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Residuo - EPP`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza residual EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varE_IEP <- heredabilidad |>
  ggplot(aes(x = `Residuo - I_P1-P2`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2) +
  annotate(
    'text', x = 3050, y = 0.005,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Residuo - I_P1-P2`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza residual IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varGC_EPP <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del grupo de comparación - EPP`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'cyan', fill = 'cyan', alpha = 0.2) +
  annotate(
    'text', x = 5810, y = 0.0017,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del grupo de comparación - EPP`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del grupo de comparación EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varGC_IEP <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del grupo de comparación - I_P1-P2`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'cyan', fill = 'cyan', alpha = 0.2) +
  annotate(
    'text', x = 1250, y = 0.005,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del grupo de comparación - I_P1-P2`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del grupo de comparación IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varT_EPP <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del toro - EPP`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2) +
  annotate(
    'text', x = 4500, y = 0.00125,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del toro - EPP`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del toro EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varT_IEP <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del toro - I_P1-P2`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2) +
  annotate(
    'text', x = 1300, y = 0.004,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del toro - I_P1-P2`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del toro IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_heredabilidad_EPP <- heredabilidad |>
  ggplot(aes(x = heredabilidad_EPP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2)  +
  annotate(
    'text', x = 0.11, y = 40,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad_EPP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_heredabilidad_IEP <- heredabilidad |>
  ggplot(aes(x = heredabilidad_IEP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2)  +
  annotate(
    'text', x = 0.08, y = 25,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad_IEP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_corr_gen_EPP_IEP <- heredabilidad |>
  ggplot(aes(x = corr_gen_EPP_IEP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2)  +
  annotate(
    'text', x = 0.08, y = 3,
    label = paste('Valor medio = ', round(mean(heredabilidad$corr_gen_EPP_IEP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Correlación genética entre EPP e IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_grup_comp_EPP <- heredabilidad |>
  ggplot(aes(x = proporcion_var_grup_comp_EPP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(
    'text', x = 0.225, y = 25,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_grup_comp_EPP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del grupo de comparación EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_grup_comp_IEP <- heredabilidad |>
  ggplot(aes(x = proporcion_var_grup_comp_IEP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(
    'text', x = 0.22, y = 30,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_grup_comp_IEP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del grupo de comparación IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_toro_EPP <- heredabilidad |>
  ggplot(aes(x = proporcion_var_toro_EPP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'gray', fill = 'gray', alpha = 0.2) +
  annotate(
    'text', x = 0.20, y = 25,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_toro_EPP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del toro EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_toro_IEP <- heredabilidad |>
  ggplot(aes(x = proporcion_var_toro_IEP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'gray', fill = 'gray', alpha = 0.2) +
  annotate(
    'text', x = 0.24, y = 20,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_toro_IEP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del toro IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_vacio <- ggplot(NULL)+
  geom_blank() +
  theme_minimal()

(guide_area()/(((graf_varG_EPP | graf_varE_EPP) / (graf_varGC_EPP | graf_varT_EPP) / (graf_heredabilidad_EPP | graf_prop_grup_comp_EPP) / (graf_prop_toro_EPP | graf_vacio)) | ((graf_varG_IEP | graf_varE_IEP) / (graf_varGC_IEP | graf_varT_IEP) / (graf_heredabilidad_IEP | graf_prop_grup_comp_IEP) / (graf_prop_toro_IEP | graf_vacio)) | (graf_corr_gen_EPP_IEP))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Parámetros para el bi-carácter entre edad al primer parto e intervalo entre el primer y segundo parto') & 
  theme(plot.title = element_text(size = 8.4, face = 'bold'))

ggsave('eva_genetica/Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Completo/Imagenes/burnin_diezmil/heredabilidad.pdf', width = 40, height = 20, units = 'cm')

##############################
# 2. Conjunto de datos parcial
##############################

##########################
# Con burn-in igual a cero
##########################

burnin_1 <- read_table(file = 'Datos/eva_genomica/SNP_tags_sing/EPP_IEP/Parcial/postgibbs_1/postgibbs_samples', col_names = FALSE)

# Se realiza una gráfica para visualizar las varianzas y la heredabilidad, a partir del postgibbs con burn-in de cero (burnin_1) ---- ----

heredabilidad <- burnin_1 |>
  select(-c(1, 3)) |>
  rename(
    'Muestra' = X2,
      'Varianza para el efecto del grupo de comparación - EPP' = X4,
      'Varianza para el efecto del toro - EPP' = X5,
      'Varianza para el efecto del grupo de comparación - I_P1-P2' = X6,
      'Varianza para el efecto del toro - I_P1-P2' = X7,
      'Varianza para el efecto del individuo - EPP' = X8,
      'Covarianza entre efectos geneticos - EPP e I_P1-P2' = X9,
      'Varianza para el efecto del individuo - I_P1-P2' = X10,
      'Residuo - EPP' = X11,
      'Covarianza residual - EPP e I_P1-P2' = X12,
      'Residuo - I_P1-P2' = X13
    ) |>
  mutate(
    heredabilidad_EPP = `Varianza para el efecto del individuo - EPP` / (`Varianza para el efecto del grupo de comparación - EPP` + `Varianza para el efecto del toro - EPP` + `Varianza para el efecto del individuo - EPP` + `Residuo - EPP`),
    heredabilidad_IEP = `Varianza para el efecto del individuo - I_P1-P2` / (`Varianza para el efecto del grupo de comparación - I_P1-P2` + `Varianza para el efecto del toro - I_P1-P2` + `Varianza para el efecto del individuo - I_P1-P2` + `Residuo - I_P1-P2`),
    corr_gen_EPP_IEP = `Covarianza entre efectos geneticos - EPP e I_P1-P2` / (sqrt(`Varianza para el efecto del individuo - EPP`) * sqrt(`Varianza para el efecto del individuo - I_P1-P2`)),
    proporcion_var_grup_comp_EPP = (`Varianza para el efecto del grupo de comparación - EPP`) / (`Varianza para el efecto del grupo de comparación - EPP` + `Varianza para el efecto del toro - EPP` + `Varianza para el efecto del individuo - EPP` + `Residuo - EPP`),
    proporcion_var_toro_EPP = (`Varianza para el efecto del toro - EPP`) / (`Varianza para el efecto del grupo de comparación - EPP` + `Varianza para el efecto del toro - EPP` + `Varianza para el efecto del individuo - EPP` + `Residuo - EPP`),
    proporcion_var_grup_comp_IEP = (`Varianza para el efecto del grupo de comparación - I_P1-P2`) / (`Varianza para el efecto del grupo de comparación - I_P1-P2` + `Varianza para el efecto del toro - I_P1-P2` + `Varianza para el efecto del individuo - I_P1-P2` + `Residuo - I_P1-P2`),
    proporcion_var_toro_IEP = (`Varianza para el efecto del toro - I_P1-P2`) / (`Varianza para el efecto del grupo de comparación - I_P1-P2` + `Varianza para el efecto del toro - I_P1-P2` + `Varianza para el efecto del individuo - I_P1-P2` + `Residuo - I_P1-P2`)
    )

HDInterval::hdi(object = heredabilidad$heredabilidad_EPP, credMass = 0.95) # El intervalo es de [0.071, 0.102]
HDInterval::hdi(object = heredabilidad$heredabilidad_IEP, credMass = 0.95) # El intervalo es de [0.038, 0.069]
HDInterval::hdi(object = heredabilidad$corr_gen_EPP_IEP, credMass = 0.95) # El intervalo es de [0.057, 0.45]

graf_varG_EPP <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del individuo - EPP`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2) +
  annotate(
    'text', x = 2400, y = 0.0015,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del individuo - EPP`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza genética aditiva EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varG_IEP <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del individuo - I_P1-P2`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'green', fill = 'green', alpha = 0.2) +
  annotate(
    'text', x = 400, y = 0.005,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del individuo - I_P1-P2`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza genética aditiva IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varE_EPP <- heredabilidad |>
  ggplot(aes(x = `Residuo - EPP`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2) +
  annotate(
    'text', x = 11250, y = 0.0020,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Residuo - EPP`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza residual EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varE_IEP <- heredabilidad |>
  ggplot(aes(x = `Residuo - I_P1-P2`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'red', fill = 'red', alpha = 0.2) +
  annotate(
    'text', x = 3050, y = 0.005,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Residuo - I_P1-P2`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza residual IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varGC_EPP <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del grupo de comparación - EPP`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'cyan', fill = 'cyan', alpha = 0.2) +
  annotate(
    'text', x = 5810, y = 0.0017,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del grupo de comparación - EPP`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del grupo de comparación EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varGC_IEP <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del grupo de comparación - I_P1-P2`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'cyan', fill = 'cyan', alpha = 0.2) +
  annotate(
    'text', x = 1250, y = 0.005,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del grupo de comparación - I_P1-P2`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del grupo de comparación IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varT_EPP <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del toro - EPP`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2) +
  annotate(
    'text', x = 4500, y = 0.00125,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del toro - EPP`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del toro EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_varT_IEP <- heredabilidad |>
  ggplot(aes(x = `Varianza para el efecto del toro - I_P1-P2`)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'orange', fill = 'orange', alpha = 0.2) +
  annotate(
    'text', x = 1300, y = 0.004,
    label = paste('Valor medio = ', round(mean(heredabilidad$`Varianza para el efecto del toro - I_P1-P2`), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Varianza para el efecto del toro IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_heredabilidad_EPP <- heredabilidad |>
  ggplot(aes(x = heredabilidad_EPP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2)  +
  annotate(
    'text', x = 0.11, y = 40,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad_EPP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_heredabilidad_IEP <- heredabilidad |>
  ggplot(aes(x = heredabilidad_IEP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'black', fill = 'black', alpha = 0.2)  +
  annotate(
    'text', x = 0.08, y = 25,
    label = paste('Valor medio = ', round(mean(heredabilidad$heredabilidad_IEP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Heredabilidad IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 7, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_corr_gen_EPP_IEP <- heredabilidad |>
  ggplot(aes(x = corr_gen_EPP_IEP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2)  +
  annotate(
    'text', x = 0.08, y = 3,
    label = paste('Valor medio = ', round(mean(heredabilidad$corr_gen_EPP_IEP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Correlación genética entre EPP e IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_grup_comp_EPP <- heredabilidad |>
  ggplot(aes(x = proporcion_var_grup_comp_EPP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(
    'text', x = 0.225, y = 25,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_grup_comp_EPP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del grupo de comparación EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_grup_comp_IEP <- heredabilidad |>
  ggplot(aes(x = proporcion_var_grup_comp_IEP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(
    'text', x = 0.22, y = 30,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_grup_comp_IEP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del grupo de comparación IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_toro_EPP <- heredabilidad |>
  ggplot(aes(x = proporcion_var_toro_EPP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'gray', fill = 'gray', alpha = 0.2) +
  annotate(
    'text', x = 0.20, y = 25,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_toro_EPP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del toro EPP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_prop_toro_IEP <- heredabilidad |>
  ggplot(aes(x = proporcion_var_toro_IEP)) +
  geom_histogram(aes(y = ..density..), bins = 20, colour = 'gray', fill = 'gray', alpha = 0.2) +
  annotate(
    'text', x = 0.24, y = 20,
    label = paste('Valor medio = ', round(mean(heredabilidad$proporcion_var_toro_IEP), digits = 2)), size = 2.4, fontface = 'bold'
    ) +
  labs(x = '', y = 'Frecuencia', title = 'Proporción de la varianza del toro IEP') +
  theme_bw() +
  theme(
    axis.text = element_text(size = 10, face = 'bold'),
    axis.title = element_text(size = 10, face = 'bold'),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12, face = 'bold')
    )

graf_vacio <- ggplot(NULL)+
  geom_blank() +
  theme_minimal()

(guide_area()/(((graf_varG_EPP | graf_varE_EPP) / (graf_varGC_EPP | graf_varT_EPP) / (graf_heredabilidad_EPP | graf_prop_grup_comp_EPP) / (graf_prop_toro_EPP | graf_vacio)) | ((graf_varG_IEP | graf_varE_IEP) / (graf_varGC_IEP | graf_varT_IEP) / (graf_heredabilidad_IEP | graf_prop_grup_comp_IEP) / (graf_prop_toro_IEP | graf_vacio)) | (graf_corr_gen_EPP_IEP))) +
  plot_layout(guides = "collect", heights = unit(c(0.1, 0.1), c('cm', 'null'))) + 
  plot_annotation(title = 'Parámetros para el bi-carácter entre edad al primer parto e intervalo entre el primer y segundo parto') & 
  theme(plot.title = element_text(size = 8.4, face = 'bold'))
```
