---
title: "Parte 1: Generación de archivos de caracteres y de pedigrí"
format: html
---

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(tidyverse)
```

<!--
NOTA: Se importan los conjuntos de datos para todos los caracteres a considerar.
-->

```{r}
#| label: Importación de conjuntos de datos

# Se importa los datos de los caracteres peso y crecimiento a los 365 día de edad ----

dat_pc305 <- read_delim(file = 'eva_genetica/Datos/datPuros/AnimalesDatoPURO.txt', col_names = FALSE, delim = ' ') |>
  rename(
    P365 = X1,
    C365 = X2,
    Peso_ent = X3,
    Dia_cebo = X4,
    Edad_pc305 = X5,
    GC_pc305 = X6,
    ID = X7
    ) # En este conjunto de datos, la primera columna representa el peso a los 365 días, la segunda columna al crecimiento a los 365 días, la tercera columna al peso de entrada, la cuarta columna a los días de cebo, la quinta columna al grupo de edad, la sexta columna al grupo de comparación y la sexta columna corresponde a la ID del animal.

dat_pc305 %>%
  summarise_all(~n_distinct(.)) # Se cuenta aquí el número de niveles de cada columna.

# NOTA: A continuación de describen algunas de las variables del objeto anterior (dat_pc305):
#
# 1. Grupos de comparación (GC_pc305): Estos se difinieron dentro del cebadero como cebadero - año - mes de entrada al cebadero. El número mínimo de animales exigido por grupo de comparación fue de cinco observaciones.
#
# 2. Grupo de edad (GC_pc305): Se difinieron dos grupos de edades en función de si tenían menos de 247 días a la entrada en el cebadero o si su edad era mayor.

# Se importa los datos del caracter peso al destete ----

dat_pdtte <- read_delim(file = 'eva_genetica/Datos/datPuros/DatosDestete_FICT.txt', col_names = FALSE, delim = ' ') |>
  rename(
    Pdtte = X1,
    Edad_pdtte = X2,
    Sexo_pdtte = X3,
    Edad_madre_pdtte = X4,
    GC_pdtte = X5,
    ID = X6
    ) # En este conjunto de datos, la primera columna representa al peso al destete, la segunda columna a la edad al destete, la tercera columna el sexo del individuo, la cuarta a la edad de la madre, la quinta al grupo de comparación y la sexta corresponde a la ID del animal.

dat_pdtte %>%
  summarise_all(~n_distinct(.)) # Se cuenta aquí el número de niveles de cada columna.

# NOTA: A continuación de describen algunas de las variables del objeto anterior (dat_pdtte):
#
# 1. Grupos de comparación (GC_pdtte): Estos fueron definidos dentro de las ganaderías por técnicas de clusters. Esta técnica se basa en las distancias entre fechas de nacimiento de los terneros dentro de una misma ganadería. La distancia máxima permitida por grupo está establecida en 90 días. La distancia mínima dentro de grupo se fijó a 30 días y se estableció un número mínimo de animales por grupo de cinco.
#
# 2. Edad de la madre al parto (Edad_madre_pdtte): Aquí, las vacas se agruparon en seis grupos de edades (2.5, de 3.5, de 4.5, de entre 4.5 y 9.5 años, y mayores de 9.5 años ¿Es que no dan seis grupos?).

# Se importa los datos de los caracteres peso y rendimiento a la canal ----

dat_prc <- read_delim(file = 'eva_genetica/Datos/datPuros/DatosPesoRendimiento_valora_PurosSep23.txt', col_names = FALSE, delim = ' ') |>
  rename(
    PC = X1,
    RC = X2,
    Sexo_prc = X3,
    Edad_prc = X4,
    GC_PC = X5,
    GC_RC = X6,
    ID = X7
    ) # En este conjunto de datos, la primera columna representa al peso a la canal, la segunda columna al rendimiento a la canal, la tercera columna el sexo del individuo, la cuarta columna a la edad en la canal, la quinta columna el grupo de comparación para el peso a la canal, la sexta columna el grupo contemporaneo para el rendimiento a la canal y la séptima columna corresponde a la ID del animal.

dat_prc %>%
  summarise_all(~n_distinct(.)) # Se cuenta aquí el número de niveles de cada columna.

# NOTA: A continuación de describen algunas de las variables del objeto anterior (dat_prc):
#
# 1. Grupos de comparación (GC_PC y GC_RC): Este se definio como cebadero - matadero - año de sacrificio, e indica el conjunto de animales que se han cebado y sacrificado en el mismo año. Ambos caracteres tienen los mismos grupos para cada animal, sin embargo el caracter rendimiento a la canal (RC) tiene menor número de observaciones (GC_RC = 271) debido a que hay valores en 0 (o NA) para este caracter.
#
# 2. Edad a la canal (Edad_prc): Se definieron tres niveles (≤ 12.3 meses; > 12.3 meses y ≤ 15.1 meses; y > 15.1 meses).

# Se importa los datos de los caracteres edad al primer parto e intervalo entre partos (parto 1 a parto 2) ----

dat_EPP_IEP <- read_delim(file = 'eva_genetica/Datos/datPuros/DatosEPPIPP.txt', col_names = FALSE, delim = ' ') |>
  rename(
    EPP = X1,
    IEP = X2,
    Sexo_P1 = X3, # Este es el sexo de la cría en el primer parto.
    Edad_toro_P1 = X4,
    GC_EPP = X5,
    ID_toro_EPP = X6,
    Sexo_P2 = X7, # Este es el sexo de la cría en el segundo parto.
    EPP_IEP = X8,
    Edad_toro_P2 = X9,
    Raza_toro = X10,
    GC_IEP = X11,
    ID_toro_IEP = X12,
    ID = X13
    ) # En este conjunto de datos, la primera columna representa la edad al primer parto, la segunda al intervalo entre parto, la tercera al sexo para la edad al primer parto, la cuarta la edad del toro en el primer parto, la quinta al grupo de comparación para la edad al primer parto, la sexta la ID del padre, la séptima al sexo para el intervalo entre parto, la octava a la edad al primer parto para el intervalo entre parto, la novena a la edad del toro en el segundo parto, la decima a la raza del toro, la onceava al grupo de comparación para el intervalo entre parto, la doceava a la ID del padre y la treceava a la ID del animal.

dat_EPP_IEP %>%
  summarise_all(~n_distinct(.)) # Se cuenta aquí el número de niveles de cada columna.

# NOTA: A continuación de describen algunas de las variables del objeto anterior (dat_EPP_IEP):
#
# 1. Grupos de comparación (GC_EPP y GC_IEP): Este indica, para ambos caracteres (EPP e IPP), el efecto ambiental común para todas las hembras que tienen el primer parto en la misma ganadería y periodo. El número mínimo de hembras por grupo fue de tres.
#
# 2. Sexo de la descendencia (Sexo_P1 y Sexo_P2): Este representa al sexo de la cría de acuerdo al parto. Sexo_P1 para el primer parto y Sexo_P2 para el segundo parto.
#
# 3. Edad al primer parto como efecto para IEP (EPP_IEP): Este corresponde a la edad al primer parto de la hembra clasificada en tres grupos (< a 2.5 años de edad, >= a 2.5 años y <= a 3 años, y > a 3 años).
#
# 4. Raza del toro (Raza_toro): Este indica la raza del toro (Avileña-Negra Ibérica, Charolés y Limusín).
#
# 5. Efecto ambiental permanente del toro (ID_toro_EPP e ID_toro_IEP): Este representa la componente del toro que es común a todas las hembras que se cubren con el mismo reproductor.
#
# 6. Edad del toro (Edad_toro_P1 e Edad_toro_P2): Este indica la edad del toro al nacimiento de la descendencia. Se clasificó en 5 grupos (< de 3 años, >= a 3 años y < a 4 años, >= a 4 años y < a 5 años, >= a 5 años y < a 6 años, y > a 6 años). Edad_toro_P1 indica la edad del toro en el primer parto y Edad_toro_P2 en el segundo parto.
```

<!--
NOTA: A continuación, usando el objeto "datPed", se renumera la ID de los individuos, padres y madres, con el fin de que queden como enteros.
-->

```{r}
#| label: Renumeración del pedigrí

# Se importa el conjunto de datos de genealogía ----

# Se importa los datos donde se extraera la genealogía (pedigrí) ----

datPed <- read_delim(file = 'eva_genetica/Datos/datPuros/genSEP23cIoficial.csv', col_names = TRUE) |>
  rename(
    id = Animal,
    sire = Padre,
    dam = Madre
    ) |>
  relocate(
    sire,
    .after = dam
    ) |>
  mutate(
    sire = replace(sire, sire == 0, NA),
    dam = replace(dam, dam == 0, NA)
    ) |>
  select('id':'sire')

# Se usa la función fixPedigree() del paquete pedantics para reordenar los datos del pedigrí ----

id_renum <- pedantics::fixPedigree(datPed) |> # Con la función fixPedigree() se retorna un pedigrí, en el que se reordenan los datos iniciando con aquellos individuos que no tienen información de progenitores. En caso de que en la primera columna aparezca mayor número de individuos, es que en el pedigrí original (denominado anteriormente como "datPed_2") habian padres (sire) y madres (dam) que no aparecian como hijos o hijas.
  mutate(id_renum = row_number()) |> # Se crea una columna denominada "Animal", que corresponde a una nueva numeración de acuerdo al orden generado con la función fixPedigree().
  dplyr::select(id, id_renum) # Se elogen estas dos columnas con el id original y el id renumerado (id_renum).

# Se unen ambos conjuntos de datos (datPed y id_renum) para obtener un conjunto de datos con individuos renumerados ----

datPed_2 <- left_join(x = datPed, y = id_renum, by = 'id') |>
  relocate(
    id_renum,
    .after = id
    )

datPed_2 |> group_by(id_renum) |> dplyr::filter(n() > 1) # Se verifica y no hay identificaciones renumeradas "id_renum" repetidas.

# Se renumeran también las madres (dam_renum) ----

dam_renum <- id_renum |>
  rename(
    dam = id,
    dam_renum = id_renum
    ) 

datPed_3 <- datPed_2 |>
  right_join(x = dam_renum, by = 'dam')

datPed_3 |>
  distinct(dam_renum) |>
  filter(!is.na(dam_renum)) |>
  count() # Hay 74746 madres (vacas).

datPed_3 |> filter(!is.na(dam_renum))|> summarise(n_hijos = n(), .by = dam_renum) |> arrange(n_hijos) |> slice_tail(n = 4) # La madre "109253" es la de mayor cantidad de crías con 21.

datPed_3 |> filter(dam_renum == 109253) |> select(dam) |> distinct() # Se mira la id original de la madre "109253".

datPed |> filter(dam == 'AG-94004') # Se comprueba, y la madre "109253" (AG-94004 su id original) si tiene 16 crías.

# Se renumeran también los padres (sire_renum) ----

sire_renum <- id_renum |>
  rename(
    sire = id,
    sire_renum = id_renum
    ) 

datPed_4 <- datPed_3 |>
  right_join(x = sire_renum, by = 'sire')

datPed_4 |> filter(!is.na(sire_renum))|> summarise(n_hijos = n(), .by = sire_renum) |> arrange(n_hijos) |> slice_tail(n = 4) # El padre "224551" es el de mayor cantidad de crías con 811.

datPed_4 |> filter(sire_renum == 224551) |> select(sire) |> distinct() # Se mira la id original del padre "109253".

datPed |> filter(sire == 'EJ-12036') # Se comprueba, y el padre "224551" (EJ-12036 su id original) se repite 811 por lo que si tiene este mismo número de crías.

# Se seleccionan las columnas que corresponden a la ID del individuos, del madre y del padre ----

datPed_5 <- datPed_4 |>
  dplyr::select(id, dam, sire) # Este conjunto de datos se usara más adelante para "prunear" o podar y generar un pedigrí basado en individuos con fenotipos.
```

<!--
NOTA: Se unen los conjuntos de datos de los caracteres peso al destete y edad al primer parto e intervalo entre el primer y segundo parto anteriormente importados.
-->

```{r}
#| label: Unión de conjuntos de datos

# Se unen los conjuntos de datos de peso al destete y de edad al primer parto e intervalo primer y segundo parto ----

datProd <- full_join(x = dat_EPP_IEP, y = dat_pdtte, by = 'ID')

datProd |>
  summarise(n = n(), .by = ID) |>
  filter(n > 1) # Se comprueba y aquí la ID del individuo no se repite.

# Se une el objeto anterior (datPed_5) con el objeto "datProd" ----

datProd_2 <- datPed_5 |>
  dplyr::select(id) |>
  rename(ID = id) |>
  inner_join(x = datProd, by = 'ID') |>
  relocate(
    ID,
    .before = EPP
    )

datProd_2 |>
  summarise(n = n(), .by = ID) |>
  filter(n > 1) # Se comprueba y aquí la id_renum del individuo no se repite.
```

<!--
NOTA: A continuación, se genera un pedigrí basado en individuos con fenotipos. Así, se eliminan individuos que no están emparentados con los individuos con fenotipo.
-->

```{r}
#| label: Generación de pedigrí con base en información fenotípica

# Se genera el pedigrí incluyendo indviduos fundadores ----

ped <- nadiv::prepPed(pedigree = datPed_5, check = TRUE) # En "pedigree" se indica un objeto en el cual las primeras tres columnas deben corresponder a ID del individuo, de la madre y del padre, en este orden (Los padres faltantes (por ejemplo, población base) deben indicarse con NA, 0 o *). En "check" se indica TRUE si se quisiera realizar controles sobre la validez de la estructura genealógica (intenta identificar cualquier problema relacionado con la notación de los valores faltantes y la validez del pedigrí básico para su posterior procesamiento). En general, la función prepPed() toma un objeto con las primeras tres columnas con una estructura de pedigrí (ID | ID_m | ID_p), agrega los fundadores que faltan y luego ordena el pedigrí.

slice_head(ped, n = 10)

datPed_5 |> filter(dam == '1B-10A') # Al ver los primeros diez individuos en el objeto anterior, el "id" 1B-10A tiene como "dam" y "sire" NA. Luego, se puede ver que el individuo 1B-10A aparece como madre, por lo que parece que es un individuo fundador.

# Se genera el pedigrí con base en información fenotípica ----

pedPrune <- nadiv::prunePed(pedigree = ped, phenotyped = datProd_2$ID) # La función prunePed() elimina (o poda) a los individuos que no son ancestros de individuos fenotipados. En "pedigree" se indica un objeto donde las primeras tres columnas corresponde a ID | ID_m | ID_p, y en "phenotyped" un vector donde se indique que individuos del pedigrí tiene fenotipo. Esta función se creo debido a que según sus desarrolladores "a menudo, los modelos de efectos mixtos se ejecutan mucho más rápido cuando se elimina información superflua antes de ejecutar el modelo. Esto es particularmente cierto cuando se reduce el número de efectos aleatorios asociados con una matriz de relaciones construida a partir de un pedigrí".

pedPrune |> filter(dam == '1B-10A') # Se observa de nuevo el mismo individuo 1B-10A como madre en el objeto "pedPrune". Al comparar el tamaño de los objetos "ped" y "pedPrune" se observa mucho menos individuos en "predPrune" debido a que en este último se obtuvo un pedigrí con sólo los individuos que tenian información fenotípica.
```

<!--
NOTA: A continuaicón se realizan algunas comprobaciones.
-->

```{r}
#| label: Comprobaciones

# Se comprueba que las madres de los indivdiuos eliminados siguen siendo madres de los individuos que no se eliminaron ----

ped_Prueba <- anti_join(x = ped, y = pedPrune, by = 'id') # Son 194374 individuos que se eliminaron al no tener fenotipo.

ped_Prueba |> slice_tail(n = 12)

set.seed(1234)

ped_Prueba_2 <- ped_Prueba |>
  distinct(dam) |>
  #count() # De los 194374 individuos eliminados, hay en total 65550 madres.
  sample_n(size = 8) # Elijo al azar 4 madres.

ped_Prueba_3 <- pedPrune |>
  filter(dam %in% ped_Prueba_2$dam)

# Se comprueba que las madres de los indivdiuos antes y después de la poda siguen siendo los mismos. Esto con el proposito de verificar que los terneros/as que están en el archivo de datos de pesos al destete no pierden su madre al generar el pedigrí: el peso al destete es un carácter que representa dos genotipos, el del ternero (potencial para crecer) y el de la madre (aptitud materna). Si se eliminan las madres de los datos se puede generar una heterogeneidad de residuos que no se modeliza, y esto puede dificultar los análisis ----

ped_Prueba <- pedPrune |>
  rename(
    dam_prune = dam,
    sire_prune = sire
    ) |>
  left_join(y = datPed, by = 'id')

ped_Prueba |> slice_tail(n = 12)

ped_Prueba_2 <- ped_Prueba %>%
  mutate_all(~if_else(is.na(.), as.factor(0), .)) |>
  mutate(
    Comparación = case_when(
      dam == dam_prune ~ 'Iguales',
      TRUE ~ 'Diferentes'
      )
    )

ped_Prueba_2 |> slice_tail(n = 12)

ped_Prueba_2 |>
  filter(Comparación == 'Diferentes') |>
  slice_head(n = 12)
```

<!--
NOTA: A continuación, se exportan los conjuntos de datos con información fenotípica y de pedigrí o genealogíca.
-->

```{r}
#| label: Exportación de conjuntos de datos

# Exportación de conjuntos de datos de pedigrí (o genealogíca) ----

pedPrune |>
  mutate_all(~if_else(is.na(.), as.factor(0), .)) |> # Se convierten los valores NA a 0.
  relocate(
    sire,
    .before = dam
    ) |> # Se cambia el orden para que quede una estructura de pedigrí como lo requiere el programa blupf90 (ID | ID_p | ID_m). 
  write_delim(file = 'eva_genetica/Datos/eva_genomica/Pedigri.txt', col_names = FALSE, delim = ' ')

pedPrune |>
  summarise_all(~n_distinct(.)) # Se cuenta el número de niveles de cada columna de "pedPrune".

# Exportación de conjuntos de datos de fenotipos ----

datProd_2 |>
  mutate_all(function(x) if_else(is.na(x), as.factor(0), as.character(x))) |> # Se convierten los valores NA a 0.
  write_delim(file = 'eva_genetica/Datos/eva_genomica/Fenotipos.txt', col_names = FALSE, delim = ' ')
```
