---
title: "Parte 7: Generación de archivos de genotipos y de fenotipos (datos completos y parciales) en genotipado de HD imputado y que corresponden a SNP-tags"
format: html
---

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(tidyverse)
```

<!--
NOTA: Se importa el conjunto de datos con todos los caracteres y se asigna el nombre a las columnas.
-->

```{r}
#| label: Datos de caracteres

datProd <- read_delim(file = 'eva_genetica/Datos/Fenotipos.txt', col_names = FALSE, delim = ' ') |>
  rename(
    ID = X1,
    id_renum = X2,
    P365 = X3,
    C365 = X4,
    Peso_ent = X5,
    Dia_cebo = X6,
    Edad_pc365 = X7,
    GC_pc365 = X8,
    Pdtte = X9,
    Edad_pdtte = X10,
    Sexo_pdtte = X11,
    Edad_madre_pdtte = X12,
    GC_pdtte = X13,
    PC = X14,
    RC = X15,
    Sexo_prc = X16,
    Edad_prc = X17,
    GC_PC = X18,
    GC_RC = X19,
    EPP = X20,
    IEP = X21,
    Sexo_P1 = X22,
    Edad_toro_P1 = X23,
    GC_EPP = X24,
    ID_toro_EPP = X25,
    Sexo_P2 = X26,
    EPP_IEP = X27,
    Edad_toro_P2 = X28,
    Raza_toro = X29,
    GC_IEP = X30,
    ID_toro_IEP = X31
    )
```

<!--
NOTA: Se crea el conjunto de datos de genotipos para cada caracter.
-->

```{r}
#| label: Genotipos para cada caracter

# Se importa el conjunto de datos de genotipos editado como resultado de la imputación a densidad alta y que corresponden a SNP-tags con Beagle v. 5.4 ----

datGeno <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/resSNP_tags.txt', delim = ' ', col_names = FALSE) |>
  rename(
    ID_ofi = X1,
    Geno = X2
    )

datGeno |> slice_head(n = 4)

dim_desc(datGeno) # Existen 2970 individuos genotipados.

# Se importa el conjunto de datos con la información del pedigrí ----

Ped <- read_delim(file = 'eva_genetica/Datos/Pedigri.txt', col_names = FALSE, delim = ' ', col_selec = c(X1)) |>
  rename(ID = X1) # Se importa el conjunto de datos de pedigrí

#################
# Peso al destete
#################

pDtte <- datProd |>
  filter(Pdtte != 0) |> # Se quitan los pesos al destete con valores de 0. En total hay 64519 individuos con registro de peso al destete.
  select(ID)

# Se importa el conjunto de datos con el libro genealogíco para así obtener un conjunto de datos con las dos identificaciones (ID | ID_ofi) ----

ID_ind <- read_csv2(file = 'eva_genetica/Datos/datPuros/genSEP23cIoficial.csv', col_names = TRUE) 

ID_ind_2 <- ID_ind |> # Este conjunto de datos contiene la ID de los individuos y la ID oficial.
  select(1, 6) |>
  rename(
    ID = Animal,
    ID_ofi = Ioficial
    ) |>
  right_join(y = pDtte, by = 'ID') # Se unen los objetos con el fin de obtener un conjunto de datos con las dos identificaciones: ID | | ID_ofi.

# Se exporta el conjunto de datos de genotipos ----

datGeno_2 <- datGeno |>
  inner_join(y = ID_ind_2, by = 'ID_ofi') |>
  relocate(
    ID,
    .before = Geno
    ) |>
  #distinct(ID) |> summarise(n = n()) # Hay 2174 con genotipo e información de peso al destete de los 2970 individuos genotipados.
  select(-ID_ofi)

datGeno_2 |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_Dtte/genoPdtte.txt', col_names = FALSE)

# NOTA: Según el manual del programa blupf0 "los dos campos (ID de animal y SNP) deben estar separados por al menos un espacio, y el campo 2 debe tener un formato fijo (es decir, todas las filas de genotipos deben comenzar en el mismo número o posición de columna)". Por esta razón, en la terminal de linux se coloco este codigo: awk '{printf "%-10s%s\n", $1, $2}' genoPdtte.txt > genoPdtte_2.txt. Este comando formateará los datos en el archivo de tal manera que la primera columna tenga un ancho fijo de 10 caracteres y la segunda columna comience inmediatamente después de la primera columna, asegurando que todas las filas comiencen en la misma posición.

# Se observa el número de pesos al destete registado en cada año de nacimiento ----

ID_ind_3 <- ID_ind |> # Del conjunto de datos anterior del libro genealogíco se extrae la fecha de nacimiento para así obtener el año de nacimiento de los individuos.
  rename(
    ID = Animal,
    fec_Nac = Fnac
    ) |>
  right_join(y = Ped, by = 'ID') |>
  mutate(año_Nac = year(fec_Nac)) # Se extrae el año de nacimiento.

ID_ind_3 |>
  summarise(n = n(), .by = ID) |>
  filter(n > 1) # Se comprueba y aquí la ID del individuo no se repite.

datGeno_3 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  summarise(n = n(), .by = 'año_Nac') |>
  arrange(año_Nac) #|>
  #slice_tail(n = 4)

summarise(
  .data = datGeno_3,
  across(
    .cols = n,
    .fns = sum,
    na.rm = TRUE
    )
  ) # Hay 2174 individuos con datos de peso al destete y genotipados, divididos en años de nacimiento.

datGeno_3 |> slice_tail(n = 10) # Se eligen los individuos nacidos en los años 2017, 2018 y 2019 como a los individuos a los que su fenotipo se les enmascarará. Suman en total 62+ 126 + 32 = 220 individuos.

ID_ind_3 |> summarise(n = n(), .by = 'año_Nac') |> filter(año_Nac %in% c(2017, 2018, 2019)) # Se observa aquí el total de individuos con datos para los años anteriores.

datGeno_4 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  filter(año_Nac %in% c(2017, 2018, 2019)) |>
  pull(ID) # Se extrae la ID de los individuos a los que se enmascarará su fenotipo.

######################
# Edad al primer parto
######################

EPP <- datProd |>
  filter(EPP != 0) |> # Se quitan las edades al primer parto con valores de 0. En total hay 34512 individuos con registro de peso al destete.
  select(ID)

# Se importa el conjunto de datos con el libro genealogíco para así obtener un conjunto de datos con las dos identificaciones (ID | ID_ofi) ----

ID_ind <- read_csv2(file = 'eva_genetica/Datos/datPuros/genSEP23cIoficial.csv', col_names = TRUE) 

ID_ind_2 <- ID_ind |> # Este conjunto de datos contiene la ID de los individuos y la ID oficial.
  select(1, 6) |>
  rename(
    ID = Animal,
    ID_ofi = Ioficial
    ) |>
  right_join(y = EPP, by = 'ID') # Se unen los objetos con el fin de obtener un conjunto de datos con las dos identificaciones: ID | | ID_ofi.

# Se exporta el conjunto de datos de genotipos ----

datGeno_2 <- datGeno |>
  inner_join(y = ID_ind_2, by = 'ID_ofi') |>
  relocate(
    ID,
    .before = Geno
    ) |>
  #distinct(ID) |> summarise(n = n()) # Hay 1972 con genotipo e información de edad al primer parto de los 2970 individuos genotipados.
  select(-ID_ofi)

datGeno_2 |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/Edad_Primer_Parto/genoEPP.txt', col_names = FALSE)

# Se observa el número de edades al primer parto registado en cada año de nacimiento ----

ID_ind_3 <- ID_ind |> # Del conjunto de datos anterior del libro genealogíco se extrae la fecha de nacimiento para así obtener el año de nacimiento de los individuos.
  rename(
    ID = Animal,
    fec_Nac = Fnac
    ) |>
  right_join(y = Ped, by = 'ID') |>
  mutate(año_Nac = year(fec_Nac)) # Se extrae el año de nacimiento.

ID_ind_3 |>
  summarise(n = n(), .by = ID) |>
  filter(n > 1) # Se comprueba y aquí la ID del individuo no se repite.

datGeno_3 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  summarise(n = n(), .by = 'año_Nac') |>
  arrange(año_Nac) #|>
  #slice_tail(n = 4)

summarise(
  .data = datGeno_3,
  across(
    .cols = n,
    .fns = sum,
    na.rm = TRUE
    )
  ) # Hay 1972 individuos con datos de edad al primer parto y genotipados, divididos en años de nacimiento.

datGeno_3 |> slice_tail(n = 10) # Se eligen los individuos nacidos en los años 2017, 2018 y 2019 como a los individuos a los que su fenotipo se les enmascarará. Suman en total 61+ 97 + 31 = 189 individuos.

ID_ind_3 |> summarise(n = n(), .by = 'año_Nac') |> filter(año_Nac %in% c(2017, 2018, 2019)) # Se observa aquí el total de individuos con datos para los años anteriores.

datGeno_4 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  filter(año_Nac %in% c(2017, 2018, 2019)) |>
  pull(ID) # Se extrae la ID de los individuos a los que se enmascarará su fenotipo.

###########################################
# Intervalo entre el primer y segundo parto
###########################################

IEP <- datProd |>
  filter(IEP != 0) |> # Se quitan los pesos al destete con valores de 0. En total hay 16726 individuos con registro de intervalo entre el primer y segundo parto.
  select(ID)

# Se importa el conjunto de datos con el libro genealogíco para así obtener un conjunto de datos con las dos identificaciones (ID | ID_ofi) ----

ID_ind <- read_csv2(file = 'eva_genetica/Datos/datPuros/genSEP23cIoficial.csv', col_names = TRUE) 

ID_ind_2 <- ID_ind |> # Este conjunto de datos contiene la ID de los individuos y la ID oficial.
  select(1, 6) |>
  rename(
    ID = Animal,
    ID_ofi = Ioficial
    ) |>
  right_join(y = IEP, by = 'ID') # Se unen los objetos con el fin de obtener un conjunto de datos con las dos identificaciones: ID | | ID_ofi.

# Se exporta el conjunto de datos de genotipos ----

datGeno_2 <- datGeno |>
  inner_join(y = ID_ind_2, by = 'ID_ofi') |>
  relocate(
    ID,
    .before = Geno
    ) |>
  #distinct(ID) |> summarise(n = n()) # Hay 1333 con genotipo e información de intervalor parto uno y dos de los 2970 individuos genotipados.
  select(-ID_ofi)

datGeno_2 |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/intervalo_P1_P2/genoIEP.txt', col_names = FALSE)

# Se observa el número de intervalos entre el primer y segundo parto registado en cada año de nacimiento ----

ID_ind_3 <- ID_ind |> # Del conjunto de datos anterior del libro genealogíco se extrae la fecha de nacimiento para así obtener el año de nacimiento de los individuos.
  rename(
    ID = Animal,
    fec_Nac = Fnac
    ) |>
  right_join(y = Ped, by = 'ID') |>
  mutate(año_Nac = year(fec_Nac)) # Se extrae el año de nacimiento.

ID_ind_3 |>
  summarise(n = n(), .by = ID) |>
  filter(n > 1) # Se comprueba y aquí la ID del individuo no se repite.

datGeno_3 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  summarise(n = n(), .by = 'año_Nac') |>
  arrange(año_Nac) #|>
  #slice_tail(n = 4)

summarise(
  .data = datGeno_3,
  across(
    .cols = n,
    .fns = sum,
    na.rm = TRUE
    )
  ) # Hay 1333 individuos con datos de inetervalo entre el primer y segundo parto y genotipados, divididos en años de nacimiento.

datGeno_3 |> slice_tail(n = 10) # Se eligen los individuos nacidos en los años 2017, 2018 y 2019 como a los individuos a los que su fenotipo se les enmascarará. Suman en total 43+ 68 + 20 = 131 individuos.

ID_ind_3 |> summarise(n = n(), .by = 'año_Nac') |> filter(año_Nac %in% c(2017, 2018, 2019)) # Se observa aquí el total de individuos con datos para los años anteriores.

datGeno_4 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  filter(año_Nac %in% c(2017, 2018, 2019)) |>
  pull(ID) # Se extrae la ID de los individuos a los que se enmascarará su fenotipo.

####################################################################
# Bi-carácter entre edad al primer parto e intervalo parto uno y dos
####################################################################

EPP_IEP <- datProd |>
  filter(EPP != 0 | IEP != 0)

EPP_IEP |> select(ID, EPP, IEP) |> filter(ID %in% c('AB-11038', 'AB-11039', 'AB-12006', 'AB-12008')) # Se observan estos individuos para ver si se dejaron individuos con registro en un carácter pero en el otro no.

EPP_IEP <- EPP_IEP |>
  select(ID)

# Se importa el conjunto de datos con el libro genealogíco para así obtener un conjunto de datos con las dos identificaciones (ID | ID_ofi) ----

ID_ind <- read_csv2(file = 'eva_genetica/Datos/datPuros/genSEP23cIoficial.csv', col_names = TRUE) 

ID_ind_2 <- ID_ind |> # Este conjunto de datos contiene la ID de los individuos y la ID oficial.
  select(1, 6) |>
  rename(
    ID = Animal,
    ID_ofi = Ioficial
    ) |>
  right_join(y = EPP_IEP, by = 'ID') # Se unen los objetos con el fin de obtener un conjunto de datos con las dos identificaciones: ID | | ID_ofi.

# Se exporta el conjunto de datos de genotipos ----

datGeno_2 <- datGeno |>
  inner_join(y = ID_ind_2, by = 'ID_ofi') |>
  relocate(
    ID,
    .before = Geno
    ) |>
  #distinct(ID) |> summarise(n = n()) # Hay 1973 con genotipo e información de edad al primer parto e intervalo parto uno y dos de los 2970 individuos genotipados.
  select(-ID_ofi)

datGeno_2 |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/EPP_IEP/genoEPP_IEP.txt', col_names = FALSE)

#############################
# Peso a los 365 días de edad
#############################

P365 <- datProd |>
  filter(P365 != 0) |> # Se quitan los pesos a los 365 días de edad con valores de 0. En total hay 15335 individuos con registro de peso a los 365 días de edad.
  select(ID)

# Se importa el conjunto de datos con el libro genealogíco para así obtener un conjunto de datos con las dos identificaciones (ID | ID_ofi) ----

ID_ind <- read_csv2(file = 'eva_genetica/Datos/datPuros/genSEP23cIoficial.csv', col_names = TRUE) 

ID_ind_2 <- ID_ind |> # Este conjunto de datos contiene la ID de los individuos y la ID oficial.
  select(1, 6) |>
  rename(
    ID = Animal,
    ID_ofi = Ioficial
    ) |>
  right_join(y = P365, by = 'ID') # Se unen los objetos con el fin de obtener un conjunto de datos con las dos identificaciones: ID | | ID_ofi.

# Se exporta el conjunto de datos de genotipos ----

datGeno_2 <- datGeno |>
  inner_join(y = ID_ind_2, by = 'ID_ofi') |>
  relocate(
    ID,
    .before = Geno
    ) |>
  #distinct(ID) |> summarise(n = n()) # Hay 28 con genotipo e información de peso a los 365 días de edad de los 2970 individuos genotipados.
  select(-ID_ofi)

datGeno_2 |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_365/genoP365.txt', col_names = FALSE)

# Se observa el número de pesos a los 365 días de edad registado en cada año de nacimiento ----

ID_ind_3 <- ID_ind |> # Del conjunto de datos anterior del libro genealogíco se extrae la fecha de nacimiento para así obtener el año de nacimiento de los individuos.
  rename(
    ID = Animal,
    fec_Nac = Fnac
    ) |>
  right_join(y = Ped, by = 'ID') |>
  mutate(año_Nac = year(fec_Nac)) # Se extrae el año de nacimiento.

ID_ind_3 |>
  summarise(n = n(), .by = ID) |>
  filter(n > 1) # Se comprueba y aquí la ID del individuo no se repite.

datGeno_3 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  summarise(n = n(), .by = 'año_Nac') |>
  arrange(año_Nac) #|>
  #slice_tail(n = 4)

summarise(
  .data = datGeno_3,
  across(
    .cols = n,
    .fns = sum,
    na.rm = TRUE
    )
  ) # Hay 28 individuos con datos de peso a los 365 días de edad y genotipados, divididos en años de nacimiento.

datGeno_3 |> slice_tail(n = 10) # Se eligen los individuos nacidos en los años 2016, 2017 y 2018 como a los individuos a los que su fenotipo se les enmascarará. Suman en total 2 + 1 + 4 = 7 individuos.

ID_ind_3 |> summarise(n = n(), .by = 'año_Nac') |> filter(año_Nac %in% c(2016, 2017, 2018)) # Se observa aquí el total de individuos con datos para los años anteriores.

datGeno_4 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  filter(año_Nac %in% c(2016, 2017, 2018)) |>
  pull(ID) # Se extrae la ID de los individuos a los que se enmascarará su fenotipo.

####################################
# Crecimiento a los 365 días de edad
####################################

C365 <- datProd |>
  filter(C365 != 0) |> # Se quitan los pesos a los 365 días de edad con valores de 0. En total hay 15335 individuos con registro de crecimiento a los 365 días de edad.
  select(ID)

# Se importa el conjunto de datos con el libro genealogíco para así obtener un conjunto de datos con las dos identificaciones (ID | ID_ofi) ----

ID_ind <- read_csv2(file = 'eva_genetica/Datos/datPuros/genSEP23cIoficial.csv', col_names = TRUE) 

ID_ind_2 <- ID_ind |> # Este conjunto de datos contiene la ID de los individuos y la ID oficial.
  select(1, 6) |>
  rename(
    ID = Animal,
    ID_ofi = Ioficial
    ) |>
  right_join(y = C365, by = 'ID') # Se unen los objetos con el fin de obtener un conjunto de datos con las dos identificaciones: ID | | ID_ofi.

# Se exporta el conjunto de datos de genotipos ----

datGeno_2 <- datGeno |>
  inner_join(y = ID_ind_2, by = 'ID_ofi') |>
  relocate(
    ID,
    .before = Geno
    ) |>
  #distinct(ID) |> summarise(n = n()) # Hay 28 con genotipo e información de crecimiento a los 365 días de edad de los 2970 individuos genotipados.
  select(-ID_ofi)

datGeno_2 |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/crecimiento_365/genoC365.txt', col_names = FALSE)

# Se observa el número de crecimientos a los 365 días de edad registado en cada año de nacimiento ----

ID_ind_3 <- ID_ind |> # Del conjunto de datos anterior del libro genealogíco se extrae la fecha de nacimiento para así obtener el año de nacimiento de los individuos.
  rename(
    ID = Animal,
    fec_Nac = Fnac
    ) |>
  right_join(y = Ped, by = 'ID') |>
  mutate(año_Nac = year(fec_Nac)) # Se extrae el año de nacimiento.

ID_ind_3 |>
  summarise(n = n(), .by = ID) |>
  filter(n > 1) # Se comprueba y aquí la ID del individuo no se repite.

datGeno_3 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  summarise(n = n(), .by = 'año_Nac') |>
  arrange(año_Nac) #|>
  #slice_tail(n = 4)

summarise(
  .data = datGeno_3,
  across(
    .cols = n,
    .fns = sum,
    na.rm = TRUE
    )
  ) # Hay 28 individuos con datos de crecimiento a los 365 días de edad y genotipados, divididos en años de nacimiento.

datGeno_3 |> slice_tail(n = 10) # Se eligen los individuos nacidos en los años 2016, 2017 y 2018 como a los individuos a los que su fenotipo se les enmascarará. Suman en total 2 + 1 + 4 = 7 individuos.

ID_ind_3 |> summarise(n = n(), .by = 'año_Nac') |> filter(año_Nac %in% c(2016, 2017, 2018)) # Se observa aquí el total de individuos con datos para los años anteriores.

datGeno_4 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  filter(año_Nac %in% c(2016, 2017, 2018)) |>
  pull(ID) # Se extrae la ID de los individuos a los que se enmascarará su fenotipo.

#############################################################
# Bi-carácter entre peso y crecimiento a los 365 días de edad
#############################################################

P365_C365 <- datProd |>
  filter(P365 != 0 | C365 != 0) |> # Estos dos caracteres, a diferencia del bi-carácter anterior entre edad al primer parto e intervalo parto uno y dos, tienen los mismos registros. Es decir, no falta un registro en unos de los caraceres mientras que el otro si lo tiene, contrario al bi-carácter anterior.
  select(ID)

# Se importa el conjunto de datos con el libro genealogíco para así obtener un conjunto de datos con las dos identificaciones (ID | ID_ofi) ----

ID_ind <- read_csv2(file = 'eva_genetica/Datos/datPuros/genSEP23cIoficial.csv', col_names = TRUE) 

ID_ind_2 <- ID_ind |> # Este conjunto de datos contiene la ID de los individuos y la ID oficial.
  select(1, 6) |>
  rename(
    ID = Animal,
    ID_ofi = Ioficial
    ) |>
  right_join(y = P365_C365, by = 'ID') # Se unen los objetos con el fin de obtener un conjunto de datos con las dos identificaciones: ID | | ID_ofi.

# Se exporta el conjunto de datos de genotipos ----

datGeno_2 <- datGeno |>
  inner_join(y = ID_ind_2, by = 'ID_ofi') |>
  relocate(
    ID,
    .before = Geno
    ) |>
  #distinct(ID) |> summarise(n = n()) # Hay 28 con genotipo e información de peso y crecimiento a los 365 días de edad de los 2970 individuos genotipados.
  select(-ID_ofi)

datGeno_2 |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/P365_C365/genoP365_C365.txt', col_names = FALSE)

#################
# Peso a la canal
#################

PC <- datProd |>
  filter(PC != 0) |> # Se quitan los pesos a la canal con valores de 0. En total hay 38975 individuos con registro de peso a la canal.
  select(ID)

# Se importa el conjunto de datos con el libro genealogíco para así obtener un conjunto de datos con las dos identificaciones (ID | ID_ofi) ----

ID_ind <- read_csv2(file = 'eva_genetica/Datos/datPuros/genSEP23cIoficial.csv', col_names = TRUE) 

ID_ind_2 <- ID_ind |> # Este conjunto de datos contiene la ID de los individuos y la ID oficial.
  select(1, 6) |>
  rename(
    ID = Animal,
    ID_ofi = Ioficial
    ) |>
  right_join(y = PC, by = 'ID') # Se unen los objetos con el fin de obtener un conjunto de datos con las dos identificaciones: ID | | ID_ofi.

# Se exporta el conjunto de datos de genotipos ----

datGeno_2 <- datGeno |>
  inner_join(y = ID_ind_2, by = 'ID_ofi') |>
  relocate(
    ID,
    .before = Geno
    ) |>
  #distinct(ID) |> summarise(n = n()) # Hay 13 con genotipo e información de peso a la canal de los 2970 individuos genotipados.
  select(-ID_ofi)

datGeno_2 |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_canal/genoPC.txt', col_names = FALSE)

# Se observa el número de pesos a la canal registado en cada año de nacimiento ----

ID_ind_3 <- ID_ind |> # Del conjunto de datos anterior del libro genealogíco se extrae la fecha de nacimiento para así obtener el año de nacimiento de los individuos.
  rename(
    ID = Animal,
    fec_Nac = Fnac
    ) |>
  right_join(y = Ped, by = 'ID') |>
  mutate(año_Nac = year(fec_Nac)) # Se extrae el año de nacimiento.

ID_ind_3 |>
  summarise(n = n(), .by = ID) |>
  filter(n > 1) # Se comprueba y aquí la ID del individuo no se repite.

datGeno_3 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  summarise(n = n(), .by = 'año_Nac') |>
  arrange(año_Nac) #|>
  #slice_tail(n = 4)

summarise(
  .data = datGeno_3,
  across(
    .cols = n,
    .fns = sum,
    na.rm = TRUE
    )
  ) # Hay 13 individuos con datos de peso en la canal y genotipados, divididos en años de nacimiento.

datGeno_3 |> slice_tail(n = 10) # Se eligen los individuos nacidos en los años 2010 y 2013 como a los individuos a los que su fenotipo se les enmascarará. Suman en total 2 + 1 = 3 individuos.

ID_ind_3 |> summarise(n = n(), .by = 'año_Nac') |> filter(año_Nac %in% c(2010, 2013)) # Se observa aquí el total de individuos con datos para los años anteriores.

datGeno_4 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  filter(año_Nac %in% c(2010, 2013)) |>
  pull(ID) # Se extrae la ID de los individuos a los que se enmascarará su fenotipo.

########################
# Rendimiento a la canal
########################

RC <- datProd |>
  filter(RC != 0) |> # Se quitan los rendimientos a la canal con valores de 0. En total hay 21314 individuos con registro de rendimiento a la canal.
  select(ID)

# Se importa el conjunto de datos con el libro genealogíco para así obtener un conjunto de datos con las dos identificaciones (ID | ID_ofi) ----

ID_ind <- read_csv2(file = 'eva_genetica/Datos/datPuros/genSEP23cIoficial.csv', col_names = TRUE) 

ID_ind_2 <- ID_ind |> # Este conjunto de datos contiene la ID de los individuos y la ID oficial.
  select(1, 6) |>
  rename(
    ID = Animal,
    ID_ofi = Ioficial
    ) |>
  right_join(y = RC, by = 'ID') # Se unen los objetos con el fin de obtener un conjunto de datos con las dos identificaciones: ID | | ID_ofi.

# Se exporta el conjunto de datos de genotipos ----

datGeno_2 <- datGeno |>
  inner_join(y = ID_ind_2, by = 'ID_ofi') |>
  relocate(
    ID,
    .before = Geno
    ) |>
  #distinct(ID) |> summarise(n = n()) # Hay 10 con genotipo e información de rendimiento a la canal de los 2970 individuos genotipados.
  select(-ID_ofi)

datGeno_2 |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/rendimiento_canal/genoRC.txt', col_names = FALSE)

# Se observa el número de pesos a la canal registado en cada año de nacimiento ----

ID_ind_3 <- ID_ind |> # Del conjunto de datos anterior del libro genealogíco se extrae la fecha de nacimiento para así obtener el año de nacimiento de los individuos.
  rename(
    ID = Animal,
    fec_Nac = Fnac
    ) |>
  right_join(y = Ped, by = 'ID') |>
  mutate(año_Nac = year(fec_Nac)) # Se extrae el año de nacimiento.

ID_ind_3 |>
  summarise(n = n(), .by = ID) |>
  filter(n > 1) # Se comprueba y aquí la ID del individuo no se repite.

datGeno_3 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  summarise(n = n(), .by = 'año_Nac') |>
  arrange(año_Nac) #|>
  #slice_tail(n = 4)

summarise(
  .data = datGeno_3,
  across(
    .cols = n,
    .fns = sum,
    na.rm = TRUE
    )
  ) # Hay 10 individuos con datos de rendimiento en la canal y genotipados, divididos en años de nacimiento.

datGeno_3 |> slice_tail(n = 10) # Se eligen los individuos nacidos en los años 2010 y 2013 como a los individuos a los que su fenotipo se les enmascarará. Suman en total 1 + 1 = 2 individuos.

ID_ind_3 |> summarise(n = n(), .by = 'año_Nac') |> filter(año_Nac %in% c(2010, 2013)) # Se observa aquí el total de individuos con datos para los años anteriores.

datGeno_4 <- datGeno_2 |>
  right_join(x = ID_ind_3, by = 'ID') |>
  filter(año_Nac %in% c(2010, 2013)) |>
  pull(ID) # Se extrae la ID de los individuos a los que se enmascarará su fenotipo.

##################################################
# Bi-carácter entre peso y rendimiento en la canal
##################################################

PC_RC <- datProd |>
  filter(PC != 0 | RC != 0)

PC_RC |> select(ID, PC, RC) |> slice_tail(n = 12) # Se observan estos individuos para ver si se dejaron individuos con registro en un carácter pero en el otro no.

PC_RC <- PC_RC |>
  select(ID)

# Se importa el conjunto de datos con el libro genealogíco para así obtener un conjunto de datos con las dos identificaciones (ID | ID_ofi) ----

ID_ind <- read_csv2(file = 'eva_genetica/Datos/datPuros/genSEP23cIoficial.csv', col_names = TRUE) 

ID_ind_2 <- ID_ind |> # Este conjunto de datos contiene la ID de los individuos y la ID oficial.
  select(1, 6) |>
  rename(
    ID = Animal,
    ID_ofi = Ioficial
    ) |>
  right_join(y = PC_RC, by = 'ID') # Se unen los objetos con el fin de obtener un conjunto de datos con las dos identificaciones: ID | | ID_ofi.

# Se exporta el conjunto de datos de genotipos ----

datGeno_2 <- datGeno |>
  inner_join(y = ID_ind_2, by = 'ID_ofi') |>
  relocate(
    ID,
    .before = Geno
    ) |>
  #distinct(ID) |> summarise(n = n()) # Hay 13 con genotipo e información de peso de la canal y rendimiento de la canal de los 2970 individuos genotipados.
  select(-ID_ofi)

datGeno_2 |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/PC_RC/genoPC_RC.txt', col_names = FALSE)
```

<!--
NOTA: Para cada caracter se generan los conjunto de datos completo y parcial.
-->

```{r}
#| label: Conjunto de datos completo y parcial para cada caracter

# Se importa el conjunto de datos de pedigrí ----

Ped <- read_delim(file = 'eva_genetica/Datos/Pedigri.txt', col_names = FALSE, delim = ' ', col_selec = c(X1)) |>
  rename(ID = X1)

# A los individuos del archivo de pedigrí anterior se les coloca su fecha de nacimiento y se extrae su año de nacimiento ----

ID_ind <- read_delim(file = 'eva_genetica/Datos/datPuros/genSEP23cIoficial.csv', col_names = TRUE, col_selec = c(Animal, Fnac)) |> # Se importa el conjunto de datos del libro genealogíco donde se extraera la fecha de nacimiento de los individuos.
  rename(
    ID = Animal,
    fec_Nac = Fnac
    ) |>
  right_join(y = Ped, by = 'ID') |>
  mutate(año_Nac = year(fec_Nac)) # Se extrae el año de nacimiento.

#################
# Peso al destete
#################

pDtte <- datProd |> 
  select(ID, id_renum, contains('pdtte')) |>
  filter(Pdtte != 0) # Se quitan los pesos al destete con valores de 0. En total hay 64519 individuos con registro de peso al destete.

pDtte_2 <- pDtte |>
  mutate(
    Pdtte_NA = case_when(
        ID %in% datGeno_4 ~ 0
        )
    ) |> # Se enmascara el peso al destete de los individuos en el objeto "datGeno_4".
  relocate(
    Pdtte_NA,
    .after = Pdtte
    )

pDtte_2 |> count(Pdtte_NA) # Hay 220 individuos con valores de 0 para el peso al destete, que corresponde a los años de nacimiento 2017, 2018 y 2019.

pDtte_3 <- pDtte_2 |>
  mutate(
    Pdtte_NA = case_when(
        is.na(Pdtte_NA) ~ Pdtte,
        TRUE ~ Pdtte_NA
        )
    ) # Se obtiene el conjunto de datos de peso al destete con datos completos y parciales para este caracter.

pDtte_3 |>
  filter(Pdtte_NA != 0) |>
  summarise(Mínimo = min(Pdtte_NA), Máximo = max(Pdtte_NA)) # Hay pesos al destete bajos y altos. El mínimo permitido por los ganaderos de Avileña es de 89.

pDtte_3 |>
  select(ID, Pdtte, ends_with('_pdtte')) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_Dtte/Completo/pDtte.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos completo.

pDtte_3 |>
  select(ID, Pdtte_NA, ends_with('_pdtte')) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_Dtte/Parcial/pDtte.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos parcial, a los que se les enmascaro el fenotipo.

######################
# Edad al primer parto
######################

EPP <- datProd |>
  select(ID, id_renum, Sexo_P1, Edad_toro_P1, contains('EPP'), -EPP_IEP) |>
  filter(EPP != 0) # Se quitan las edades al primer parto con valores de 0. En total hay 34512 individuos con registro de edad al primer parto.

EPP_2 <- EPP |>
  mutate(
    EPP_NA = case_when(
        ID %in% datGeno_4 ~ 0
        )
    ) |> # Se enmascara la edad al primer parto de los individuos en el objeto "datGeno_4".
  relocate(
    EPP_NA,
    .after = EPP
    )

EPP_2 |> count(EPP_NA) # Hay 189 individuos con valores de 0 para la edad al primer parto, que corresponde a los años de nacimiento 2017, 2018 y 2019.

EPP_3 <- EPP_2 |>
  mutate(
    EPP_NA = case_when(
        is.na(EPP_NA) ~ EPP,
        TRUE ~ EPP_NA
        )
    ) # Se obtiene el conjunto de datos edad al primer parto con datos completos y parciales para este caracter.

EPP_3 |>
  filter(EPP_NA != 0) |>
  summarise(Mínimo = min(EPP_NA), Máximo = max(EPP_NA))

EPP_3 |>
  select(ID, EPP, ends_with(c('_EPP', 'P1'))) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/Edad_Primer_Parto/Completo/EPP.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos completo.

EPP_3 |>
  select(ID, EPP_NA, ends_with(c('_EPP', 'P1'))) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/Edad_Primer_Parto/Parcial/EPP.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos parcial, a los que se les enmascaro el fenotipo.

###########################################
# Intervalo entre el primer y segundo parto
###########################################

IEP <- datProd |>
  select(ID, id_renum, Sexo_P2, Edad_toro_P2, Raza_toro, contains('IEP')) |>
  filter(IEP != 0) # Se quitan los intervalos parto uno y parto dos con valores de 0. En total hay 16726 individuos con registro de intervalor entre el primer y segundo parto.

IEP_2 <- IEP |>
  mutate(
    IEP_NA = case_when(
        ID %in% datGeno_4 ~ 0
        )
    ) |> # Se enmascara el peso al destete de los individuos en el objeto "datGeno_4".
  relocate(
    IEP_NA,
    .after = IEP
    )

IEP_2 |> count(IEP_NA) # Hay 131 individuos con valores de 0 para el intervalo entre el primer y segundo parto, que corresponde a los años de nacimiento 2017, 2018 y 2019.

IEP_3 <- IEP_2 |>
  mutate(
    IEP_NA = case_when(
        is.na(IEP_NA) ~ IEP,
        TRUE ~ IEP_NA
        )
    ) # Se obtiene el conjunto de datos de intervalor parto uno y dos con datos completos y parciales para este caracter.

IEP_3 |>
  filter(IEP_NA != 0) |>
  summarise(Mínimo = min(IEP_NA), Máximo = max(IEP_NA))

IEP_3 |>
  select(ID, IEP, ends_with(c('_IEP', 'P2')), Raza_toro) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/intervalo_P1_P2/Completo/IEP.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos completo.

IEP_3 |>
  select(ID, IEP_NA, ends_with(c('_IEP', 'P2')), Raza_toro) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/intervalo_P1_P2/Parcial/IEP.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos parcial, a los que se les enmascaro el fenotipo.

####################################################################
# Bi-carácter entre edad al primer parto e intervalo parto uno y dos
####################################################################

##########
# Completo
##########

EPP <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/Edad_Primer_Parto/Completo/EPP.txt', delim = ' ', col_names = FALSE) |> # Se importa el conjunto de datos completo para la edad al primer parto.
  rename(
    ID = X1,
    EPP = X2,
    GC_EPP = X3,
    ID_toro_EPP = X4,
    Sexo_P1 = X5,
    Edad_toro_P1 = X6    
    )

IEP <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/intervalo_P1_P2/Completo/IEP.txt', delim = ' ', col_names = FALSE) |> # Se importa el conjunto de datos completo para el intervalo entre el primer y segundo parto.
  rename(
    ID = X1,
    IEP = X2,
    EPP_IEP = X3,
    GC_IEP = X4,
    ID_toro_IEP = X5,
    Sexo_P2 = X6,
    Edad_toro_P2 = X7,
    Raza_toro = X8
    )

EPP_IEP <- full_join(x = EPP, y = IEP, by = 'ID') |>
  mutate_all(~replace(., is.na(.), 0)) |> # Con mutate_all() se aplica la función replace() a todas las columnas, de esta forma se reemplazan los valores NA en todas las columnas por 0.
  select(ID, EPP, ends_with(c('_EPP', 'P1')), -EPP_IEP, IEP, ends_with(c('_IEP', 'P2')), Raza_toro)

EPP_IEP |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/EPP_IEP/Completo/EPP_IEP.txt', col_names = FALSE)

#########
# Parcial
#########

EPP <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/Edad_Primer_Parto/Parcial/EPP.txt', delim = ' ', col_names = FALSE) |> # Se importa el conjunto de datos parcial para la edad al primer parto.
  rename(
    ID = X1,
    EPP_NA = X2,
    GC_EPP = X3,
    ID_toro_EPP = X4,
    Sexo_P1 = X5,
    Edad_toro_P1 = X6    
    )

IEP <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/intervalo_P1_P2/Parcial/IEP.txt', delim = ' ', col_names = FALSE) |> # Se importa el conjunto de datos parcial para el intervalo entre el primer y segundo parto.
  rename(
    ID = X1,
    IEP_NA = X2,
    EPP_IEP = X3,
    GC_IEP = X4,
    ID_toro_IEP = X5,
    Sexo_P2 = X6,
    Edad_toro_P2 = X7,
    Raza_toro = X8
    )

EPP_IEP <- full_join(x = EPP, y = IEP, by = 'ID') |>
  mutate_all(~replace(., is.na(.), 0)) |> # Con mutate_all() se aplica la función replace() a todas las columnas, de esta forma se reemplazan los valores NA en todas las columnas por 0.
  select(ID, EPP_NA, ends_with(c('_EPP', 'P1')), -EPP_IEP, IEP_NA, ends_with(c('_IEP', 'P2')), Raza_toro)
  
EPP_IEP |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/EPP_IEP/Parcial/EPP_IEP.txt', col_names = FALSE)

#############################
# Peso a los 365 días de edad
#############################

P365 <- datProd |>
  select(ID, id_renum, P365, Peso_ent, Dia_cebo, contains('pc365')) |>
  filter(P365 != 0) # Se quitan los intervalos parto uno y parto dos con valores de 0. En total hay 15335 individuos con registro de peso a los 365 días de edad.

P365_2 <- P365 |>
  mutate(
    P365_NA = case_when(
        ID %in% datGeno_4 ~ 0
        )
    ) |> # Se enmascara el peso a los 365 días de edad de los individuos en el objeto "datGeno_4".
  relocate(
    P365_NA,
    .after = P365
    )

P365_2 |> count(P365_NA) # Hay 7 individuos con valores de 0 para el peso a los 365 días de edad, que corresponde a los años de nacimiento 2016, 2017 y 2018.

P365_3 <- P365_2 |>
  mutate(
    P365_NA = case_when(
        is.na(P365_NA) ~ P365,
        TRUE ~ P365_NA
        )
    ) # Se obtiene el conjunto de peso a los 365 días de edad con datos completos y parciales para este caracter.

P365_3 |>
  filter(P365_NA != 0) |>
  summarise(Mínimo = min(P365_NA), Máximo = max(P365_NA))

P365_3 |>
  select(ID, P365, ends_with('_pc365'), Peso_ent, Dia_cebo) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_365/Completo/P365.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos completo.

P365_3 |>
  select(ID, P365_NA, ends_with('_pc365'), Peso_ent, Dia_cebo) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_365/Parcial/P365.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos parcial, a los que se les enmascaro el fenotipo.

####################################
# Crecimiento a los 365 días de edad
####################################

C365 <- datProd |>
  select(ID, id_renum, C365, Peso_ent, Dia_cebo, contains('pc365')) |>
  filter(C365 != 0) # Se quitan los intervalos parto uno y parto dos con valores de 0. En total hay 15335 individuos con registro de crecimiento a los 365 días de edad.

C365_2 <- C365 |>
  mutate(
    C365_NA = case_when(
        ID %in% datGeno_4 ~ 0
        )
    ) |> # Se enmascara el peso a los 365 días de edad de los individuos en el objeto "datGeno_4".
  relocate(
    C365_NA,
    .after = C365
    )

C365_2 |> count(C365_NA) # Hay 7 individuos con valores de 0 para el peso a los 365 días de edad, que corresponde a los años de nacimiento 2016, 2017 y 2018.

C365_3 <- C365_2 |>
  mutate(
    C365_NA = case_when(
        is.na(C365_NA) ~ C365,
        TRUE ~ C365_NA
        )
    ) # Se obtiene el conjunto de datos de crecimiento a los 365 días de edad con datos completos y parciales para este caracter.

C365_3 |>
  filter(C365_NA != 0) |>
  summarise(Mínimo = min(C365_NA), Máximo = max(C365_NA))

C365_3 |>
  select(ID, C365, ends_with('_pc365'), Peso_ent, Dia_cebo) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/crecimiento_365/Completo/C365.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos completo.

C365_3 |>
  select(ID, C365_NA, ends_with('_pc365'), Peso_ent, Dia_cebo) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/crecimiento_365/Parcial/C365.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos parcial, a los que se les enmascaro el fenotipo.

#############################################################
# Bi-carácter entre peso y crecimiento a los 365 días de edad
#############################################################

##########
# Completo
##########

P365 <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_365/Completo/P365.txt', delim = ' ', col_names = FALSE) |> # Se importa el conjunto de datos completo para el peso a los 365 días de edad.
  rename(
    ID = X1,
    P365 = X2,
    Edad_pc365 = X3,
    GC_pc365 = X4,
    Peso_ent = X5,
    Dia_cebo = X6    
    )

C365 <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/crecimiento_365/Completo/C365.txt', delim = ' ', col_names = FALSE) |> # Se importa el conjunto de datos completo para el crecimiento a los 365 días de edad.
  rename(
    ID = X1,
    C365 = X2,
    Edad_pc365 = X3,
    GC_pc365 = X4,
    Peso_ent = X5,
    Dia_cebo = X6
    ) |>
  select(ID, C365)

P365_C365 <- full_join(x = P365, y = C365, by = 'ID') |>
  mutate_all(~replace(., is.na(.), 0)) |> # Con mutate_all() se aplica la función replace() a todas las columnas, de esta forma se reemplazan los valores NA en todas las columnas por 0.
  relocate(
    C365,
    .after = P365
    )

P365_C365 |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/P365_C365/Completo/P365_C365.txt', col_names = FALSE)

#########
# Parcial
#########

P365 <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_365/Parcial/P365.txt', delim = ' ', col_names = FALSE) |> # Se importa el conjunto de datos completo para el peso a los 365 días de edad.
  rename(
    ID = X1,
    P365_NA = X2,
    Edad_pc365 = X3,
    GC_pc365 = X4,
    Peso_ent = X5,
    Dia_cebo = X6    
    )

C365 <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/crecimiento_365/Parcial/C365.txt', delim = ' ', col_names = FALSE) |> # Se importa el conjunto de datos completo para el crecimiento a los 365 días de edad.
  rename(
    ID = X1,
    C365_NA = X2,
    Edad_pc365 = X3,
    GC_pc365 = X4,
    Peso_ent = X5,
    Dia_cebo = X6
    ) |>
  select(ID, C365_NA)

P365_C365 <- full_join(x = P365, y = C365, by = 'ID') |>
  mutate_all(~replace(., is.na(.), 0)) |> # Con mutate_all() se aplica la función replace() a todas las columnas, de esta forma se reemplazan los valores NA en todas las columnas por 0.
  relocate(
    C365_NA,
    .after = P365_NA
    )

P365_C365 |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/P365_C365/Parcial/P365_C365.txt', col_names = FALSE)

#################
# Peso a la canal
#################

PC <- datProd |>
  select(ID, id_renum, PC, GC_PC, contains('prc')) |>
  filter(PC != 0) # Se quitan los intervalos parto uno y parto dos con valores de 0. En total hay 38975 individuos con registro de peso a la canal.

PC_2 <- PC |>
  mutate(
    PC_NA = case_when(
        ID %in% datGeno_4 ~ 0
        )
    ) |> # Se enmascara el peso a la canal de los individuos en el objeto "datGeno_4".
  relocate(
    PC_NA,
    .after = PC
    )

PC_2 |> count(PC_NA) # Hay 3 individuos con valores de 0 para el peso a la canal, que corresponde a los años de nacimiento 2010 y 2013.

PC_3 <- PC_2 |>
  mutate(
    PC_NA = case_when(
        is.na(PC_NA) ~ PC,
        TRUE ~ PC_NA
        )
    ) # Se obtiene el conjunto de datos peso a la canal con datos completos y parciales para este caracter.

PC_3 |>
  filter(PC_NA != 0) |>
  summarise(Mínimo = min(PC_NA), Máximo = max(PC_NA))

PC_3 |>
  select(ID, PC, ends_with('_prc'), GC_PC) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_canal/Completo/PC.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos completo.

PC_3 |>
  select(ID, PC_NA, ends_with('_prc'), GC_PC) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_canal/Parcial/PC.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos parcial, a los que se les enmascaro el fenotipo.

########################
# Rendimiento a la canal
########################

RC <- datProd |>
  select(ID, id_renum, RC, GC_RC, contains('prc')) |>
  filter(RC != 0) # Se quitan los intervalos parto uno y parto dos con valores de 0. En total hay 21314 individuos con registro de peso a la canal.

RC_2 <- RC |>
  mutate(
    RC_NA = case_when(
        ID %in% datGeno_4 ~ 0
        )
    ) |> # Se enmascara el rednimiento a la canal de los individuos en el objeto "datGeno_4".
  relocate(
    RC_NA,
    .after = RC
    )

RC_2 |> count(RC_NA) # Hay 2 individuos con valores de 0 para el peso a la canal, que corresponde a los años de nacimiento 2010 y 2013.

RC_3 <- RC_2 |>
  mutate(
    RC_NA = case_when(
        is.na(RC_NA) ~ RC,
        TRUE ~ RC_NA
        )
    ) # Se obtiene el conjunto de rendimiento a la canal con datos completos y parciales para este caracter.

RC_3 |>
  filter(RC_NA != 0) |>
  summarise(Mínimo = min(RC_NA), Máximo = max(RC_NA))

RC_3 |>
  select(ID, RC, ends_with('_prc'), GC_RC) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/rendimiento_canal/Completo/RC.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos completo.

RC_3 |>
  select(ID, RC_NA, ends_with('_prc'), GC_RC) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/rendimiento_canal/Parcial/RC.txt', delim = ' ', col_names = FALSE) # Se importa el conjunto de datos parcial, a los que se les enmascaro el fenotipo.

##################################################
# Bi-carácter entre peso y rendimiento en la canal
##################################################

##########
# Completo
##########

PC <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_canal/Completo/PC.txt', delim = ' ', col_names = FALSE) |> # Se importa el conjunto de datos completo para el peso en la canal.
  rename(
    ID = X1,
    PC = X2,
    Sexo_prc = X3,
    Edad_prc = X4,
    GC_PC = X5    
    )

RC <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/rendimiento_canal/Completo/RC.txt', delim = ' ', col_names = FALSE) |> # Se importa el conjunto de datos completo para el rendimiento en la canal.
  rename(
    ID = X1,
    RC = X2,
    Sexo_prc = X3,
    Edad_prc = X4,
    GC_PC = X5   
    ) |>
  select(ID, RC)

PC_RC <- full_join(x = PC, y = RC, by = 'ID') |>
  mutate_all(~replace(., is.na(.), 0)) |> # Con mutate_all() se aplica la función replace() a todas las columnas, de esta forma se reemplazan los valores NA en todas las columnas por 0.
  relocate(
    RC,
    .after = PC
    )

PC_RC |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/PC_RC/Completo/PC_RC.txt', col_names = FALSE)

#########
# Parcial
#########

PC <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/peso_canal/Parcial/PC.txt', delim = ' ', col_names = FALSE) |> # Se importa el conjunto de datos parcial para el peso en la canal.
  rename(
    ID = X1,
    PC = X2,
    Sexo_prc = X3,
    Edad_prc = X4,
    GC_PC = X5    
    )

RC <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/rendimiento_canal/Parcial/RC.txt', delim = ' ', col_names = FALSE) |> # Se importa el conjunto de datos parcial para el rendimiento en la canal.
  rename(
    ID = X1,
    RC = X2,
    Sexo_prc = X3,
    Edad_prc = X4,
    GC_PC = X5   
    ) |>
  select(ID, RC)

PC_RC <- full_join(x = PC, y = RC, by = 'ID') |>
  mutate_all(~replace(., is.na(.), 0)) |> # Con mutate_all() se aplica la función replace() a todas las columnas, de esta forma se reemplazan los valores NA en todas las columnas por 0.
  relocate(
    RC,
    .after = PC
    )

PC_RC |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags/PC_RC/Parcial/PC_RC.txt', col_names = FALSE)
```
