---
title: "Parte 8: Edición en los datos de genotipos imputados a HD con Beagle v. 5.4 y que corresponden a SNP-tags y singletones"
format: html
---

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(tidyverse, conflicted)
conflicts_prefer(dplyr::filter) # Aquí se le da prioridad a la función filter() del paquete dplyr. Esto debido al conflicto generado con el paquete stats:
# Error:
# ! [conflicted] filter found in 2 packages.
# Either pick the one you want with `::`:
# dplyr::filter
# stats::filter
conflicts_prefer(dplyr::select)
```

<!--
NOTA: A continuación se seleccionan de los genotipos en HD imputados, los marcadores que corresponden a SNP-tags.
-->

```{r}
#| label: Selección de tags en los datos de genotipos en HD

# Se importa los datos de genotipos imputados en HD ----

resHD <- data.table::fread(file = 'Imp_HD/Datos/Beagle/Precision_origen/Res_imputacion_2.vcf', sep = '\t', skip = '#CHROM', header = TRUE) |> # Con skip = "#CHROM" se indica iniciar en la fila donde estan los nombres de las columnas.
  select(-c(2, 4:9))

# Se importa los datos con los nombres de los SNP-tags ----

dat_tags <- read_delim(file = 'single_tags/Datos/datPuros/SNP_only_tags_ANI.txt', col_names = FALSE, delim = ' ')

# Se observa cuales SNP-tags aparecen adentro del conjunto de datos "nomb_marc_comun.txt" ----

marc_comun <- read_delim(file = 'Imp_HD/Datos/datQC_2/nomb_marc_comun.txt', col_names = FALSE, delim = ' ') |>
  inner_join(y = dat_tags, by = 'X1')

# Se genera la columna X3 con el nombre de los SNP-tags de acuerdo al genotipado en 50k y HD ----

dat_tags <- marc_comun |>
  full_join(x = dat_tags, by = 'X1') |>
  mutate(
    X3 = case_when(
      is.na(X2) ~ X1,
      TRUE ~ X2
      )
    )

dat_tags |> slice(1021:1024) # Se observa para ver si la columna X3 generó el nombre de los SNP-tags como se quería.

dim_desc(dat_tags) # Hay en total 103080 SNP-tags.

# Se dejan los marcadores considerados tags ----

SNP_tag <- resHD |>
  filter(ID %in% dat_tags$X3)

dim_desc(SNP_tag) # 103080-102554 = 526 SNP-tags se eliminaron, pueden que al hacer el control de calidad.

# Se importa los datos con los nombres de los singletones  ----

dat_sing <- read_delim(file = 'single_tags/Datos/datPuros/SNP_single_ANI.txt', col_names = FALSE, delim = ' ')

# Se observa cuales singletones aparecen adentro del conjunto de datos "nomb_marc_comun.txt" ----

marc_comun_2 <- read_delim(file = 'Imp_HD/Datos/datQC_2/nomb_marc_comun.txt', col_names = FALSE, delim = ' ') |>
  inner_join(y = dat_sing, by = 'X1')

# Se genera la columna X3 con el nombre de los SNP-tags de acuerdo al genotipado en 50k y HD ----

dat_sing <- marc_comun_2 |>
  full_join(x = dat_sing, by = 'X1') |>
  mutate(
    X3 = case_when(
      is.na(X2) ~ X1,
      TRUE ~ X2
      )
    )

dat_sing |>
  filter(grepl("Affx-", X2)) |> # Con la función  grepl() se filtra las filas de dat_sing donde la columna X2 contiene la cadena "Affx-".
  slice_tail(n = 4) # Se observa para ver si la columna X3 generó el nombre de los singletones como se quería.

dim_desc(dat_sing) # Hay en total 128660 singletones.

# Se dejan los marcadores considerados singletones ----

SNP_sing <- resHD |>
  filter(ID %in% dat_sing$X3)

dim_desc(SNP_sing) # 128660-128003 = 657 singletones se eliminaron, pueden que al hacer el control de calidad.

# Se unen los marcadores considerados SNP-tags y singletones ----

SNP_tag_sing <- bind_rows(SNP_tag, SNP_sing)

dim_desc(SNP_tag_sing) # Hay en total 128003 + 102554 = 230557 SNP-tags y singletones.
```

<!--
NOTA: A continuación se transponen los conjuntos de datos de SNP-tags y singletones, un cromosoma a la vez.
-->

```{r}
#| label: Edición de datos de SNP-tags y singletones

#############
# Cromosoma 1
#############

# Se obtienen solo los marcadores del cromosoma 1 ----

Cromo_1 <- SNP_tag_sing |>
  filter(`#CHROM` == 1)

Cromo_1 |> count(`#CHROM`) # Se comprueba y si hay 13139 marcadores en el cromosoma 1.

Cromo_1 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_1_t <- Cromo_1 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_1_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_1_t) # Se comprueba y hay 2970 individuos y 13139 marcadores.

Cromo_1_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_1/Cromo_1.txt', delim = ' ', col_names = TRUE)

#############
# Cromosoma 2
#############

# Se obtienen solo los marcadores del cromosoma 2 ----

Cromo_2 <- SNP_tag_sing |>
  filter(`#CHROM` == 2)

Cromo_2 |> count(`#CHROM`) # Se comprueba y si hay 11631 marcadores en el cromosoma 2.

Cromo_2 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_2_t <- Cromo_2 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_2_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_2_t) # Se comprueba y hay 2970 individuos y 11631 marcadores.

Cromo_2_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_2/Cromo_2.txt', delim = ' ', col_names = TRUE)

#############
# Cromosoma 3
#############

# Se obtienen solo los marcadores del cromosoma 3 ----

Cromo_3 <- SNP_tag_sing |>
  filter(`#CHROM` == 3)

Cromo_3 |> count(`#CHROM`) # Se comprueba y si hay 10749 marcadores en el cromosoma 3.

Cromo_3 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_3_t <- Cromo_3 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_3_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_3_t) # Se comprueba y hay 2970 individuos y 10749 marcadores.

Cromo_3_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_3/Cromo_3.txt', delim = ' ', col_names = TRUE)

#############
# Cromosoma 4
#############

# Se obtienen solo los marcadores del cromosoma 4 ----

Cromo_4 <- SNP_tag_sing |>
  filter(`#CHROM` == 4)

Cromo_4 |> count(`#CHROM`) # Se comprueba y si hay 11005 marcadores en el cromosoma 4.

Cromo_4 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_4_t <- Cromo_4 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_4_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_4_t) # Se comprueba y hay 2970 individuos y 11005 marcadores.

Cromo_4_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_4/Cromo_4.txt', delim = ' ', col_names = TRUE)

#############
# Cromosoma 5
#############

# Se obtienen solo los marcadores del cromosoma 5 ----

Cromo_5 <- SNP_tag_sing |>
  filter(`#CHROM` == 5)

Cromo_5 |> count(`#CHROM`) # Se comprueba y si hay 10183 marcadores en el cromosoma 5.

Cromo_5 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_5_t <- Cromo_5 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_5_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_5_t) # Se comprueba y hay 2970 individuos y 10183 marcadores.

Cromo_5_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_5/Cromo_5.txt', delim = ' ', col_names = TRUE)

#############
# Cromosoma 6
#############

# Se obtienen solo los marcadores del cromosoma 6 ----

Cromo_6 <- SNP_tag_sing |>
  filter(`#CHROM` == 6)

Cromo_6 |> count(`#CHROM`) # Se comprueba y si hay 10140 marcadores en el cromosoma 6.

Cromo_6 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_6_t <- Cromo_6 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_6_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_6_t) # Se comprueba y hay 2970 individuos y 10140 marcadores.

Cromo_6_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_6/Cromo_6.txt', delim = ' ', col_names = TRUE)

#############
# Cromosoma 7
#############

# Se obtienen solo los marcadores del cromosoma 7 ----

Cromo_7 <- SNP_tag_sing |>
  filter(`#CHROM` == 7)

Cromo_7 |> count(`#CHROM`) # Se comprueba y si hay 9845 marcadores en el cromosoma 7.

Cromo_7 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_7_t <- Cromo_7 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_7_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_7_t) # Se comprueba y hay 2970 individuos y 9845 marcadores.

Cromo_7_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_7/Cromo_7.txt', delim = ' ', col_names = TRUE)

#############
# Cromosoma 8
#############

# Se obtienen solo los marcadores del cromosoma 8 ----

Cromo_8 <- SNP_tag_sing |>
  filter(`#CHROM` == 8)

Cromo_8 |> count(`#CHROM`) # Se comprueba y si hay 9005 marcadores en el cromosoma 7.

Cromo_8 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_8_t <- Cromo_8 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_8_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_8_t) # Se comprueba y hay 2970 individuos y 9005 marcadores.

Cromo_8_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_8/Cromo_8.txt', delim = ' ', col_names = TRUE)

#############
# Cromosoma 9
#############

# Se obtienen solo los marcadores del cromosoma 9 ----

Cromo_9 <- SNP_tag_sing |>
  filter(`#CHROM` == 9)

Cromo_9 |> count(`#CHROM`) # Se comprueba y si hay 9149 marcadores en el cromosoma 9.

Cromo_9 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_9_t <- Cromo_9 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_9_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_9_t) # Se comprueba y hay 2970 individuos y 9149 marcadores.

Cromo_9_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_9/Cromo_9.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 10
##############

# Se obtienen solo los marcadores del cromosoma 10 ----

Cromo_10 <- SNP_tag_sing |>
  filter(`#CHROM` == 10)

Cromo_10 |> count(`#CHROM`) # Se comprueba y si hay 9854 marcadores en el cromosoma 10.

Cromo_10 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_10_t <- Cromo_10 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_10_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_10_t) # Se comprueba y hay 2970 individuos y 9854 marcadores.

Cromo_10_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_10/Cromo_10.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 11
##############

# Se obtienen solo los marcadores del cromosoma 11 ----

Cromo_11 <- SNP_tag_sing |>
  filter(`#CHROM` == 11)

Cromo_11 |> count(`#CHROM`) # Se comprueba y si hay 9873 marcadores en el cromosoma 11.

Cromo_11 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_11_t <- Cromo_11 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_11_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_11_t) # Se comprueba y hay 2970 individuos y 9873 marcadores.

Cromo_11_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_11/Cromo_11.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 12
##############

# Se obtienen solo los marcadores del cromosoma 12 ----

Cromo_12 <- SNP_tag_sing |>
  filter(`#CHROM` == 12)

Cromo_12 |> count(`#CHROM`) # Se comprueba y si hay 8290 marcadores en el cromosoma 12.

Cromo_12 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_12_t <- Cromo_12 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_12_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_12_t) # Se comprueba y hay 2970 individuos y 8290 marcadores.

Cromo_12_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_12/Cromo_12.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 13
##############

# Se obtienen solo los marcadores del cromosoma 13 ----

Cromo_13 <- SNP_tag_sing |>
  filter(`#CHROM` == 13)

Cromo_13 |> count(`#CHROM`) # Se comprueba y si hay 7166 marcadores en el cromosoma 13.

Cromo_13 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_13_t <- Cromo_13 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_13_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_13_t) # Se comprueba y hay 2970 individuos y 7166 marcadores.

Cromo_13_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_13/Cromo_13.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 14
##############

# Se obtienen solo los marcadores del cromosoma 14 ----

Cromo_14 <- SNP_tag_sing |>
  filter(`#CHROM` == 14)

Cromo_14 |> count(`#CHROM`) # Se comprueba y si hay 7557 marcadores en el cromosoma 14.

Cromo_14 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_14_t <- Cromo_14 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_14_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_14_t) # Se comprueba y hay 2970 individuos y 7557 marcadores.

Cromo_14_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_14/Cromo_14.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 15
##############

# Se obtienen solo los marcadores del cromosoma 15 ----

Cromo_15 <- SNP_tag_sing |>
  filter(`#CHROM` == 15)

Cromo_15 |> count(`#CHROM`) # Se comprueba y si hay 7878 marcadores en el cromosoma 15.

Cromo_15 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_15_t <- Cromo_15 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_15_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_15_t) # Se comprueba y hay 2970 individuos y 13139 marcadores.

Cromo_15_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_15/Cromo_15.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 16
##############

# Se obtienen solo los marcadores del cromosoma 16 ----

Cromo_16 <- SNP_tag_sing |>
  filter(`#CHROM` == 16)

Cromo_16 |> count(`#CHROM`) # Se comprueba y si hay 7228 marcadores en el cromosoma 16.

Cromo_16 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_16_t <- Cromo_16 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_16_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_16_t) # Se comprueba y hay 2970 individuos y 7228 marcadores.

Cromo_16_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_16/Cromo_16.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 17
##############

# Se obtienen solo los marcadores del cromosoma 17 ----

Cromo_17 <- SNP_tag_sing |>
  filter(`#CHROM` == 17)

Cromo_17 |> count(`#CHROM`) # Se comprueba y si hay 7292 marcadores en el cromosoma 17.

Cromo_17 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_17_t <- Cromo_17 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_17_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_17_t) # Se comprueba y hay 2970 individuos y 7292 marcadores.

Cromo_17_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_17/Cromo_17.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 18
##############

# Se obtienen solo los marcadores del cromosoma 18 ----

Cromo_18 <- SNP_tag_sing |>
  filter(`#CHROM` == 18)

Cromo_18 |> count(`#CHROM`) # Se comprueba y si hay 6358 marcadores en el cromosoma 18.

Cromo_18 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_18_t <- Cromo_18 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_18_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_18_t) # Se comprueba y hay 2970 individuos y 6358 marcadores.

Cromo_18_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_18/Cromo_18.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 19
##############

# Se obtienen solo los marcadores del cromosoma 19 ----

Cromo_19 <- SNP_tag_sing |>
  filter(`#CHROM` == 19)

Cromo_19 |> count(`#CHROM`) # Se comprueba y si hay 7208 marcadores en el cromosoma 19.

Cromo_19 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_19_t <- Cromo_19 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_19_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_19_t) # Se comprueba y hay 2970 individuos y 7208 marcadores.

Cromo_19_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_19/Cromo_19.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 20
##############

# Se obtienen solo los marcadores del cromosoma 20 ----

Cromo_20 <- SNP_tag_sing |>
  filter(`#CHROM` == 20)

Cromo_20 |> count(`#CHROM`) # Se comprueba y si hay 6883 marcadores en el cromosoma 20.

Cromo_20 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_20_t <- Cromo_20 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_20_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_20_t) # Se comprueba y hay 2970 individuos y 6883 marcadores.

Cromo_20_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_20/Cromo_20.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 21
##############

# Se obtienen solo los marcadores del cromosoma 21 ----

Cromo_21 <- SNP_tag_sing |>
  filter(`#CHROM` == 21)

Cromo_21 |> count(`#CHROM`) # Se comprueba y si hay 6596 marcadores en el cromosoma 21.

Cromo_21 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_21_t <- Cromo_21 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_21_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_21_t) # Se comprueba y hay 2970 individuos y 6596 marcadores.

Cromo_21_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_21/Cromo_21.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 22
##############

# Se obtienen solo los marcadores del cromosoma 22 ----

Cromo_22 <- SNP_tag_sing |>
  filter(`#CHROM` == 22)

Cromo_22 |> count(`#CHROM`) # Se comprueba y si hay 6382 marcadores en el cromosoma 22.

Cromo_22 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_22_t <- Cromo_22 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_22_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_22_t) # Se comprueba y hay 2970 individuos y 13139 marcadores.

Cromo_22_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_22/Cromo_22.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 23
##############

# Se obtienen solo los marcadores del cromosoma 23 ----

Cromo_23 <- SNP_tag_sing |>
  filter(`#CHROM` == 23)

Cromo_23 |> count(`#CHROM`) # Se comprueba y si hay 5994 marcadores en el cromosoma 23.

Cromo_23 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_23_t <- Cromo_23 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_23_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_23_t) # Se comprueba y hay 2970 individuos y 5994 marcadores.

Cromo_23_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_23/Cromo_23.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 24
##############

# Se obtienen solo los marcadores del cromosoma 24 ----

Cromo_24 <- SNP_tag_sing |>
  filter(`#CHROM` == 24)

Cromo_24 |> count(`#CHROM`) # Se comprueba y si hay 6194 marcadores en el cromosoma 24.

Cromo_24 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_24_t <- Cromo_24 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_24_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_24_t) # Se comprueba y hay 2970 individuos y 6194 marcadores.

Cromo_24_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_24/Cromo_24.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 25
##############

# Se obtienen solo los marcadores del cromosoma 25 ----

Cromo_25 <- SNP_tag_sing |>
  filter(`#CHROM` == 25)

Cromo_25 |> count(`#CHROM`) # Se comprueba y si hay 4731 marcadores en el cromosoma 25.

Cromo_25 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_25_t <- Cromo_25 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_25_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_25_t) # Se comprueba y hay 2970 individuos y 4731 marcadores.

Cromo_25_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_25/Cromo_25.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 26
##############

# Se obtienen solo los marcadores del cromosoma 26 ----

Cromo_26 <- SNP_tag_sing |>
  filter(`#CHROM` == 26)

Cromo_26 |> count(`#CHROM`) # Se comprueba y si hay 5229 marcadores en el cromosoma 26.

Cromo_26 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_26_t <- Cromo_26 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_26_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_26_t) # Se comprueba y hay 2970 individuos y 5229 marcadores.

Cromo_26_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_26/Cromo_26.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 27
##############

# Se obtienen solo los marcadores del cromosoma 27 ----

Cromo_27 <- SNP_tag_sing |>
  filter(`#CHROM` == 27)

Cromo_27 |> count(`#CHROM`) # Se comprueba y si hay 4817 marcadores en el cromosoma 27.

Cromo_27 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_27_t <- Cromo_27 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_27_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_27_t) # Se comprueba y hay 2970 individuos y 4817 marcadores.

Cromo_27_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_27/Cromo_27.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 28
##############

# Se obtienen solo los marcadores del cromosoma 28 ----

Cromo_28 <- SNP_tag_sing |>
  filter(`#CHROM` == 28)

Cromo_28 |> count(`#CHROM`) # Se comprueba y si hay 4806 marcadores en el cromosoma 28.

Cromo_28 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_28_t <- Cromo_28 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_28_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_28_t) # Se comprueba y hay 2970 individuos y 4806 marcadores.

Cromo_28_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_28/Cromo_28.txt', delim = ' ', col_names = TRUE)

##############
# Cromosoma 29
##############

# Se obtienen solo los marcadores del cromosoma 29 ----

Cromo_29 <- SNP_tag_sing |>
  filter(`#CHROM` == 29)

Cromo_29 |> count(`#CHROM`) # Se comprueba y si hay 5375 marcadores en el cromosoma 29.

Cromo_29 |> select(1:4) |> slice_head(n = 4)

# Se transpone el objeto anterior para que los maradores queden en columnas y los individuos en filas ----

Cromo_29_t <- Cromo_29 |>
  select(-1) |>
  pivot_longer(
    cols = c(2:2971),
    names_to = 'IID',
    values_to = 'Gen_fase'
    ) |>
  pivot_wider(
    names_from = ID,
    values_from = Gen_fase
    ) |>
  separate(
    col = IID,
    into = c('ID', 'ID_2'),
    sep = '_'
    ) |>
  select(-ID_2) |>
  as_tibble()

Cromo_29_t |> select(1:4) |> slice_head(n = 4)

dim_desc(Cromo_29_t) # Se comprueba y hay 2970 individuos y 5375 marcadores.

Cromo_29_t |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_29/Cromo_29.txt', delim = ' ', col_names = TRUE)
```

<!--
NOTA: Se cambia los genotipos en fase del Beagle al código de genotipos como lo requiere el blupf90.
-->

```{r}
#| label: Recodificación de genotipos

# La función a continuación permite cambiar los genotipos a como lo requiere el conjunto de programas del blupf90 ----

cod_geno <- function(columna) { # Esta función permite cambiar los genotipos en fase del Beagle al código de genotipos como lo requiere el blupf90 (0: A1A1 | 5: fase desconocida | 2: A2A2 | 1: A1A2 | 1:A2A1... el primer alelo es el paterno y el segundo es el materno).
  for (i in 2:ncol(columna)) { # Se indica aquí iniciar los cambios a partir de la segunda columna, ya que la primera corresponde a la ID de los individuos.
    columna[[i]] <- case_when(
      columna[[i]] == '0|0' ~ '0',
      columna[[i]] == '0|1' ~ '1',
      columna[[i]] == '1|0' ~ '1',
      columna[[i]] == '1|1' ~ '2',
      columna[[i]] == '.|.' ~ '5'
      )
    }
  return(columna)
  }

#############
# Cromosoma 1
#############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_1_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_1/Cromo_1.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_1_e <- cod_geno(Cromo_1_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_1', 
    2:ncol(Cromo_1_t),
    sep = '',
    remove = TRUE
    )

#############
# Cromosoma 2
#############

Cromo_2_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_2/Cromo_2.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_2_e <- cod_geno(Cromo_2_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_2', 
    2:ncol(Cromo_2_t),
    sep = '',
    remove = TRUE
    )

#############
# Cromosoma 3
#############

Cromo_3_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_3/Cromo_3.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_3_e <- cod_geno(Cromo_3_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_3', 
    2:ncol(Cromo_3_t),
    sep = '',
    remove = TRUE
    )

#############
# Cromosoma 4
#############

Cromo_4_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_4/Cromo_4.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_4_e <- cod_geno(Cromo_4_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_4', 
    2:ncol(Cromo_4_t),
    sep = '',
    remove = TRUE
    )

#############
# Cromosoma 5
#############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_5_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_5/Cromo_5.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_5_e <- cod_geno(Cromo_5_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_5', 
    2:ncol(Cromo_5_t),
    sep = '',
    remove = TRUE
    )

#############
# Cromosoma 6
#############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_6_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_6/Cromo_6.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_6_e <- cod_geno(Cromo_6_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_6', 
    2:ncol(Cromo_6_t),
    sep = '',
    remove = TRUE
    )

#############
# Cromosoma 7
#############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_7_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_7/Cromo_7.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_7_e <- cod_geno(Cromo_7_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_7', 
    2:ncol(Cromo_7_t),
    sep = '',
    remove = TRUE
    )

#############
# Cromosoma 8
#############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_8_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_8/Cromo_8.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_8_e <- cod_geno(Cromo_8_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_8', 
    2:ncol(Cromo_8_t),
    sep = '',
    remove = TRUE
    )

#############
# Cromosoma 9
#############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_9_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_9/Cromo_9.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_9_e <- cod_geno(Cromo_9_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_9', 
    2:ncol(Cromo_9_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 10
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_10_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_10/Cromo_10.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_10_e <- cod_geno(Cromo_10_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_10', 
    2:ncol(Cromo_10_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 11
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_11_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_11/Cromo_11.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_11_e <- cod_geno(Cromo_11_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_11', 
    2:ncol(Cromo_11_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 12
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_12_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_12/Cromo_12.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_12_e <- cod_geno(Cromo_12_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_12', 
    2:ncol(Cromo_12_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 13
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_13_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_13/Cromo_13.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_13_e <- cod_geno(Cromo_13_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_13', 
    2:ncol(Cromo_13_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 14
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_14_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_14/Cromo_14.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_14_e <- cod_geno(Cromo_14_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_14', 
    2:ncol(Cromo_14_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 15
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_15_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_15/Cromo_15.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_15_e <- cod_geno(Cromo_15_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_15', 
    2:ncol(Cromo_15_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 16
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_16_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_16/Cromo_16.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_16_e <- cod_geno(Cromo_16_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_16', 
    2:ncol(Cromo_16_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 17
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_17_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_17/Cromo_17.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_17_e <- cod_geno(Cromo_17_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_17', 
    2:ncol(Cromo_17_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 18
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_18_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_18/Cromo_18.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_18_e <- cod_geno(Cromo_18_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_18', 
    2:ncol(Cromo_18_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 19
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_19_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_19/Cromo_19.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_19_e <- cod_geno(Cromo_19_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_19', 
    2:ncol(Cromo_19_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 20
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_20_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_20/Cromo_20.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_20_e <- cod_geno(Cromo_20_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_20', 
    2:ncol(Cromo_20_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 21
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_21_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_21/Cromo_21.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_21_e <- cod_geno(Cromo_21_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_21', 
    2:ncol(Cromo_21_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 22
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_22_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_22/Cromo_22.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_22_e <- cod_geno(Cromo_22_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_22', 
    2:ncol(Cromo_22_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 23
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_23_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_23/Cromo_23.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_23_e <- cod_geno(Cromo_23_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_23', 
    2:ncol(Cromo_23_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 24
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_24_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_24/Cromo_24.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_24_e <- cod_geno(Cromo_24_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_24', 
    2:ncol(Cromo_24_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 25
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_25_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_25/Cromo_25.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_25_e <- cod_geno(Cromo_25_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_25', 
    2:ncol(Cromo_25_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 26
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_26_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_26/Cromo_26.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_26_e <- cod_geno(Cromo_26_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_26', 
    2:ncol(Cromo_26_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 27
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_27_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_27/Cromo_27.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_27_e <- cod_geno(Cromo_27_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_27', 
    2:ncol(Cromo_27_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 28
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_28_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_28/Cromo_28.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_28_e <- cod_geno(Cromo_28_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_28', 
    2:ncol(Cromo_28_t),
    sep = '',
    remove = TRUE
    )

##############
# Cromosoma 29
##############

# Se importa el conjunto de datos con marcadoes en columnas e individuos en filas ----

Cromo_29_t <- read_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/Cromo_29/Cromo_29.txt', delim = ' ', col_names = TRUE)

# Se cambian los valores de los genotipos ----

Cromo_29_e <- cod_geno(Cromo_29_t) |> # Se usa la función al inicio de este fragmento de código para cambiar los valores de los genotipos (en fase) del Beagle v. 5.4 a como lo requiere el programa blupf90.
  unite(
    col = 'Geno_29', 
    2:ncol(Cromo_29_t),
    sep = '',
    remove = TRUE
    )

# Se unen los objetos anteriores ----

Cromo_e <- inner_join(Cromo_1_e, Cromo_2_e, by = 'ID') |>
  inner_join(Cromo_3_e, by = 'ID') |>
  inner_join(Cromo_4_e, by = 'ID') |>
  inner_join(Cromo_5_e, by = 'ID') |>
  inner_join(Cromo_6_e, by = 'ID') |>
  inner_join(Cromo_7_e, by = 'ID') |>
  inner_join(Cromo_8_e, by = 'ID') |>
  inner_join(Cromo_9_e, by = 'ID') |>
  inner_join(Cromo_10_e, by = 'ID') |>
  inner_join(Cromo_11_e, by = 'ID') |>
  inner_join(Cromo_12_e, by = 'ID') |>
  inner_join(Cromo_13_e, by = 'ID') |>
  inner_join(Cromo_14_e, by = 'ID') |>
  inner_join(Cromo_15_e, by = 'ID') |>
  inner_join(Cromo_16_e, by = 'ID') |>
  inner_join(Cromo_17_e, by = 'ID') |>
  inner_join(Cromo_18_e, by = 'ID') |>
  inner_join(Cromo_19_e, by = 'ID') |>
  inner_join(Cromo_20_e, by = 'ID') |>
  inner_join(Cromo_21_e, by = 'ID') |>
  inner_join(Cromo_22_e, by = 'ID') |>
  inner_join(Cromo_23_e, by = 'ID') |>
  inner_join(Cromo_24_e, by = 'ID') |>
  inner_join(Cromo_25_e, by = 'ID') |>
  inner_join(Cromo_26_e, by = 'ID') |>
  inner_join(Cromo_27_e, by = 'ID') |>
  inner_join(Cromo_28_e, by = 'ID') |>
  inner_join(Cromo_29_e, by = 'ID')

Cromo_e |>
  unite(
    col = 'Geno', 
    2:ncol(Cromo_e),
    sep = '',
    remove = TRUE
    ) |>
  write_delim(file = 'eva_genetica/Datos/eva_genomica/SNP_tags_sing/resSNP_tags_sing.txt', delim = ' ', col_names = FALSE)
```
