---
title: "Parte 23: Edición en los datos de genotipos imputados a 50k con Beagle v. 5.4 y que corresponden a SNP-tags"
format: html
---

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(tidyverse, conflicted)
conflicts_prefer(dplyr::filter) # Aquí se le da prioridad a la función filter() del paquete dplyr. Esto debido al conflicto generado con el paquete stats:
# Error:
# ! [conflicted] filter found in 2 packages.
# Either pick the one you want with `::`:
# dplyr::filter
# stats::filter
conflicts_prefer(dplyr::select)
```

<!--
NOTA: A continuación se seleccionan de los genotipos en 50K imputados, los marcadores que corresponden a SNP-tags.
-->

```{r}
#| label: Selección de tags en los datos de genotipos en 50K

# Se importa los datos de genotipos imputados en HD ----

res50K <- data.table::fread(file = 'Imputacion/Imp_HD/Datos/Beagle/Precision_origen/Res_imputacion_3.vcf', sep = '\t', skip = '#CHROM', header = TRUE) |> # Con skip = "#CHROM" se indica iniciar en la fila donde estan los nombres de las columnas.
  select(-c(1:2, 4:9))

# Se importa los datos con los nombres de los SNP-tags y se extrae este nombre como un vector ----

dat_tags <- read_delim(file = 'single_tags/Datos/datPuros/SNP_only_tags_ANI.txt', col_names = FALSE, delim = ' ')

# Se observa cuales SNP-tags aparecen adentro del conjunto de datos "nomb_marc_comun.txt" ----

marc_comun <- read_delim(file = 'Imputacion/Imp_HD/Datos/datQC_2/nomb_marc_comun.txt', col_names = FALSE, delim = ' ') |>
  inner_join(y = dat_tags, by = 'X1')

# Se genera la columna X3 con el nombre de los SNP-tags de acuerdo al genotipado en 50k y HD ----

dat_tags <- marc_comun |>
  full_join(x = dat_tags, by = 'X1') |>
  mutate(
    X3 = case_when(
      is.na(X2) ~ X1,
      TRUE ~ X2
      )
    )

dat_tags |> slice(1021:1024) # Se observa para ver si la columna X3 generó el nombre de los SNP-tags como se quería.

dim_desc(dat_tags) # Hay en total 103080 SNP-tags.

# Se dejan los marcadores considerados tags ----

SNP_tag <- res50K |>
  filter(ID %in% dat_tags$X3)

dim_desc(SNP_tag) # En total, 55534 tag-SNPs en el genotipado de 50K. VOY AQUI
```
