---
title: "Parte 1: Visualizaciones para la presentación"
format: html
---

<!--
NOTA: Se cargan los paquetes de R.
-->

```{r}
#| label: Carga de paquetes R

pacman::p_load(tidyverse, patchwork)
```

<!--
NOTA: Se realiza una visualización que ayudará a explicar que son los tag SNPs.
-->

```{r}
#| label: Gráfica de tag SNP

data.frame(x = 1.0, y = 1.0) |>
  ggplot(aes(x = x, y = y)) +
  
  # Se dibujan dos cromosomas:
  annotate(geom = 'segment', x = 1.01, xend = 1.01, y = 3.0, yend = 4.0, colour = 'black', alpha = 0.1, linewidth = 4.8, linetype = 'solid', lineend = 'round') +
  annotate(geom = 'segment', x = 1.02, xend = 1.02, y = 3.0, yend = 4.0, colour = 'black', alpha = 0.1, linewidth = 4.8, linetype = 'solid', lineend = 'round') +
  annotate(geom = 'text', x = 1.015, y = 2.9, label = 'Cromosomas', size = 7.2, colour = 'black') +

  # Se dibuja el locus donde estará el SNP:
  annotate(geom = 'rect', xmin = 1.009, xmax = 1.011, ymin = 3.88, ymax = 3.9, colour = 'red', fill = 'red', alpha = 0.4, linewidth = 0.4, linetype = 'longdash') +
  annotate(geom = 'rect', xmin = 1.019, xmax = 1.021, ymin = 3.88, ymax = 3.9, colour = 'red', fill = 'red', alpha = 0.4, linewidth = 0.4, linetype = 'longdash') +
  annotate(geom = 'text', x = 1.003, y = 3.89, label = 'Locus', size = 4.2, colour = 'black') +
  
  # Se dibuja uno de los cromosomas más grande:
  annotate(geom = 'segment', x = 1.05, xend = 1.10, y = 2.5, yend = 2.5, colour = 'black', alpha = 0.1, linewidth = 28.8, linetype = 'solid', lineend = 'round') +
  annotate(geom = 'rect', xmin = 1.105, xmax = 1.107, ymin = 2.5, ymax = 2.5, colour = 'black', fill = 'black', alpha = 0.1, linewidth = 8.4) +
  annotate(geom = 'segment', x = 1.112, xend = 1.162, y = 2.5, yend = 2.5, colour = 'black', alpha = 0.1, linewidth = 28.8, linetype = 'solid', lineend = 'round') +

  # Se dibujan los maracdores (SNPs):
  annotate(geom = 'rect', xmin = 1.05, xmax = 1.053, ymin = 2.40, ymax = 2.60, colour = 'red', fill = 'red', alpha = 0.4) +
  annotate(geom = 'rect', xmin = 1.055, xmax = 1.058, ymin = 2.40, ymax = 2.60, colour = 'black', fill = 'black', alpha = 0.01) +
  annotate(geom = 'rect', xmin = 1.060, xmax = 1.063, ymin = 2.40, ymax = 2.60, colour = 'black', fill = 'black', alpha = 0.01) +
  annotate(geom = 'rect', xmin = 1.065, xmax = 1.068, ymin = 2.40, ymax = 2.60, colour = 'black', fill = 'black', alpha = 0.01) +
  annotate(geom = 'rect', xmin = 1.070, xmax = 1.073, ymin = 2.40, ymax = 2.60, colour = 'black', fill = 'black', alpha = 0.01) +
  annotate(geom = 'rect', xmin = 1.075, xmax = 1.078, ymin = 2.40, ymax = 2.60, colour = 'black', fill = 'black', alpha = 0.01) +
  annotate(geom = 'rect', xmin = 1.080, xmax = 1.083, ymin = 2.40, ymax = 2.60, colour = 'black', fill = 'black', alpha = 0.01) +
  annotate(geom = 'text', x = 1.092, y = 2.50, label = 'ADN', size = 7.2, colour = 'black') +
  annotate(geom = 'rect', xmin = 1.03, xmax = 1.033, ymin = 2.60, ymax = 2.80, colour = 'red', fill = 'red', alpha = 0.2) +
  annotate(geom = 'text', x = 1.0315, y = 2.75, label = 'A', size = 4.2, colour = 'black') +
  annotate(geom = 'text', x = 1.0315, y = 2.65, label = 'T', size = 4.2, colour = 'black') +
  geom_curve(x = 1.05, xend = 1.035, y = 2.55, yend = 2.70, arrow = arrow(length = unit(0.1, 'inch')), size = 0.8, color = 'black', curvature = 0.0, linetype = 'solid') +
  annotate(geom = 'rect', xmin = 1.03, xmax = 1.033, ymin = 2.20, ymax = 2.40, colour = 'red', fill = 'red', alpha = 0.01) +
  annotate(geom = 'text', x = 1.0315, y = 2.35, label = 'C', size = 4.2, colour = 'black') +
  annotate(geom = 'text', x = 1.0315, y = 2.25, label = 'G', size = 4.2, colour = 'black') +
  geom_curve(x = 1.05, xend = 1.035, y = 2.45, yend = 2.30, arrow = arrow(length = unit(0.1, 'inch')), size = 0.8, color = 'black', curvature = 0.0, linetype = 'solid') +
  annotate(geom = 'text', x = 1.054, y = 2.10, label = 'SNP', size = 4.2, colour = 'black') +
  geom_curve(x = 1.052, xend = 1.0515, y = 2.16, yend = 2.315, arrow = arrow(length = unit(0.1, 'inch')), size = 0.4, color = 'black', curvature = -0.1, linetype = 'solid') +
  geom_curve(x = 1.0215, xend = 1.0515, y = 3.89, yend = 2.745, arrow = arrow(length = unit(0.1, 'inch')), size = 0.8, color = 'black', curvature = -0.1, linetype = 'longdash') +
  
  # Se dibujan los SNPs en desequilibrio de ligamiento (LD):
  annotate(geom = 'text', x = 1.0265, y = 1.32, label = 'SNP', size = 5.2, colour = 'black') +
  annotate(geom = 'rect', xmin = 1.025, xmax = 1.028, ymin = 1.05, ymax = 1.25, colour = 'red', fill = 'red', alpha = 0.4) +
  annotate(geom = 'rect', xmin = 1.030, xmax = 1.033, ymin = 1.05, ymax = 1.25, colour = 'black', fill = 'black', alpha = 0.001) +
  annotate(geom = 'rect', xmin = 1.035, xmax = 1.038, ymin = 1.05, ymax = 1.25, colour = 'black', fill = 'black', alpha = 0.001) +
  annotate(geom = 'rect', xmin = 1.040, xmax = 1.043, ymin = 1.05, ymax = 1.25, colour = 'black', fill = 'black', alpha = 0.001) +
  annotate(geom = 'text', x = 1.0465, y = 1.32, label = 'SNP', size = 5.2, colour = 'black') +
  annotate(geom = 'rect', xmin = 1.045, xmax = 1.048, ymin = 1.05, ymax = 1.25, colour = 'cyan', fill = 'cyan', alpha = 0.4) +
  annotate(geom = 'rect', xmin = 1.050, xmax = 1.053, ymin = 1.05, ymax = 1.25, colour = 'black', fill = 'black', alpha = 0.001) +
  annotate(geom = 'rect', xmin = 1.055, xmax = 1.058, ymin = 1.05, ymax = 1.25, colour = 'black', fill = 'black', alpha = 0.001) +
  annotate(geom = 'text', x = 1.0615, y = 1.32, label = 'SNP', size = 5.2, colour = 'black') +
  annotate(geom = 'rect', xmin = 1.060, xmax = 1.063, ymin = 1.05, ymax = 1.25, colour = 'orange', fill = 'orange', alpha = 0.4) +
  annotate(geom = 'rect', xmin = 1.065, xmax = 1.068, ymin = 1.05, ymax = 1.25, colour = 'black', fill = 'black', alpha = 0.001) +
  annotate(geom = 'rect', xmin = 1.070, xmax = 1.073, ymin = 1.05, ymax = 1.25, colour = 'black', fill = 'black', alpha = 0.001) +
  annotate(geom = 'text', x = 1.0765, y = 1.32, label = 'SNP', size = 5.2, colour = 'black') +
  annotate(geom = 'rect', xmin = 1.075, xmax = 1.078, ymin = 1.05, ymax = 1.25, colour = 'green', fill = 'green', alpha = 0.4) +
  annotate(geom = 'rect', xmin = 1.080, xmax = 1.083, ymin = 1.05, ymax = 1.25, colour = 'black', fill = 'black', alpha = 0.001) +
  annotate(geom = 'text', x = 1.0865, y = 1.32, label = 'SNP', size = 5.2, colour = 'black') +
  annotate(geom = 'rect', xmin = 1.085, xmax = 1.088, ymin = 1.05, ymax = 1.25, colour = 'yellow', fill = 'yellow', alpha = 0.4) +
  annotate(geom = 'rect', xmin = 1.090, xmax = 1.093, ymin = 1.05, ymax = 1.25, colour = 'black', fill = 'black', alpha = 0.001) +
  annotate(geom = 'text', x = 1.123, y = 1.23, label = 'SNPs en desequili-', size = 7.2, colour = 'black') +
  annotate(geom = 'text', x = 1.123, y = 1.07, label = 'brio de ligamiento', size = 7.2, colour = 'black') +
  geom_curve(x = 1.1, xend = 1.095, y = 1.15, yend = 1.15, arrow = arrow(length = unit(0.1, 'inch')), size = 0.8, color = 'black', curvature = 0.0, linetype = 'solid') +

  # Se dibujan los SNPs en haplotipos, entre ellos el tag SNP:
  #annotate(geom = 'text', x = 1.0435, y = 0.49, label = 'QTL', size = 3.2, colour = 'black') +
  annotate(geom = 'rect', xmin = 1.042, xmax = 1.045, ymin = 0.25, ymax = 0.45, colour = 'red', fill = 'red', alpha = 0.4) +
  annotate(geom = 'rect', xmin = 1.047, xmax = 1.050, ymin = 0.25, ymax = 0.45, colour = 'cyan', fill = 'cyan', alpha = 0.4) +
  annotate(geom = 'rect', xmin = 1.052, xmax = 1.055, ymin = 0.25, ymax = 0.45, colour = 'orange', fill = 'orange', alpha = 0.4) +
  annotate(geom = 'text', x = 1.0585, y = 0.19, label = 'tag', size = 5.2, colour = 'black') +
  annotate(geom = 'text', x = 1.0585, y = 0.07, label = 'SNP', size = 5.2, colour = 'black') +
  annotate(geom = 'rect', xmin = 1.057, xmax = 1.060, ymin = 0.25, ymax = 0.45, colour = 'green', fill = 'green', alpha = 0.4) +
  annotate(geom = 'rect', xmin = 1.062, xmax = 1.065, ymin = 0.25, ymax = 0.45, colour = 'yellow', fill = 'yellow', alpha = 0.4) +
  annotate(geom = 'text', x = 1.085, y = 0.35, label = 'Haplotipo', size = 7.2, colour = 'black') +
  geom_curve(x = 1.073, xend = 1.067, y = 0.35, yend = 0.35, arrow = arrow(length = unit(0.1, 'inch')), size = 0.8, color = 'black', curvature = 0.0, linetype = 'solid') +

  # Se dibujan las fechas de los SNPs que por LD se transmiten juntos a la siguiente generación:
  geom_curve(x = 1.0265, xend = 1.0435, y = 1.02, yend = 0.54, arrow = arrow(length = unit(0.1, 'inch')), size = 0.8, color = 'black', curvature = 0.0, linetype = 'longdash') +
  geom_curve(x = 1.0465, xend = 1.0485, y = 1.02, yend = 0.50, arrow = arrow(length = unit(0.1, 'inch')), size = 0.8, color = 'black', curvature = 0.0, linetype = 'longdash') +
  geom_curve(x = 1.0615, xend = 1.0535, y = 1.02, yend = 0.50, arrow = arrow(length = unit(0.1, 'inch')), size = 0.8, color = 'black', curvature = 0.0, linetype = 'longdash') +
  geom_curve(x = 1.0765, xend = 1.0585, y = 1.02, yend = 0.54, arrow = arrow(length = unit(0.1, 'inch')), size = 0.8, color = 'black', curvature = 0.0, linetype = 'longdash') +
  geom_curve(x = 1.0865, xend = 1.0635, y = 1.02, yend = 0.54, arrow = arrow(length = unit(0.1, 'inch')), size = 0.8, color = 'black', curvature = 0.0, linetype = 'longdash') +

  scale_x_continuous(limits = c(1.0, 1.18)) +
  scale_y_continuous(limits = c(0.0, 4.0)) +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())

ggsave('expo_Cartagena/Figuras/tag_SNP.png', width = 30, height = 20, units = 'cm')
```

<!--
NOTA: Se realiza una visualización en donde se observa un pedigrí.
-->

```{r}
#| label: Gráfica de pedigrí

Puntos <- data.frame(x = c(1.0, 1.5, 0.75, 1.75, 1.0, 1.5, 2.0, 1.75, 2.25), y = c(c(2.8, 2.8, 1.5, 1.5, 0.2, 0.2, 0.2, -1.1, -1.1)))

Punto_x <- data.frame(x = 1.0, y = 2.8)

data.frame(x = 1.0, y = 1.0) |>
  ggplot() +
  
  geom_point(aes(x = x, y = y), data = Puntos, size = 5.6, shape = 21, color = 'black', fill = 'black', alpha = 0.8) +
  
  # Se construye las lineas que unen a cada individuo en el pedigrí:
  annotate(geom = 'segment', x = 1.0, xend = 0.75, y = 2.8, yend = 1.5, colour = 'black', size = 0.8) +
  annotate(geom = 'segment', x = 1.5, xend = 0.75, y = 2.8, yend = 1.5, colour = 'black', size = 0.8) +
  annotate(geom = 'segment', x = 1.5, xend = 1.25, y = 2.8, yend = 1.5, colour = 'black', size = 0.8) +
  annotate(geom = 'segment', x = 1.5, xend = 1.75, y = 2.8, yend = 1.5, colour = 'black', size = 0.8) +
  annotate(geom = 'segment', x = 1.25, xend = 1.0, y = 1.5, yend = 0.2, colour = 'black', size = 0.8) +
  annotate(geom = 'segment', x = 1.75, xend = 2.0, y = 1.5, yend = 0.2, colour = 'black', size = 0.8) +
  annotate(geom = 'segment', x = 1.75, xend = 1.5, y = 1.5, yend = 0.2, colour = 'black', size = 0.8) +  
  annotate(geom = 'segment', x = 1.75, xend = 2.0, y = -1.1, yend = 0.2, colour = 'black', size = 0.8) +
  annotate(geom = 'segment', x = 2.25, xend = 2.0, y = -1.1, yend = 0.2, colour = 'black', size = 0.8) +

  # Se indica el individuo sin información de fenotipo:
  annotate(geom = 'rect', xmin = 0.55, xmax = 1.05, ymin = 0.9, ymax = 1.3, colour = 'orange', fill = 'orange', alpha = 0.1) +
  annotate(geom = 'text', x = 0.8, y = 1.1, label = 'Sin fenotipo.', size = 3.2, colour = 'black') +
  geom_point(aes(x = x, y = y), data = Punto_x, size = 9.6, shape = 'X', color = 'red', fill = 'red', alpha = 0.8) +
  
  scale_x_continuous(limits = c(0.5, 2.45)) +
  scale_y_continuous(limits = c(-1.3, 3.0)) +  
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())

ggsave('expo_Cartagena/Figuras/ped_nadiv.png', width = 10, height = 10, units = 'cm')
```

<!--
NOTA: Se realiza una visualización donde se observa la imputación de 50k a HD, y de HD a 50k.
-->

```{r}
#| label: Imputación a densidades posteriores al control de calidad

Venn <- tibble(
  x = c(0.866, -0.866),
  y = c(-0.5, -0.5),
  Densidades = c('HD', '50k')
  )

# Número de individuos en cada densidad ----

ind_marc <- tibble(
  individuos = c(284, 2894)
  ) %>%
  mutate(
    x = c(1.5, -1.5),
    y = c(-0.5, -0.5),
    label = paste(individuos, '\nindividuos')
    )

imput_1 <- ggplot(data = Venn) +
  ggforce::geom_circle(aes(x0 = x, y0 = y, r = 1.5, fill = Densidades, colour = Densidades), alpha = 0.2, size = 1.0) + 
  coord_fixed() +
  scale_colour_manual(values = c('black', 'orange'), name = 'Densidad de marcador') +
  scale_fill_manual(values = c('white', 'orange'), name = 'Densidad de marcador') +
  labs(x = NULL, y = NULL) +
  theme_bw() +
  theme(
    legend.text = element_text(size = 28),
    legend.title = element_text(size = 28, face = 'bold'),
    legend.position = 'none',
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  ) +
  annotate('text', x = ind_marc$x, y = ind_marc$y, label = ind_marc$label, size = 11.5)

ggsave('expo_Cartagena/Figuras/imput_1.png', width = 20, height = 20, units = 'cm')

imput_2 <- ggplot(data = Venn) +
  ggforce::geom_circle(aes(x0 = x, y0 = y, r = 1.5, fill = Densidades, colour = Densidades), alpha = 0.2, size = 1.0) + 
  coord_fixed() +
  scale_colour_manual(values = c('black', 'orange'), name = 'Densidad de marcador') +
  scale_fill_manual(values = c('black', 'white'), name = 'Densidad de marcador') +
  labs(x = NULL, y = NULL) +
  theme_bw() +
  theme(
    legend.text = element_text(size = 28),
    legend.title = element_text(size = 28, face = 'bold'),
    legend.position = 'none',
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  ) +
  annotate('text', x = ind_marc$x, y = ind_marc$y, label = ind_marc$label, size = 11.5)

ggsave('expo_Cartagena/Figuras/imput_2.png', width = 20, height = 20, units = 'cm')

imput_3 <- ggplot(data = Venn) +
  ggforce::geom_circle(aes(x0 = x, y0 = y, r = 1.5, fill = Densidades, colour = Densidades), alpha = 0.2, size = 1.0) + 
  coord_fixed() +
  scale_colour_manual(values = c('black', 'orange'), name = 'Densidad') +
  scale_fill_manual(values = c('black', 'orange'), name = 'Densidad') +
  labs(x = NULL, y = NULL) +
  theme_bw() +
  theme(
    legend.text = element_text(size = 28),
    legend.title = element_text(size = 28, face = 'bold'),
    legend.position = 'left',
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  ) +
  annotate('text', x = ind_marc$x, y = ind_marc$y, label = ind_marc$label, size = 11.5)

ggsave('expo_Cartagena/Figuras/ley_imput.png', width = 20, height = 20, units = 'cm')
```

<!--
NOTA: Se realiza una visualización que representa los genotipos a HD.
-->

```{r}
#| label: Hola

Circulo <- tibble(
  x = c(0.866),
  y = c(-0.5),
  Densidad = 'HD'
  )

den_HD <- ggplot(data = Circulo) +
  ggforce::geom_circle(aes(x0 = x, y0 = y, r = 1.5, fill = Densidad, colour = Densidad), alpha = 0.2, size = 1.0) + 
  coord_fixed() +
  scale_colour_manual(values = 'orange', name = 'Densidad') +
  scale_fill_manual(values = 'orange', name = 'Densidad') +
  labs(x = NULL, y = NULL) +
  theme_bw() +
  theme(
    legend.text = element_text(size = 28),
    legend.title = element_text(size = 28, face = 'bold'),
    legend.position = 'left',
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

ggsave('expo_Cartagena/Figuras/den_HD.png', width = 20, height = 20, units = 'cm')
```

<!--
NOTA: Se realiza una visualización donde se representen los marcadores a densidad media (50k) y alta (HD).
-->

```{r}
#| label: Graficas de densidades 50k y HD

# Se dibuja la densidad de 50k ----

ggplot() +
  annotate(geom = 'rect', xmin = 1.0, xmax = 2.0, ymin = 1.0, ymax = 2.0, colour = 'black', fill = 'black', alpha = 0.2) +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())

ggsave('expo_Cartagena/Figuras/geno_50k.png', width = 10, height = 10, units = 'cm')

# Se dibuja la matriz de HD ----

ggplot() +
  annotate(geom = 'rect', xmin = 1.0, xmax = 2.0, ymin = 1.0, ymax = 2.0, colour = 'orange', fill = 'orange', alpha = 0.2) +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())

ggsave('expo_Cartagena/Figuras/geno_HD.png', width = 10, height = 10, units = 'cm')
```

<!--
NOTA: Se realiza una visualizaciín para representar la metodología del blup genómico de un solo paso.
-->

```{r}
#| label: Hola

ssGBLUP <- data.frame(
  x = 1.0, y = 1.0
  ) %>%
  ggplot() +
  #geom_blank() +
  
  annotate(geom = 'rect', xmin = 1.5, xmax = 4.25, ymin = 7.5, ymax = 9.5, colour = 'yellow', fill = 'yellow', alpha = 0.2) +
  annotate(geom = 'text', x = 2.875, y = 8.5, label = 'A', size = 8.4, colour = 'black') +
  annotate(geom = 'text', x = 1.1, y = 8.5, label = 'Matriz A', size = 7.6, angle = 90, colour = 'black') +
  
  annotate(geom = 'rect', xmin = 7.0, xmax = 8.75, ymin = 7.75, ymax = 9.0, colour = 'cyan', fill = 'cyan', alpha = 0.2) +
  annotate(geom = 'text', x = 7.875, y = 8.375, label = 'G', size = 8.4, colour = 'black') +
  annotate(geom = 'text', x = 6.6, y = 8.375, label = 'Matriz G', size = 7.6, angle = 90, colour = 'black') +
  
  annotate(geom = 'rect', xmin = 6.0, xmax = 8.75, ymin = 3.75, ymax = 5.75, colour = 'black', fill = 'white', alpha = 0.2) +
  annotate(geom = 'rect', xmin = 6.8, xmax = 8.55, ymin = 3.95, ymax = 5.05, colour = 'cyan', fill = 'cyan', alpha = 0.2) +
  annotate(geom = 'text', x = 5.6, y = 4.75, label = 'Matriz H', size = 7.6, angle = 90, colour = 'black') +
  
  #annotate(geom = 'rect', xmin = 6.275, xmax = 8.475, ymin = 1.4, ymax = 2.2, colour = 'black', fill = 'white', alpha = 0.2, linetype = 'dashed') +
  #annotate(geom = 'text', x = 7.375, y = 1.8, label = 'ssGBLUP', size = 7.6, colour = 'black') +
  #geom_curve(x = 7.375, xend = 7.375, y = 3.45, yend = 2.5, arrow = arrow(length = unit(0.1, 'inch')), size = 1.2, color = 'black', curvature = 0.0, linetype = 'dashed') +
  
  #annotate(geom = 'rect', xmin = 1.55, xmax = 3.75, ymin = 1.4, ymax = 2.2, colour = 'black', fill = 'white', alpha = 0.2, linetype = 'dashed') +
  #annotate(geom = 'text', x = 2.65, y = 1.8, label = 'BLUP', size = 7.6, colour = 'black') +
  
  geom_curve(x = 3.0, xend = 5.2, y = 7.3, yend = 4.9, arrow = arrow(length = unit(0.1, 'inch')), size = 1.2, color = 'black', curvature = 0.0, linetype = 'solid') +
  geom_curve(x = 7.875, xend = 7.875, y = 7.45, yend = 6.05, arrow = arrow(length = unit(0.1, 'inch')), size = 1.2, color = 'black', curvature = 0.0, linetype = 'solid') +
  #geom_curve(x = 2.65, xend = 2.65, y = 7.3, yend = 2.5, arrow = arrow(length = unit(0.1, 'inch')), size = 1.2, color = 'black', curvature = 0.0, linetype = 'dashed') +
  
  #scale_x_continuous(limits = c(0.45, 9.4)) +
  #scale_y_continuous(limits = c(1.0, 9.9)) +
  
  theme_bw() +
  #labs(title = 'ssGBLUP') +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.title = element_text(size = 11, face = 'bold'))

ggsave('expo_Cartagena/Figuras/ssGBLUP.png', width = 20, height = 20, units = 'cm')
```

<!--
NOTA: Se realiza una visualización donde se observa como se realizo el método LR.
-->

```{r}
#| label: Método LR

data.frame(x = 1.0, y = 1.0) |>
  ggplot() +

  # Se dibujan los datos completos y paciales:
  annotate(geom = 'rect', xmin = 1.0, xmax = 9.0, ymin = 1.0, ymax = 1.15, colour = 'orange', fill = 'orange', alpha = 0.2) +
  annotate(geom = 'rect', xmin = 1.0, xmax = 12.0, ymin = 1.75, ymax = 1.9, colour = 'orange', fill = 'orange', alpha = 0.2) +
  #annotate(geom = 'rect', xmin = 10.5, xmax = 12.0, ymin = 1.0, ymax = 1.15, colour = 'orange', fill = 'orange', alpha = 0.2) +

  
  # Se dibuja una línea que corresponde a los individuos focales (o de validación):
  annotate(geom = 'segment', x = 9.0, xend = 9.0, y = 1.0, yend = 1.9, colour = 'black', alpha = 1.2, linewidth = 1.0, linetype = 'longdash') +
  #annotate(geom = 'segment', x = 10.5, xend = 10.5, y = 1.0, yend = 1.9, colour = 'black', alpha = 1.2, linewidth = 1.0, linetype = 'longdash') +
  #geom_curve(x = 11.1, xend = 10.1, y = 1.68, yend = 1.73, arrow = arrow(length = unit(0.1, 'inch')), size = 0.4, color = 'black', curvature = -0.2, linetype = 'solid') +
  #annotate(geom = 'text', x = 11.9, y = 1.65, label = 'Validación', size = 3.8, colour = 'black') +

  # Se indica los EBV completos y parciales:
  annotate(geom = 'text', x = 14.8, y = 1.125, label = '(G)EBV parcial', size = 4.8, colour = 'black') +
  annotate(geom = 'text', x = 14.8, y = 1.875, label = '(G)EBV completo', size = 4.8, colour = 'black') +
  geom_curve(x = 12.2, xend = 12.8, y = 1.125, yend = 1.125, arrow = arrow(length = unit(0.1, 'inch')), size = 1.8, color = 'black', curvature = 0.0, linetype = 'solid') +
  geom_curve(x = 12.2, xend = 12.8, y = 1.875, yend = 1.875, arrow = arrow(length = unit(0.1, 'inch')), size = 1.8, color = 'black', curvature = 0.0, linetype = 'solid') +
  
  # Se escriben las formulas del método LR:
  #geom_curve(x = 16.2, xend = 16.8, y = 1.5, yend = 1.5, arrow = arrow(length = unit(0.1, 'inch')), size = 1.8, color = 'black', curvature = 0.0, linetype = 'solid') +
  #annotate(geom = 'rect', xmin = 17.2, xmax = 21.2, ymin = 0.95, ymax = 2.05, colour = 'black', fill = 'black', alpha = 0.01) +
  #annotate(geom = 'text', x = 19.2, y = 1.875, label = 'Delta[p] == mu[p] - mu[w]', size = 3.8, colour = 'black', parse = TRUE) +
  #annotate(geom = 'text', x = 19.2, y = 1.5, label = 'b[p] == frac(cov(mu[p] - mu[w]), var(mu[p]))', size = 3.8, colour = 'black', parse = TRUE) +
  #annotate(geom = 'text', x = 19.2, y = 1.125, label = 'hat(acc[p])', size = 3.8, colour = 'black', parse = TRUE) +

  # Se dibujan los años de toma de datos:
  annotate(geom = 'text', x = 1.0, y = 1.21, label = '1984', size = 3.4, colour = 'black') +
  annotate(geom = 'segment', x = 1.0, xend = 1.0, y = 1.15, yend = 1.18, colour = 'orange') +
  #annotate(geom = 'text', x = 8.7, y = 1.21, label = '2017', size = 3.4, colour = 'black', angle = 45) +
  #annotate(geom = 'text', x = 10.9, y = 1.21, label = '2019', size = 3.4, colour = 'black', angle = 45) +
  #annotate(geom = 'text', x = 12.0, y = 1.21, label = '2023', size = 3.4, colour = 'black') +
  #annotate(geom = 'segment', x = 12.0, xend = 12.0, y = 1.15, yend = 1.18, colour = 'orange') +
  annotate(geom = 'text', x = 1.0, y = 1.96, label = '1984', size = 3.4, colour = 'black') +
  annotate(geom = 'segment', x = 1.0, xend = 1.0, y = 1.9, yend = 1.93, colour = 'orange') +
  annotate(geom = 'text', x = 8.7, y = 1.96, label = '2017', size = 3.4, colour = 'black') +
  annotate(geom = 'segment', x = 9.0, xend = 9.0, y = 1.9, yend = 1.93, colour = 'orange') +
  #annotate(geom = 'text', x = 10.9, y = 1.96, label = '2019', size = 3.4, colour = 'black') +
  #annotate(geom = 'segment', x = 10.5, xend = 10.5, y = 1.9, yend = 1.93, colour = 'orange') +
  annotate(geom = 'text', x = 12.0, y = 1.96, label = '2023', size = 3.4, colour = 'black') +
  annotate(geom = 'segment', x = 12.0, xend = 12.0, y = 1.9, yend = 1.93, colour = 'orange') +
  
  labs(title = 'Descripción esquemática de la validación mediante el método LR', x = NULL, y = NULL) +
  scale_x_continuous(limits = c(1.0, 16.2)) +
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.title = element_text(size = 10, face = 'bold'))

ggsave('expo_Cartagena/Figuras/metodo_LR.png', width = 20, height = 8, units = 'cm')
```

<!--
NOTA: Se realiza la visualización con los resultados de las estimas del método LR.
-->

```{r}
#| label: Estadísticas del método LR.

# Se importa los datos con las estimas para el caracter peso al destete (del análisis uni-caracter) y posteriormente se calcula los intervalos de confianza al 95% para cada estima ----

LR_est_PD <- read_delim(file = 'eva_genetica/Datos/metodo_LR/peso_Dtte/Estadisticos_LR_PD_uni.txt', col_names = TRUE, delim = ' ')

lower_bounds <- vector() # Se crea un vector para almacenar los límites inferiores de los intervalos de confianza.
upper_bounds <- vector() # Se crea un vector para almacenar los límites superiores de los intervalos de confianza.

for (i in 1:nrow(LR_est_PD)) { # Mediante un ciclio for se calcula los intervalos de confianza al 95% para cada valor de estimación.
  # Estimación:
  valor <- LR_est_PD$Valor[i]
  # Error estándar:
  error_estandar <- LR_est_PD$Error_estandar[i]
  # Calculo del límite inferior del intervalo de confianza:
  lower_bound <- valor - 1.96 * error_estandar
  # Calculo del límite superior del intervalo de confianza:
  upper_bound <- valor + 1.96 * error_estandar
  # Se agrega los límites a los vectores correspondientes:
  lower_bounds <- c(lower_bounds, lower_bound)
  upper_bounds <- c(upper_bounds, upper_bound)
  }

intervalos_confianza <- tibble(
  ICI = lower_bounds,
  ICS = upper_bounds
  )

LR_est_PD_2 <- bind_cols(LR_est_PD, intervalos_confianza) |>
  mutate(
    Escenarios = case_when(
      Densidad_marcador == '50k_directo' ~ 'E1_D',
      Densidad_marcador == '50k_materno' ~ 'E1_M',
      Densidad_marcador == 'SNP_tags_directo' ~ 'E3_D',
      Densidad_marcador == 'SNP_tags_materno' ~ 'E3_M',
      Densidad_marcador == 'SNP_tags_sing_directo' ~ 'E4_D',
      Densidad_marcador == 'SNP_tags_sing_materno' ~ 'E4_M',
      Densidad_marcador == 'HD_directo' ~ 'E2_D',
      Densidad_marcador == 'HD_materno' ~ 'E2_M'
      )
    )

# Se importa los datos con las estimas para los caracteres edad al primer partor e intervalo entre el primer y segundo parto (del análisis bi-caracter) y posteriormente se calcula los intervalos de confianza al 95% para cada estima ----

LR_est_EPP_IEP <- read_delim(file = 'eva_genetica/Datos/metodo_LR/EPP_IEP/Estadisticos_LR_EPP_IEP_bi.txt', col_names = TRUE, delim = ' ')

lower_bounds <- vector() # Se crea un vector para almacenar los límites inferiores de los intervalos de confianza.
upper_bounds <- vector() # Se crea un vector para almacenar los límites superiores de los intervalos de confianza.

for (i in 1:nrow(LR_est_EPP_IEP)) { # Mediante un ciclio for se calcula los intervalos de confianza al 95% para cada valor de estimación.
  # Estimación:
  valor <- LR_est_EPP_IEP$Valor[i]
  # Error estándar:
  error_estandar <- LR_est_EPP_IEP$Error_estandar[i]
  # Calculo del límite inferior del intervalo de confianza:
  lower_bound <- valor - 1.96 * error_estandar
  # Calculo del límite superior del intervalo de confianza:
  upper_bound <- valor + 1.96 * error_estandar
  # Se agrega los límites a los vectores correspondientes:
  lower_bounds <- c(lower_bounds, lower_bound)
  upper_bounds <- c(upper_bounds, upper_bound)
  }

intervalos_confianza <- tibble(
  ICI = lower_bounds,
  ICS = upper_bounds
  )

LR_est_EPP_IEP_2 <- bind_cols(LR_est_EPP_IEP, intervalos_confianza) |>
  mutate(
    Escenarios = case_when(
      Densidad_marcador == '50k' ~ 'E1',
      Densidad_marcador == 'SNP_tags' ~ 'E3',
      Densidad_marcador == 'SNP_tags_sing' ~ 'E4',
      Densidad_marcador == 'HD' ~ 'E2'
      )
    )

# Se unen los resultados del análisis uni- y bi-carácter ----

LR_est <- bind_rows(LR_est_PD_2, LR_est_EPP_IEP_2)

# Se visualizan los resultados ----

orden_escenarios <- c('E1', 'E1_D', 'E1_M', 'E2', 'E2_D', 'E2_M', 'E3', 'E3_D', 'E3_M', 'E4', 'E4_D', 'E4_M') # Se define el orden deseado de las variables en el eje x.

LR_est <- LR_est |>
  mutate(Escenarios = factor(Escenarios, levels = orden_escenarios)) # Se convierte la variable densidad_marcador en factor con el orden deseado.

#####################################################################
# 1. Edad al primer parto e intervalo entre el primer y segundo parto
#####################################################################

#######
# Sesgo
#######

sesgo <- LR_est |>
  filter(Estadistico == 'level_bias_in_GSD')

sesgo_EPP <- ggplot(data = sesgo |> filter(Caracter == 'Edad_primer_parto' & Densidad_marcador %in% c('50k', 'HD', 'SNP_tags', 'SNP_tags_sing')), aes(x = Escenarios, y = Valor, fill = Escenarios, colour = Escenarios)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.2) +
  ggrepel::geom_label_repel(data = sesgo |> filter(Caracter == 'Edad_primer_parto' & Densidad_marcador %in% c('50k', 'HD', 'SNP_tags', 'SNP_tags_sing')), aes(label = paste(round(Valor, digits = 5), '±', round(Error_estandar, digits = 2))), size = 5.4, box.padding = 0.0, direction = 'y', fill = 'white', colour = 'black') +
  labs(title = 'Edad al primer parto', y = 'Sesgo', x = NULL) +
  scale_colour_manual(values = c('cyan', 'green', 'red', 'orange')) +
  scale_fill_manual(values = c('cyan', 'green', 'red', 'orange')) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = 'bold'),
    axis.title = element_text(size = 18, face = 'bold'),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 17, face = 'bold'),
    legend.position = 'none',
    legend.title = element_text(size = 18, face = 'bold'),
    legend.text = element_text(size = 17)
    )

ggsave('expo_Cartagena/Figuras/sesgo_EPP_uni_bi.png', width = 26, height = 26, units = 'cm')

sesgo_IEP <- ggplot(data = sesgo |> filter(Caracter == 'intervalo_P1_P2' & Densidad_marcador %in% c('50k', 'HD', 'SNP_tags', 'SNP_tags_sing')), aes(x = Escenarios, y = Valor, fill = Escenarios, colour = Escenarios)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.2) +
  ggrepel::geom_label_repel(data = sesgo |> filter(Caracter == 'intervalo_P1_P2' & Densidad_marcador %in% c('50k', 'HD', 'SNP_tags', 'SNP_tags_sing')), aes(label = paste(round(Valor, digits = 5), '±', round(Error_estandar, digits = 2))), size = 5.4, box.padding = 0.0, direction = 'y', fill = 'white', colour = 'black') +
  labs(title = 'Intervalo entre el primer y el segundo parto', y = NULL, x = NULL) +
  scale_colour_manual(values = c('cyan', 'green', 'red', 'orange')) +
  scale_fill_manual(values = c('cyan', 'green', 'red', 'orange')) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = 'bold'),
    axis.title = element_text(size = 18, face = 'bold'),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 17, face = 'bold'),
    legend.position = 'right',
    legend.title = element_text(size = 18, face = 'bold'),
    legend.text = element_text(size = 17)
    )

ggsave('expo_Cartagena/Figuras/sesgo_IEP_uni_bi.png', width = 26, height = 26, units = 'cm')

############
# Dispersión
############

dispersion <- LR_est |>
  filter(Estadistico == 'dispersion_bias')

dispersion_EPP <- ggplot(data = dispersion |> filter(Caracter == 'Edad_primer_parto' & Densidad_marcador %in% c('50k', 'HD', 'SNP_tags', 'SNP_tags_sing')), aes(x = Escenarios, y = Valor, fill = Escenarios, colour = Escenarios)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.2) +
  ggrepel::geom_label_repel(data = dispersion |> filter(Caracter == 'Edad_primer_parto' & Densidad_marcador %in% c('50k', 'HD', 'SNP_tags', 'SNP_tags_sing')), aes(label = paste(round(Valor, digits = 2), '±', round(Error_estandar, digits = 2))), size = 4.4, box.padding = 0.0, direction = 'y', fill = 'white', colour = 'black') +
  labs(title = 'Edad al primer parto', y = 'Dispersión', x = NULL) +
  scale_colour_manual(values = c('cyan', 'green', 'red', 'orange')) +
  scale_fill_manual(values = c('cyan', 'green', 'red', 'orange')) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = 'bold'),
    axis.title = element_text(size = 18, face = 'bold'),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 17, face = 'bold'),
    legend.position = 'none',
    legend.title = element_text(size = 18, face = 'bold'),
    legend.text = element_text(size = 17)
    )

ggsave('expo_Cartagena/Figuras/dispersion_EPP_uni_bi.png', width = 26, height = 26, units = 'cm')

dispersion_IEP <- ggplot(data = dispersion |> filter(Caracter == 'intervalo_P1_P2' & Densidad_marcador %in% c('50k', 'HD', 'SNP_tags', 'SNP_tags_sing')), aes(x = Escenarios, y = Valor, fill = Escenarios, colour = Escenarios)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.2) +
  ggrepel::geom_label_repel(data = dispersion |> filter(Caracter == 'intervalo_P1_P2' & Densidad_marcador %in% c('50k', 'HD', 'SNP_tags', 'SNP_tags_sing')), aes(label = paste(round(Valor, digits = 2), '±', round(Error_estandar, digits = 2))), size = 4.4, box.padding = 0.0, direction = 'y', fill = 'white', colour = 'black') +
  labs(title = 'Intervalo entre el primer y el segundo parto', y = NULL, x = NULL) +
  scale_colour_manual(values = c('cyan', 'green', 'red', 'orange')) +
  scale_fill_manual(values = c('cyan', 'green', 'red', 'orange')) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = 'bold'),
    axis.title = element_text(size = 18, face = 'bold'),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 17, face = 'bold'),
    legend.position = 'right',
    legend.title = element_text(size = 18, face = 'bold'),
    legend.text = element_text(size = 17)
    )

ggsave('expo_Cartagena/Figuras/dispersion_IEP_uni_bi.png', width = 26, height = 26, units = 'cm')

###########
# Precisión
###########

precision <- LR_est |>
  filter(Estadistico == 'accuracy_partial')

precision_EPP <- ggplot(data = precision |> filter(Caracter == 'Edad_primer_parto' & Densidad_marcador %in% c('50k', 'HD', 'SNP_tags', 'SNP_tags_sing')), aes(x = Escenarios, y = Valor, fill = Escenarios, colour = Escenarios)) +
  #geom_hline(yintercept = 0.46, linetype = 'dashed', color = 'black', size = 1) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.2) +
  ggrepel::geom_label_repel(data = precision |> filter(Caracter == 'Edad_primer_parto' & Densidad_marcador %in% c('50k')), aes(label = paste(round(Valor, digits = 2))), size = 8.4, box.padding = 0.4, direction = 'both', nudge_y = 0.02, fill = 'white', colour = 'black') +
  labs(title = 'EPP', y = 'Precisión', x = NULL) +
  scale_y_continuous(limits = c(0.0, 0.5)) +
  scale_colour_manual(values = c('cyan', 'green', 'red', 'orange')) +
  scale_fill_manual(values = c('cyan', 'green', 'red', 'orange')) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 24, face = 'bold'),
    axis.title = element_text(size = 24, face = 'bold'),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 23, face = 'bold'),
    legend.position = 'none',
    legend.title = element_text(size = 24, face = 'bold'),
    legend.text = element_text(size = 23)
    )

ggsave('expo_Cartagena/Figuras/precision_EPP_uni_bi.png', width = 20, height = 20, units = 'cm')

precision_IEP <- ggplot(data = precision |> filter(Caracter == 'intervalo_P1_P2' & Densidad_marcador %in% c('50k', 'HD', 'SNP_tags', 'SNP_tags_sing')), aes(x = Escenarios, y = Valor, fill = Escenarios, colour = Escenarios)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.2) +
  ggrepel::geom_label_repel(data = precision |> filter(Caracter == 'intervalo_P1_P2' & Densidad_marcador %in% c('50k')), aes(label = paste(round(Valor, digits = 2))), size = 8.4, box.padding = 0.4, direction = 'both', nudge_y = 0.02, fill = 'white', colour = 'black') +
  labs(title = 'IEP', y = NULL, x = NULL) +
  scale_y_continuous(limits = c(0.0, 0.5)) +
  scale_colour_manual(values = c('cyan', 'green', 'red', 'orange')) +
  scale_fill_manual(values = c('cyan', 'green', 'red', 'orange')) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 24, face = 'bold'),
    axis.title = element_text(size = 24, face = 'bold'),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.position = 'right',
    legend.title = element_text(size = 22, face = 'bold'),
    legend.text = element_text(size = 21)
    )

ggsave('expo_Cartagena/Figuras/precision_IEP_uni_bi.png', width = 20, height = 20, units = 'cm')

(precision_EPP | precision_IEP)

ggsave('expo_Cartagena/Figuras/precision_EPP_IEP_uni_bi.png', width = 40, height = 20, units = 'cm')

####################
# 2. Peso al destete
####################

#######
# Sesgo
#######

#####################
# 3.1. Efecto directo
#####################

sesgo <- LR_est |>
  filter(
    Estadistico == 'level_bias_in_GSD',
    str_detect(Densidad_marcador, '_directo')
    )

sesgo_PD_directo <- ggplot(data = sesgo |> filter(Densidad_marcador %in% c('50k_directo', 'HD_directo', 'SNP_tags_directo', 'SNP_tags_sing_directo')) |> mutate(Densidad_marcador_2 = case_when(Densidad_marcador == '50k_directo' | Densidad_marcador == '50k_directo' ~ 'E1', Densidad_marcador == 'HD_directo' | Densidad_marcador == 'HD_materno' ~ 'E2', Densidad_marcador == 'SNP_tags_directo' | Densidad_marcador == 'SNP_tags_materno' ~ 'E3', Densidad_marcador == 'SNP_tags_sing_directo' | Densidad_marcador == 'SNP_tags_sing_materno' ~ 'E4')), aes(x = Escenarios, y = Valor, fill = Densidad_marcador_2, colour = Densidad_marcador_2)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.2) +
  ggrepel::geom_label_repel(data = sesgo |> filter(Densidad_marcador %in% c('50k_directo', 'HD_directo', 'SNP_tags_directo', 'SNP_tags_sing_directo')), aes(label = paste(round(Valor, digits = 4), '±', round(Error_estandar, digits = 2))), size = 4.4, box.padding = 0.0, direction = 'y', fill = 'white', colour = 'black') +
  labs(title = 'Peso al destete - efecto directo', y = 'Sesgo', x = NULL, fill = 'Escenarios', colour = 'Escenarios') +
  scale_colour_manual(values = c('cyan', 'green', 'red', 'orange')) +
  scale_fill_manual(values = c('cyan', 'green', 'red', 'orange')) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = 'bold'),
    axis.title = element_text(size = 18, face = 'bold'),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 17, face = 'bold'),
    legend.position = 'none',
    legend.title = element_text(size = 18, face = 'bold'),
    legend.text = element_text(size = 17)
    )

ggsave('expo_Cartagena/Figuras/sesgo_PD_uni_bi_dir.pdf', width = 40, height = 20, units = 'cm')

#####################
# 3.2. Efecto materno
#####################

sesgo <- LR_est |>
  filter(
    Estadistico == 'level_bias_in_GSD',
    str_detect(Densidad_marcador, '_materno')
    )

sesgo_PD_materno <- ggplot(data = sesgo |> filter(Densidad_marcador %in% c('50k_materno', 'HD_materno', 'SNP_tags_materno', 'SNP_tags_sing_materno')) |> mutate(Densidad_marcador_2 = case_when(Densidad_marcador == '50k_materno' | Densidad_marcador == '50k_materno' ~ 'E1', Densidad_marcador == 'HD_materno' | Densidad_marcador == 'HD_materno' ~ 'E2', Densidad_marcador == 'SNP_tags_materno' | Densidad_marcador == 'SNP_tags_materno' ~ 'E3', Densidad_marcador == 'SNP_tags_sing_materno' | Densidad_marcador == 'SNP_tags_sing_materno' ~ 'E4')), aes(x = Escenarios, y = Valor, fill = Densidad_marcador_2, colour = Densidad_marcador_2)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.2) +
  ggrepel::geom_label_repel(data = sesgo |> filter(Densidad_marcador %in% c('50k_materno', 'HD_materno', 'SNP_tags_materno', 'SNP_tags_sing_materno')), aes(label = paste(round(Valor, digits = 4), '±', round(Error_estandar, digits = 2))), size = 4.4, box.padding = 0.0, direction = 'y', fill = 'white', colour = 'black') +
  labs(title = 'Peso al destete - efecto materno', y = NULL, x = NULL, fill = 'Escenarios', colour = 'Escenarios') +
  scale_colour_manual(values = c('cyan', 'green', 'red', 'orange')) +
  scale_fill_manual(values = c('cyan', 'green', 'red', 'orange')) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = 'bold'),
    axis.title = element_text(size = 18, face = 'bold'),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 17, face = 'bold'),
    legend.position = 'right',
    legend.title = element_text(size = 18, face = 'bold'),
    legend.text = element_text(size = 17)
    )

ggsave('expo_Cartagena/Figuras/sesgo_PD_uni_bi_mat.pdf', width = 40, height = 20, units = 'cm')

############
# Dispersion
############

###################
# 1. Efecto directo
###################

dispersion <- LR_est |>
  filter(
    Estadistico == 'dispersion_bias',
    str_detect(Densidad_marcador, '_directo')
    )

dispersion_PD_directo <- ggplot(data = dispersion |> filter(Densidad_marcador %in% c('50k_directo', 'HD_directo', 'SNP_tags_directo', 'SNP_tags_sing_directo')) |> mutate(Densidad_marcador_2 = case_when(Densidad_marcador == '50k_directo' | Densidad_marcador == '50k_directo' ~ 'E1', Densidad_marcador == 'HD_directo' | Densidad_marcador == 'HD_directo' ~ 'E2', Densidad_marcador == 'SNP_tags_directo' | Densidad_marcador == 'SNP_tags_directo' ~ 'E3', Densidad_marcador == 'SNP_tags_sing_directo' | Densidad_marcador == 'SNP_tags_sing_directo' ~ 'E4')), aes(x = Escenarios, y = Valor, fill = Densidad_marcador_2, colour = Densidad_marcador_2)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.2) +
  ggrepel::geom_label_repel(data = dispersion |> filter(Densidad_marcador %in% c('50k_directo', 'HD_directo', 'SNP_tags_directo', 'SNP_tags_sing_directo')), aes(label = paste(round(Valor, digits = 2), '±', round(Error_estandar, digits = 2))), size = 4.4, box.padding = 0.0, direction = 'y', fill = 'white', colour = 'black') +
  labs(title = 'Peso al destete - efecto directo', y = 'Dispersion', x = NULL, fill = 'Escenarios', colour = 'Escenarios') +
  scale_colour_manual(values = c('cyan', 'green', 'red', 'orange')) +
  scale_fill_manual(values = c('cyan', 'green', 'red', 'orange')) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = 'bold'),
    axis.title = element_text(size = 18, face = 'bold'),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 17, face = 'bold'),
    legend.position = 'none',
    legend.title = element_text(size = 18, face = 'bold'),
    legend.text = element_text(size = 17)
    )

ggsave('expo_Cartagena/Figuras/dispersion_PD_uni_bi_dir.png', width = 20, height = 20, units = 'cm')

###################
# 2. Efecto materno
###################

dispersion <- LR_est_PD_2 |>
  filter(
    Estadistico == 'dispersion_bias',
    str_detect(Densidad_marcador, '_materno')
    )

dispersion_PD_materno <- ggplot(data = dispersion |> filter(Densidad_marcador %in% c('50k_materno', 'HD_materno', 'SNP_tags_materno', 'SNP_tags_sing_materno')) |> mutate(Densidad_marcador_2 = case_when(Densidad_marcador == '50k_materno' | Densidad_marcador == '50k_materno' ~ 'E1', Densidad_marcador == 'HD_materno' | Densidad_marcador == 'HD_materno' ~ 'E2', Densidad_marcador == 'SNP_tags_materno' | Densidad_marcador == 'SNP_tags_materno' ~ 'E3', Densidad_marcador == 'SNP_tags_sing_materno' | Densidad_marcador == 'SNP_tags_sing_materno' ~ 'E4')), aes(x = Escenarios, y = Valor, fill = Densidad_marcador_2, colour = Densidad_marcador_2)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.2) +
  ggrepel::geom_label_repel(data = dispersion |> filter(Densidad_marcador %in% c('50k_materno', 'HD_materno', 'SNP_tags_materno', 'SNP_tags_sing_materno')), aes(label = paste(round(Valor, digits = 2), '±', round(Error_estandar, digits = 2))), size = 4.4, box.padding = 0.0, direction = 'y', fill = 'white', colour = 'black') +
  labs(title = 'Peso al destete - efecto materno', y = NULL, x = NULL, fill = 'Escenarios', colour = 'Escenarios') +
  scale_colour_manual(values = c('cyan', 'green', 'red', 'orange')) +
  scale_fill_manual(values = c('cyan', 'green', 'red', 'orange')) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = 'bold'),
    axis.title = element_text(size = 18, face = 'bold'),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 17, face = 'bold'),
    legend.position = 'rihgt',
    legend.title = element_text(size = 18, face = 'bold'),
    legend.text = element_text(size = 17)
    )

ggsave('expo_Cartagena/Figuras/dispersion_PD_uni_bi_mat.png', width = 20, height = 20, units = 'cm')

###########
# Precisión
###########

###################
# 1. Efecto directo
###################

precision <- LR_est |>
  filter(
    Estadistico == 'accuracy_partial',
    str_detect(Densidad_marcador, '_directo')
    )

precision_PD_directo <- ggplot(data = precision |> filter(Densidad_marcador %in% c('50k_directo', 'HD_directo', 'SNP_tags_directo', 'SNP_tags_sing_directo')) |> mutate(Densidad_marcador_2 = case_when(Densidad_marcador == '50k_directo' | Densidad_marcador == '50k_directo' ~ 'E1', Densidad_marcador == 'HD_directo' | Densidad_marcador == 'HD_directo' ~ 'E2', Densidad_marcador == 'SNP_tags_directo' | Densidad_marcador == 'SNP_tags_directo' ~ 'E3', Densidad_marcador == 'SNP_tags_sing_directo' | Densidad_marcador == 'SNP_tags_sing_directo' ~ 'E4')), aes(x = Escenarios, y = Valor, fill = Densidad_marcador_2, colour = Densidad_marcador_2)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.2) +
  ggrepel::geom_label_repel(data = precision |> filter(Densidad_marcador %in% c('50k_directo')), aes(label = paste(round(Valor, digits = 2))), size = 8.4, box.padding = 0.4, direction = 'both', nudge_y = 0.02, fill = 'white', colour = 'black') +
  labs(title = 'PD - efecto directo', y = 'Precisión', x = NULL, fill = 'Escenarios', colour = 'Escenarios') +
  scale_y_continuous(limits = c(0.0, 0.41)) +
  scale_colour_manual(values = c('cyan', 'green', 'red', 'orange')) +
  scale_fill_manual(values = c('cyan', 'green', 'red', 'orange')) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 24, face = 'bold'),
    axis.title = element_text(size = 24, face = 'bold'),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 23, face = 'bold'),
    legend.position = 'none',
    legend.title = element_text(size = 24, face = 'bold'),
    legend.text = element_text(size = 23)
    )

ggsave('expo_Cartagena/Figuras/precision_PD_uni_bi_dir.png', width = 20, height = 20, units = 'cm')

###################
# 2. Efecto materno
###################

precision <- LR_est_PD_2 |>
  filter(
    Estadistico == 'accuracy_partial',
    str_detect(Densidad_marcador, '_materno')
    )

precision_PD_materno <- ggplot(data = precision |> filter(Densidad_marcador %in% c('50k_materno', 'HD_materno', 'SNP_tags_materno', 'SNP_tags_sing_materno')) |> mutate(Densidad_marcador_2 = case_when(Densidad_marcador == '50k_materno' | Densidad_marcador == '50k_materno' ~ 'E1', Densidad_marcador == 'HD_materno' | Densidad_marcador == 'HD_materno' ~ 'E2', Densidad_marcador == 'SNP_tags_materno' | Densidad_marcador == 'SNP_tags_materno' ~ 'E3', Densidad_marcador == 'SNP_tags_sing_materno' | Densidad_marcador == 'SNP_tags_sing_materno' ~ 'E4')), aes(x = Escenarios, y = Valor, fill = Densidad_marcador_2, colour = Densidad_marcador_2)) +
  geom_col(position = position_dodge(width = 0.7), width = 0.6, alpha = 0.2) +
  ggrepel::geom_label_repel(data = precision |> filter(Densidad_marcador %in% c('50k_materno')), aes(label = paste(round(Valor, digits = 2))), size = 8.4, box.padding = 0.4, direction = 'both', nudge_y = 0.02, fill = 'white', colour = 'black') +
  labs(title = 'PD - efecto materno', y = NULL, x = NULL, fill = 'Escenarios', colour = 'Escenarios') +
  scale_y_continuous(limits = c(0.0, 0.41)) +
  scale_colour_manual(values = c('cyan', 'green', 'red', 'orange')) +
  scale_fill_manual(values = c('cyan', 'green', 'red', 'orange')) +
  theme_bw() +
  theme(
    plot.title = element_text(size = 24, face = 'bold'),
    axis.title = element_text(size = 24, face = 'bold'),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = 'right',
    legend.title = element_text(size = 24, face = 'bold'),
    legend.text = element_text(size = 23)
    )

ggsave('expo_Cartagena/Figuras/precision_PD_uni_bi_mat.png', width = 20, height = 20, units = 'cm')

(precision_PD_directo | precision_PD_materno)

ggsave('expo_Cartagena/Figuras/precision_PD_uni_bi_dir_mat.png', width = 40, height = 20, units = 'cm')
```
